import type {
  Shipment,
  Ticket,
  ActivityItem,
  RevenueDataPoint,
  RegionalData,
  BlogPost,
  RoleConfig,
  FleetDriver,
  FleetVehicle,
  CapacityMatch,
  RouteOptimization,
} from '@/types';

export const roleConfigs: RoleConfig[] = [
  {
    id: 'admin',
    label: 'Administrator',
    icon: 'Shield',
    description: 'Vollzugriff auf alle Plattformfunktionen',
    availableTabs: ['dashboard', 'shipments', 'tracking', 'fleet', 'capacity', 'support', 'analytics', 'blog', 'settings'],
  },
  {
    id: 'dispatcher',
    label: 'Disponent',
    icon: 'Radio',
    description: 'Sendungsverwaltung und Routenplanung',
    availableTabs: ['dashboard', 'shipments', 'tracking', 'fleet', 'capacity', 'support', 'settings'],
  },
  {
    id: 'driver',
    label: 'Fahrer',
    icon: 'Truck',
    description: 'Aktive Lieferungen und Routennavigation',
    availableTabs: ['dashboard', 'tracking', 'fleet', 'settings'],
  },
  {
    id: 'shipper',
    label: 'Versender',
    icon: 'Package',
    description: 'Sendungen erstellen und Pakete verfolgen',
    availableTabs: ['dashboard', 'shipments', 'tracking', 'capacity', 'settings'],
  },
  {
    id: 'warehouse',
    label: 'Lager',
    icon: 'Warehouse',
    description: 'Bestandsverwaltung und Lagerverwaltung',
    availableTabs: ['dashboard', 'shipments', 'tracking', 'fleet', 'analytics', 'settings'],
  },
  {
    id: 'support',
    label: 'Support',
    icon: 'Headphones',
    description: 'Ticketverwaltung und Konfliktlösung',
    availableTabs: ['dashboard', 'support', 'tracking', 'settings'],
  },
  {
    id: 'finance',
    label: 'Finanzen',
    icon: 'Euro',
    description: 'Rechnungen, Zahlungen und Berichte',
    availableTabs: ['dashboard', 'shipments', 'capacity', 'analytics', 'settings'],
  },
  {
    id: 'customer',
    label: 'Kunde',
    icon: 'User',
    description: 'Pakete verfolgen und Support kontaktieren',
    availableTabs: ['dashboard', 'tracking', 'support', 'blog', 'settings'],
  },
];

export const shipments: Shipment[] = [
  {
    id: 'SHP-001',
    trackingNumber: 'CB-DE-2024-001245',
    sender: 'BMW AG',
    senderAddress: 'Petuelring 130, 80809 München',
    receiver: 'Autohaus Berlin GmbH',
    receiverAddress: 'Friedrichstraße 123, 10117 Berlin',
    status: 'in_transit',
    weight: 2450,
    dimensions: '2.5m × 1.8m × 1.2m',
    pickupDate: '2024-12-15',
    deliveryDate: '',
    estimatedDelivery: '2024-12-17',
    driver: 'Hans Müller',
    vehicle: 'MAN TGX 18.500',
    route: 'München → Nürnberg → Leipzig → Berlin',
    cost: 1285.50,
    insurance: true,
    priority: 'express',
  },
  {
    id: 'SHP-002',
    trackingNumber: 'CB-DE-2024-001246',
    sender: 'Siemens AG',
    senderAddress: 'Wittelsbacherplatz 2, 80333 München',
    receiver: 'Hamburger Hafen GmbH',
    receiverAddress: 'Am Sandtorkai 48, 20457 Hamburg',
    status: 'delivered',
    weight: 5200,
    dimensions: '6.0m × 2.4m × 2.6m',
    pickupDate: '2024-12-10',
    deliveryDate: '2024-12-13',
    estimatedDelivery: '2024-12-13',
    driver: 'Klaus Schmidt',
    vehicle: 'Mercedes Actros 1845',
    route: 'München → Stuttgart → Frankfurt → Hamburg',
    cost: 2890.00,
    insurance: true,
    priority: 'standard',
  },
  {
    id: 'SHP-003',
    trackingNumber: 'CB-DE-2024-001247',
    sender: 'BASF SE',
    senderAddress: 'Carl-Bosch-Straße 38, 67056 Ludwigshafen',
    receiver: 'Bayer CropScience',
    receiverAddress: 'Alfred-Nobel-Straße 50, 40789 Monheim',
    status: 'pending',
    weight: 890,
    dimensions: '1.2m × 0.8m × 1.0m',
    pickupDate: '2024-12-18',
    deliveryDate: '',
    estimatedDelivery: '2024-12-19',
    driver: '',
    vehicle: 'VW Crafter',
    route: 'Ludwigshafen → Mannheim → Köln → Monheim',
    cost: 456.75,
    insurance: false,
    priority: 'standard',
  },
  {
    id: 'SHP-004',
    trackingNumber: 'CB-DE-2024-001248',
    sender: 'Adidas AG',
    senderAddress: 'Adi-Dassler-Straße 1, 91074 Herzogenaurach',
    receiver: 'Sportarena Wien',
    receiverAddress: 'Wagramer Straße 74, 1220 Wien, Österreich',
    status: 'out_for_delivery',
    weight: 1250,
    dimensions: '3.0m × 2.0m × 1.5m',
    pickupDate: '2024-12-14',
    deliveryDate: '',
    estimatedDelivery: '2024-12-16',
    driver: 'Stefan Weber',
    vehicle: 'Scania R450',
    route: 'Herzogenaurach → Nürnberg → Regensburg → Wien',
    cost: 1580.00,
    insurance: true,
    priority: 'overnight',
  },
  {
    id: 'SHP-005',
    trackingNumber: 'CB-DE-2024-001249',
    sender: 'SAP SE',
    senderAddress: 'Dietmar-Hopp-Allee 16, 69190 Walldorf',
    receiver: 'Google Ireland',
    receiverAddress: 'Gordon House, Barrow Street, Dublin, Irland',
    status: 'processing',
    weight: 320,
    dimensions: '0.5m × 0.4m × 0.3m',
    pickupDate: '2024-12-19',
    deliveryDate: '',
    estimatedDelivery: '2024-12-23',
    driver: '',
    vehicle: '',
    route: 'Walldorf → Frankfurt → Amsterdam → Dublin',
    cost: 2150.00,
    insurance: true,
    priority: 'express',
  },
  {
    id: 'SHP-006',
    trackingNumber: 'CB-DE-2024-001250',
    sender: 'Volkswagen AG',
    senderAddress: 'Berliner Ring 2, 38440 Wolfsburg',
    receiver: 'Autohaus Hamburg Nord',
    receiverAddress: 'Langenhorner Chaussee 302, 22419 Hamburg',
    status: 'delivered',
    weight: 1800,
    dimensions: '4.5m × 2.0m × 1.8m',
    pickupDate: '2024-12-08',
    deliveryDate: '2024-12-09',
    estimatedDelivery: '2024-12-09',
    driver: 'Peter Fischer',
    vehicle: 'Volvo FH16',
    route: 'Wolfsburg → Hannover → Hamburg',
    cost: 890.00,
    insurance: true,
    priority: 'standard',
  },
  {
    id: 'SHP-007',
    trackingNumber: 'CB-DE-2024-001251',
    sender: 'Bosch GmbH',
    senderAddress: 'Gerlingstraße 34, 70499 Stuttgart',
    receiver: 'Continental AG',
    receiverAddress: 'Vahrenwalder Straße 9, 30165 Hannover',
    status: 'cancelled',
    weight: 750,
    dimensions: '1.5m × 1.0m × 0.8m',
    pickupDate: '2024-12-12',
    deliveryDate: '',
    estimatedDelivery: '2024-12-14',
    driver: 'Thomas Braun',
    vehicle: 'DAF XF 480',
    route: 'Stuttgart → Frankfurt → Hannover',
    cost: 645.00,
    insurance: false,
    priority: 'standard',
  },
  {
    id: 'SHP-008',
    trackingNumber: 'CB-DE-2024-001252',
    sender: 'Deutsche Telekom AG',
    senderAddress: 'Landgrabenweg 151, 53227 Bonn',
    receiver: 'Telekom Shop Berlin',
    receiverAddress: 'Kurfürstendamm 21, 10719 Berlin',
    status: 'in_transit',
    weight: 430,
    dimensions: '2.0m × 1.5m × 1.5m',
    pickupDate: '2024-12-16',
    deliveryDate: '',
    estimatedDelivery: '2024-12-17',
    driver: 'Michael Wagner',
    vehicle: 'Iveco S-Way',
    route: 'Bonn → Köln → Düsseldorf → Dortmund → Berlin',
    cost: 720.00,
    insurance: false,
    priority: 'express',
  },
  {
    id: 'SHP-009',
    trackingNumber: 'CB-DE-2024-001253',
    sender: 'Lufthansa Cargo',
    senderAddress: 'Flughafen Frankfurt, 60547 Frankfurt',
    receiver: 'DHL Express Hub Leipzig',
    receiverAddress: 'Zur Hallerschen Aue 2, 04356 Leipzig',
    status: 'delivered',
    weight: 6800,
    dimensions: '8.0m × 2.4m × 2.4m',
    pickupDate: '2024-12-05',
    deliveryDate: '2024-12-06',
    estimatedDelivery: '2024-12-06',
    driver: 'Andreas Becker',
    vehicle: 'Scania R500',
    route: 'Frankfurt → Leipzig',
    cost: 1540.00,
    insurance: true,
    priority: 'overnight',
  },
  {
    id: 'SHP-010',
    trackingNumber: 'CB-DE-2024-001254',
    sender: 'Henkel AG',
    senderAddress: 'Henkelstraße 67, 40191 Düsseldorf',
    receiver: 'DM-Drogerie Markt',
    receiverAddress: 'Am Goldenen Turm 1, 72336 Balingen',
    status: 'pending',
    weight: 2100,
    dimensions: '4.0m × 2.0m × 2.0m',
    pickupDate: '2024-12-20',
    deliveryDate: '',
    estimatedDelivery: '2024-12-22',
    driver: '',
    vehicle: 'MAN TGS 26.480',
    route: 'Düsseldorf → Köln → Frankfurt → Stuttgart → Balingen',
    cost: 1120.00,
    insurance: true,
    priority: 'standard',
  },
  {
    id: 'SHP-011',
    trackingNumber: 'CB-DE-2024-001255',
    sender: 'Allianz SE',
    senderAddress: 'Königinstraße 28, 80802 München',
    receiver: 'HDI Versicherung',
    receiverAddress: 'Röpckestraße 2, 30179 Hannover',
    status: 'in_transit',
    weight: 150,
    dimensions: '0.8m × 0.6m × 0.4m',
    pickupDate: '2024-12-15',
    deliveryDate: '',
    estimatedDelivery: '2024-12-16',
    driver: 'Rolf Hoffmann',
    vehicle: 'Mercedes Sprinter',
    route: 'München → Nürnberg → Würzburg → Frankfurt → Hannover',
    cost: 540.00,
    insurance: false,
    priority: 'express',
  },
  {
    id: 'SHP-012',
    trackingNumber: 'CB-DE-2024-001256',
    sender: 'E.ON SE',
    senderAddress: 'Ruhrallee 93, 45128 Essen',
    receiver: 'Vattenfall Europe',
    receiverAddress: 'Alexanderplatz 6, 10178 Berlin',
    status: 'delivered',
    weight: 3400,
    dimensions: '5.0m × 2.2m × 2.0m',
    pickupDate: '2024-12-07',
    deliveryDate: '2024-12-10',
    estimatedDelivery: '2024-12-09',
    driver: 'Wolfgang Schneider',
    vehicle: 'Volvo FM 460',
    route: 'Essen → Dortmund → Hannover → Berlin',
    cost: 1650.00,
    insurance: true,
    priority: 'standard',
  },
];

export const tickets: Ticket[] = [
  {
    id: 'TKT-001',
    subject: 'Verspätete Lieferung - CB-DE-2024-001255',
    description: 'Die Sendung CB-DE-2024-001255 ist um 2 Tage verspätet. Der Kunde verlangt eine Erklärung.',
    priority: 'high',
    status: 'open',
    customer: 'HDI Versicherung',
    shipmentId: 'CB-DE-2024-001255',
    createdAt: '2024-12-16T10:30:00Z',
    updatedAt: '2024-12-16T10:30:00Z',
    assignedTo: 'Maria Schneider',
    messages: [
      { id: 'MSG-001', sender: 'HDI Versicherung', content: 'Wir haben die Sendung noch nicht erhalten. Geschätzte Lieferung war gestern.', timestamp: '2024-12-16T10:30:00Z', isAgent: false },
      { id: 'MSG-002', sender: 'Maria Schneider', content: 'Vielen Dank für Ihre Meldung. Wir prüfen den Status der Sendung und melden uns zurück.', timestamp: '2024-12-16T11:15:00Z', isAgent: true },
    ],
  },
  {
    id: 'TKT-002',
    subject: 'Beschädigte Ware bei Ankunft',
    description: 'Das Paket bei Sendung CB-DE-2024-001246 wurde beim Entladen beschädigt.',
    priority: 'urgent',
    status: 'in_progress',
    customer: 'Hamburger Hafen GmbH',
    shipmentId: 'CB-DE-2024-001246',
    createdAt: '2024-12-14T08:45:00Z',
    updatedAt: '2024-12-15T14:20:00Z',
    assignedTo: 'Thomas Meier',
    messages: [
      { id: 'MSG-003', sender: 'Hamburger Hafen GmbH', content: 'Bei der Ankunft haben wir festgestellt, dass die Verpackung beschädigt ist. Drei Artikel sind unbrauchbar.', timestamp: '2024-12-14T08:45:00Z', isAgent: false },
      { id: 'MSG-004', sender: 'Thomas Meier', content: 'Wir bedauern sehr die Unannehmlichkeiten. Eine Schadensmeldung wurde eingeleitet. Bitte senden Sie Fotos der Beschädigung.', timestamp: '2024-12-14T10:00:00Z', isAgent: true },
      { id: 'MSG-005', sender: 'Hamburger Hafen GmbH', content: 'Fotos wurden per E-Mail gesendet. Wann können wir mit einer Lösung rechnen?', timestamp: '2024-12-15T09:30:00Z', isAgent: false },
    ],
  },
  {
    id: 'TKT-003',
    subject: 'Preisanfrage für Großauftrag',
    description: 'Wir planen einen Großauftrag mit monatlich ca. 50 Sendungen nach Skandinavien.',
    priority: 'medium',
    status: 'open',
    customer: 'IKEA Deutschland',
    createdAt: '2024-12-16T14:00:00Z',
    updatedAt: '2024-12-16T14:00:00Z',
    messages: [
      { id: 'MSG-006', sender: 'IKEA Deutschland', content: 'Könnten Sie uns ein Angebot für regelmäßige Sendungen nach Schweden und Norwegen machen?', timestamp: '2024-12-16T14:00:00Z', isAgent: false },
    ],
  },
  {
    id: 'TKT-004',
    subject: 'Falsche Adresse auf Lieferschein',
    description: 'Die Empfängeradresse auf der Sendung CB-DE-2024-001248 ist inkorrekt.',
    priority: 'high',
    status: 'resolved',
    customer: 'Sportarena Wien',
    shipmentId: 'CB-DE-2024-001248',
    createdAt: '2024-12-15T09:00:00Z',
    updatedAt: '2024-12-15T16:30:00Z',
    assignedTo: 'Maria Schneider',
    messages: [
      { id: 'MSG-007', sender: 'Sportarena Wien', content: 'Die korrekte Adresse ist Mariahilfer Straße 124, nicht Wagramer Straße 74.', timestamp: '2024-12-15T09:00:00Z', isAgent: false },
      { id: 'MSG-008', sender: 'Maria Schneider', content: 'Vielen Dank für den Hinweis. Die Adresse wurde korrigiert und der Fahrer wurde informiert.', timestamp: '2024-12-15T11:00:00Z', isAgent: true },
      { id: 'MSG-009', sender: 'Sportarena Wien', content: 'Perfekt, die Sendung wurde korrekt zugestellt. Vielen Dank!', timestamp: '2024-12-15T16:30:00Z', isAgent: false },
    ],
  },
  {
    id: 'TKT-005',
    subject: 'Rechnungskorrektur erforderlich',
    description: 'Die Rechnung für Sendung CB-DE-2024-001250 enthält einen falschen Betrag.',
    priority: 'low',
    status: 'closed',
    customer: 'Autohaus Hamburg Nord',
    shipmentId: 'CB-DE-2024-001250',
    createdAt: '2024-12-10T13:00:00Z',
    updatedAt: '2024-12-12T10:00:00Z',
    assignedTo: 'Lisa Klein',
    messages: [
      { id: 'MSG-010', sender: 'Autohaus Hamburg Nord', content: 'Auf der Rechnung steht €890,00, aber es wurden nur €750,00 vereinbart.', timestamp: '2024-12-10T13:00:00Z', isAgent: false },
      { id: 'MSG-011', sender: 'Lisa Klein', content: 'Sie haben recht, es war ein Tippfehler. Die korrigierte Rechnung wurde per E-Mail versandt.', timestamp: '2024-12-11T09:00:00Z', isAgent: true },
      { id: 'MSG-012', sender: 'Autohaus Hamburg Nord', content: 'Korrigierte Rechnung erhalten. Vielen Dank!', timestamp: '2024-12-12T10:00:00Z', isAgent: false },
    ],
  },
  {
    id: 'TKT-006',
    subject: 'Neuen Kundenstatus beantragen',
    description: 'Wir möchten von Standard-Kunde auf Premium-Kunde wechseln.',
    priority: 'low',
    status: 'open',
    customer: 'MediaMarkt Deutschland',
    createdAt: '2024-12-16T16:00:00Z',
    updatedAt: '2024-12-16T16:00:00Z',
    messages: [
      { id: 'MSG-013', sender: 'MediaMarkt Deutschland', content: 'Bitte teilen Sie uns die Konditionen für den Premium-Status mit.', timestamp: '2024-12-16T16:00:00Z', isAgent: false },
    ],
  },
  {
    id: 'TKT-007',
    subject: 'Sendung fehlt - CB-DE-2024-001251',
    description: 'Die Sendung CB-DE-2024-001251 wurde storniert, aber die Ware wurde nie retourniert.',
    priority: 'urgent',
    status: 'in_progress',
    customer: 'Continental AG',
    shipmentId: 'CB-DE-2024-001251',
    createdAt: '2024-12-14T16:00:00Z',
    updatedAt: '2024-12-16T09:00:00Z',
    assignedTo: 'Thomas Meier',
    messages: [
      { id: 'MSG-014', sender: 'Continental AG', content: 'Wir haben die Sendung am 12.12. storniert. Wo befindet sich unsere Ware?', timestamp: '2024-12-14T16:00:00Z', isAgent: false },
      { id: 'MSG-015', sender: 'Thomas Meier', content: 'Die Sendung wurde am Hub in Frankfurt zurückgehalten. Die Rücksendung wird heute eingeleitet.', timestamp: '2024-12-16T09:00:00Z', isAgent: true },
    ],
  },
];

export const activities: ActivityItem[] = [
  { id: 'ACT-001', type: 'shipment', title: 'Neue Sendung erstellt', description: 'CB-DE-2024-001254 - Henkel AG → DM-Drogerie', timestamp: '2024-12-16T15:30:00Z', icon: 'Package' },
  { id: 'ACT-002', type: 'delivery', title: 'Lieferung bestätigt', description: 'CB-DE-2024-001256 - E.ON → Vattenfall', timestamp: '2024-12-16T14:15:00Z', icon: 'CheckCircle' },
  { id: 'ACT-003', type: 'payment', title: 'Zahlung eingegangen', description: '€2.890,00 von Siemens AG', timestamp: '2024-12-16T13:00:00Z', icon: 'CreditCard' },
  { id: 'ACT-004', type: 'alert', title: 'Verspätung gemeldet', description: 'CB-DE-2024-001255 - Wetterbedingte Verzögerung', timestamp: '2024-12-16T12:00:00Z', icon: 'AlertTriangle' },
  { id: 'ACT-005', type: 'system', title: 'Fahrer zugewiesen', description: 'Andreas Becker → CB-DE-2024-001253', timestamp: '2024-12-16T11:30:00Z', icon: 'User' },
  { id: 'ACT-006', type: 'delivery', title: 'Sendung abgeholt', description: 'CB-DE-2024-001252 - Bonn', timestamp: '2024-12-16T10:45:00Z', icon: 'Truck' },
  { id: 'ACT-007', type: 'shipment', title: 'Route aktualisiert', description: 'CB-DE-2024-001251 - Neue Strecke berechnet', timestamp: '2024-12-16T10:00:00Z', icon: 'Map' },
  { id: 'ACT-008', type: 'payment', title: 'Rechnung erstellt', description: 'RE-2024-00891 für Volkswagen AG', timestamp: '2024-12-16T09:15:00Z', icon: 'FileText' },
];

export const revenueData: RevenueDataPoint[] = [
  { month: 'Jan', revenue: 142000, shipments: 320 },
  { month: 'Feb', revenue: 138500, shipments: 295 },
  { month: 'Mär', revenue: 165200, shipments: 380 },
  { month: 'Apr', revenue: 172800, shipments: 410 },
  { month: 'Mai', revenue: 195400, shipments: 445 },
  { month: 'Jun', revenue: 210000, shipments: 490 },
  { month: 'Jul', revenue: 198600, shipments: 465 },
  { month: 'Aug', revenue: 185200, shipments: 420 },
  { month: 'Sep', revenue: 223000, shipments: 510 },
  { month: 'Okt', revenue: 245600, shipments: 560 },
  { month: 'Nov', revenue: 268400, shipments: 615 },
  { month: 'Dez', revenue: 298000, shipments: 680 },
];

export const regionalData: RegionalData[] = [
  { region: 'Deutschland', shipments: 2450, revenue: 1850000, growth: 12.5 },
  { region: 'Österreich', shipments: 680, revenue: 520000, growth: 8.3 },
  { region: 'Schweiz', shipments: 420, revenue: 380000, growth: 15.2 },
  { region: 'Niederlande', shipments: 310, revenue: 245000, growth: -2.1 },
  { region: 'Belgien', shipments: 190, revenue: 152000, growth: 5.7 },
  { region: 'Frankreich', shipments: 280, revenue: 198000, growth: 18.4 },
  { region: 'Tschechien', shipments: 150, revenue: 95000, growth: 22.1 },
  { region: 'Polen', shipments: 220, revenue: 135000, growth: 10.8 },
];

export const blogPosts: BlogPost[] = [
  {
    id: 'BLG-001',
    title: 'Die Zukunft der Logistik: KI-gesteuerte Routenoptimierung',
    excerpt: 'Wie künstliche Intelligenz die Lieferketten von morgen revolutioniert und Kosten um bis zu 30% senken kann.',
    content: 'Die Logistikbranche steht vor einer Revolution. Durch den Einsatz von Künstlicher Intelligenz können Routen in Echtzeit optimiert werden, was zu erheblichen Kosteneinsparungen und kürzeren Lieferzeiten führt. Unsere neueste Studie zeigt, dass AI-gesteuerte Systeme die Effizienz um bis zu 30% steigern können...',
    coverImage: 'https://picsum.photos/seed/logistics-ai/800/400',
    author: 'Dr. Anna Weber',
    category: 'Technologie',
    tags: ['KI', 'Routenoptimierung', 'Innovation'],
    publishedAt: '2024-12-15',
    readTime: 8,
  },
  {
    id: 'BLG-002',
    title: 'Elektromobilität in der Güterlogistik: Erfahrungen und Ausblick',
    excerpt: 'Unsere ersten 12 Monate mit Elektro-LKW auf deutschen Autobahnen - eine Bestandsaufnahme.',
    content: 'Seit Anfang 2024 setzen wir erstmals Elektro-LKW auf ausgewählten Routen ein. Die Ergebnisse sind ermutigend: Obwohl die Reichweitenlimitierungen eine Herausforderung darstellen, konnten wir auf Strecken unter 300 km signifikante Kostenreduzierungen erzielen...',
    coverImage: 'https://picsum.photos/seed/electric-truck/800/400',
    author: 'Markus Stein',
    category: 'Nachhaltigkeit',
    tags: ['Elektro-LKW', 'Nachhaltigkeit', 'Flotte'],
    publishedAt: '2024-12-10',
    readTime: 12,
  },
  {
    id: 'BLG-003',
    title: 'Neue Partnerschaft mit DHL Express: Schnellere Zustellungen in Europa',
    excerpt: 'CargoBit und DHL Express schließen strategische Partnerschaft für grenzüberschreitende Sendungen.',
    content: 'Wir freuen uns, unsere neue strategische Partnerschaft mit DHL Express bekannt zu geben. Diese Zusammenarbeit ermöglicht uns, unsere grenzüberschreitenden Lieferzeiten in Europa um durchschnittlich 24 Stunden zu verkürzen...',
    coverImage: 'https://picsum.photos/seed/partnership/800/400',
    author: 'Sarah Koch',
    category: 'Unternehmen',
    tags: ['Partnerschaft', 'DHL', 'Europa'],
    publishedAt: '2024-12-05',
    readTime: 5,
  },
  {
    id: 'BLG-004',
    title: 'CargoBit eröffnet neues Logistikzentrum in Leipzig',
    excerpt: 'Das modernste Logistikzentrum Mitteldeutschlands geht in Betrieb.',
    content: 'Am 1. Dezember haben wir unser neues Logistikzentrum in Leipzig offiziell eröffnet. Mit einer Fläche von 25.000 Quadratmetern und modernster Automatisierungstechnik ist es eines der fortschrittlichsten Zentren in Mitteldeutschland...',
    coverImage: 'https://picsum.photos/seed/warehouse-new/800/400',
    author: 'Thomas Richter',
    category: 'Unternehmen',
    tags: ['Expansion', 'Leipzig', 'Logistikzentrum'],
    publishedAt: '2024-12-01',
    readTime: 6,
  },
  {
    id: 'BLG-005',
    title: '5 Tipps für effizienteres Lieferkettenmanagement im Winter',
    excerpt: 'Winterzeit bedeutet Herausforderungen für die Logistik. So bereiten Sie sich optimal vor.',
    content: 'Der Winter bringt besondere Herausforderungen für die Logistikbranche mit sich. Von verspäteten Lieferungen bis hin zu beschädigter Ware - hier sind unsere Top 5 Tipps, wie Sie Ihre Lieferkette auch bei Kälte und Schnee effizient halten...',
    coverImage: 'https://picsum.photos/seed/winter-logistics/800/400',
    author: 'Lisa Müller',
    category: 'Tipps',
    tags: ['Winter', 'Lieferkette', 'Tipps'],
    publishedAt: '2024-11-28',
    readTime: 7,
  },
  {
    id: 'BLG-006',
    title: 'Digitaler Zwilling: Wie wir Sendungen virtuell simulieren',
    excerpt: 'Mit digitalen Zwillingen simulieren wir Lieferungen vorab und optimieren so den gesamten Prozess.',
    content: 'CargoBit setzt zunehmend auf digitale Zwillinge, um Sendungen bereits vor der physischen Durchführung zu simulieren. Diese Technologie ermöglicht es uns, potenzielle Probleme zu erkennen und zu beheben, bevor sie auftreten...',
    coverImage: 'https://picsum.photos/seed/digital-twin/800/400',
    author: 'Dr. Anna Weber',
    category: 'Technologie',
    tags: ['Digitaler Zwilling', 'Simulation', 'Technologie'],
    publishedAt: '2024-11-22',
    readTime: 10,
  },
];

export const kpiData = {
  admin: [
    { label: 'activeShipments', value: 1247, change: 12.5, changeLabel: 'vs. letzten Monat', icon: 'Package' },
    { label: 'revenue', value: 298000, change: 11.1, changeLabel: 'vs. letzten Monat', icon: 'TrendingUp' },
    { label: 'deliveriesToday', value: 342, change: 8.3, changeLabel: 'vs. gestern', icon: 'Truck' },
    { label: 'avgRating', value: 4.8, change: 0.2, changeLabel: 'vs. letzten Monat', icon: 'Star' },
  ],
  dispatcher: [
    { label: 'activeShipments', value: 89, change: 5.2, changeLabel: 'heute aktiv', icon: 'Package' },
    { label: 'deliveriesToday', value: 342, change: 8.3, changeLabel: 'heute geplant', icon: 'Truck' },
    { label: 'revenue', value: 45200, change: 3.1, changeLabel: 'heute', icon: 'TrendingUp' },
    { label: 'avgRating', value: 4.6, change: 0.1, changeLabel: 'Kundenrating', icon: 'Star' },
  ],
  driver: [
    { label: 'deliveriesToday', value: 8, change: 2, changeLabel: 'heute erledigt', icon: 'Truck' },
    { label: 'activeShipments', value: 2, change: 0, changeLabel: 'restlich', icon: 'Package' },
    { label: 'revenue', value: 1450, change: 15.2, changeLabel: 'heute verdient', icon: 'TrendingUp' },
    { label: 'avgRating', value: 4.9, change: 0.3, changeLabel: 'Kundenrating', icon: 'Star' },
  ],
  shipper: [
    { label: 'activeShipments', value: 15, change: 3, changeLabel: 'aktive Sendungen', icon: 'Package' },
    { label: 'revenue', value: 12850, change: 5.5, changeLabel: 'dieser Monat', icon: 'TrendingUp' },
    { label: 'deliveriesToday', value: 3, change: 1, changeLabel: 'heute geliefert', icon: 'Truck' },
    { label: 'avgRating', value: 4.7, change: 0.1, changeLabel: 'Liefer-Qualität', icon: 'Star' },
  ],
  warehouse: [
    { label: 'activeShipments', value: 45, change: 7.2, changeLabel: 'im Lager', icon: 'Package' },
    { label: 'revenue', value: 18500, change: 4.8, changeLabel: 'Umsatz heute', icon: 'TrendingUp' },
    { label: 'deliveriesToday', value: 28, change: 12, changeLabel: 'Ausgang heute', icon: 'Truck' },
    { label: 'avgRating', value: 4.5, change: 0.2, changeLabel: 'Prozesseffizienz', icon: 'Star' },
  ],
  support: [
    { label: 'activeShipments', value: 7, change: 2, changeLabel: 'offene Tickets', icon: 'Package' },
    { label: 'revenue', value: 95.2, change: 3.4, changeLabel: 'Lösungsrate %', icon: 'TrendingUp' },
    { label: 'deliveriesToday', value: 23, change: 5, changeLabel: 'heute bearbeitet', icon: 'Truck' },
    { label: 'avgRating', value: 4.6, change: 0.2, changeLabel: 'Zufriedenheit', icon: 'Star' },
  ],
  finance: [
    { label: 'revenue', value: 298000, change: 11.1, changeLabel: 'Monatsumsatz', icon: 'TrendingUp' },
    { label: 'activeShipments', value: 245, change: 15.3, changeLabel: 'offene Rechnungen', icon: 'Package' },
    { label: 'deliveriesToday', value: 18, change: 4, changeLabel: 'Zahlungen heute', icon: 'Truck' },
    { label: 'avgRating', value: 97.8, change: 1.2, changeLabel: 'Zahlungsquote %', icon: 'Star' },
  ],
  customer: [
    { label: 'activeShipments', value: 3, change: 1, changeLabel: 'aktive Sendungen', icon: 'Package' },
    { label: 'revenue', value: 2450, change: 0, changeLabel: 'offener Betrag', icon: 'TrendingUp' },
    { label: 'deliveriesToday', value: 1, change: 1, changeLabel: 'heute geliefert', icon: 'Truck' },
    { label: 'avgRating', value: 4.8, change: 0, changeLabel: 'Gesamtbewertung', icon: 'Star' },
  ],
};

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(amount);
}

export function formatNumber(num: number): string {
  return new Intl.NumberFormat('de-DE').format(num);
}

export function formatDate(dateStr: string): string {
  return new Intl.DateTimeFormat('de-DE', { day: '2-digit', month: '2-digit', year: 'numeric' }).format(new Date(dateStr));
}

export function formatDateTime(dateStr: string): string {
  return new Intl.DateTimeFormat('de-DE', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(new Date(dateStr));
}

export function getTimeAgo(dateStr: string): string {
  const now = new Date();
  const date = new Date(dateStr);
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMins / 60);
  const diffDays = Math.floor(diffHours / 24);

  if (diffMins < 1) return 'Gerade eben';
  if (diffMins < 60) return `vor ${diffMins} Min.`;
  if (diffHours < 24) return `vor ${diffHours} Std.`;
  return `vor ${diffDays} Tag${diffDays > 1 ? 'en' : ''}`;
}

export function getStatusColor(status: string): string {
  switch (status) {
    case 'pending': return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400';
    case 'processing': return 'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-400';
    case 'in_transit': return 'bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-400';
    case 'out_for_delivery': return 'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-400';
    case 'delivered': return 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400';
    case 'cancelled': return 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400';
    case 'returned': return 'bg-gray-100 text-gray-800 dark:bg-gray-900/30 dark:text-gray-400';
    default: return 'bg-gray-100 text-gray-800 dark:bg-gray-900/30 dark:text-gray-400';
  }
}

export function getPriorityColor(priority: string): string {
  switch (priority) {
    case 'low': return 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400';
    case 'medium': return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400';
    case 'high': return 'bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-400';
    case 'urgent': return 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400';
    default: return 'bg-gray-100 text-gray-800 dark:bg-gray-900/30 dark:text-gray-400';
  }
}

// ==========================================
// FLEET MANAGEMENT DATA
// ==========================================

export const fleetDrivers: FleetDriver[] = [
  {
    id: 'DRV-001',
    name: 'Hans Müller',
    phone: '+49 170 1234567',
    email: 'h.mueller@cargobit.de',
    license: 'CE-5839274',
    status: 'en_route',
    currentVehicle: 'VH-001',
    currentRoute: 'München → Nürnberg → Leipzig → Berlin',
    completedDeliveries: 847,
    rating: 4.9,
    location: 'Nürnberg',
    languages: ['Deutsch', 'Englisch'],
  },
  {
    id: 'DRV-002',
    name: 'Klaus Schmidt',
    phone: '+49 171 2345678',
    email: 'k.schmidt@cargobit.de',
    license: 'CE-6738291',
    status: 'available',
    currentVehicle: 'VH-002',
    currentRoute: '',
    completedDeliveries: 1203,
    rating: 4.7,
    location: 'München',
    languages: ['Deutsch', 'Englisch', 'Französisch'],
  },
  {
    id: 'DRV-003',
    name: 'Stefan Weber',
    phone: '+49 172 3456789',
    email: 's.weber@cargobit.de',
    license: 'CE-7492836',
    status: 'en_route',
    currentVehicle: 'VH-004',
    currentRoute: 'Herzogenaurach → Nürnberg → Regensburg → Wien',
    completedDeliveries: 562,
    rating: 4.8,
    location: 'Regensburg',
    languages: ['Deutsch', 'Englisch'],
  },
  {
    id: 'DRV-004',
    name: 'Michael Wagner',
    phone: '+49 173 4567890',
    email: 'm.wagner@cargobit.de',
    license: 'C-8392745',
    status: 'en_route',
    currentVehicle: 'VH-008',
    currentRoute: 'Bonn → Köln → Düsseldorf → Dortmund → Berlin',
    completedDeliveries: 389,
    rating: 4.6,
    location: 'Düsseldorf',
    languages: ['Deutsch'],
  },
  {
    id: 'DRV-005',
    name: 'Andreas Becker',
    phone: '+49 174 5678901',
    email: 'a.becker@cargobit.de',
    license: 'CE-9273648',
    status: 'on_break',
    currentVehicle: 'VH-009',
    currentRoute: 'Frankfurt → Leipzig',
    completedDeliveries: 945,
    rating: 4.9,
    location: 'Fulda Raststätte',
    languages: ['Deutsch', 'Englisch', 'Spanisch'],
  },
  {
    id: 'DRV-006',
    name: 'Peter Fischer',
    phone: '+49 175 6789012',
    email: 'p.fischer@cargobit.de',
    license: 'CE-6382947',
    status: 'resting',
    currentVehicle: 'VH-006',
    currentRoute: '',
    completedDeliveries: 678,
    rating: 4.5,
    location: 'Hamburg',
    languages: ['Deutsch', 'Englisch'],
  },
  {
    id: 'DRV-007',
    name: 'Thomas Braun',
    phone: '+49 176 7890123',
    email: 't.braun@cargobit.de',
    license: 'CE-5839274',
    status: 'offline',
    currentVehicle: '',
    currentRoute: '',
    completedDeliveries: 421,
    rating: 4.3,
    location: 'Stuttgart',
    languages: ['Deutsch'],
  },
  {
    id: 'DRV-008',
    name: 'Rolf Hoffmann',
    phone: '+49 177 8901234',
    email: 'r.hoffmann@cargobit.de',
    license: 'C-7483926',
    status: 'en_route',
    currentVehicle: 'VH-011',
    currentRoute: 'München → Nürnberg → Würzburg → Frankfurt → Hannover',
    completedDeliveries: 256,
    rating: 4.8,
    location: 'Würzburg',
    languages: ['Deutsch', 'Englisch'],
  },
  {
    id: 'DRV-009',
    name: 'Wolfgang Schneider',
    phone: '+49 178 9012345',
    email: 'w.schneider@cargobit.de',
    license: 'CE-8392746',
    status: 'available',
    currentVehicle: 'VH-012',
    currentRoute: '',
    completedDeliveries: 1102,
    rating: 4.7,
    location: 'Essen',
    languages: ['Deutsch', 'Niederländisch'],
  },
  {
    id: 'DRV-010',
    name: 'Lisa Meier',
    phone: '+49 179 0123456',
    email: 'l.meier@cargobit.de',
    license: 'C-9283746',
    status: 'en_route',
    currentVehicle: 'VH-014',
    currentRoute: 'Düsseldorf → Köln → Frankfurt → Stuttgart → Balingen',
    completedDeliveries: 178,
    rating: 4.9,
    location: 'Frankfurt',
    languages: ['Deutsch', 'Englisch', 'Italienisch'],
  },
];

export const fleetVehicles: FleetVehicle[] = [
  {
    id: 'VH-001',
    plate: 'M-AB 1234',
    make: 'MAN',
    model: 'TGX 18.500',
    year: 2023,
    type: 'semi_trailer',
    status: 'active',
    maxWeight: 18000,
    maxVolume: 82,
    currentWeight: 2450,
    currentVolume: 12,
    fuelLevel: 72,
    mileage: 84520,
    nextMaintenance: '2025-01-15',
    assignedDriver: 'Hans Müller',
    currentRoute: 'München → Nürnberg → Leipzig → Berlin',
    insuranceExpiry: '2025-06-30',
  },
  {
    id: 'VH-002',
    plate: 'M-CD 5678',
    make: 'Mercedes-Benz',
    model: 'Actros 1845',
    year: 2022,
    type: 'semi_trailer',
    status: 'parked',
    maxWeight: 20000,
    maxVolume: 90,
    currentWeight: 0,
    currentVolume: 0,
    fuelLevel: 95,
    mileage: 112340,
    nextMaintenance: '2025-02-01',
    assignedDriver: 'Klaus Schmidt',
    currentRoute: '',
    insuranceExpiry: '2025-08-15',
  },
  {
    id: 'VH-003',
    plate: 'L-EF 9012',
    make: 'Volkswagen',
    model: 'Crafter',
    year: 2024,
    type: 'van',
    status: 'parked',
    maxWeight: 3500,
    maxVolume: 18,
    currentWeight: 0,
    currentVolume: 0,
    fuelLevel: 88,
    mileage: 34200,
    nextMaintenance: '2025-03-20',
    assignedDriver: '',
    currentRoute: '',
    insuranceExpiry: '2025-12-31',
  },
  {
    id: 'VH-004',
    plate: 'N-GH 3456',
    make: 'Scania',
    model: 'R450',
    year: 2023,
    type: 'semi_trailer',
    status: 'active',
    maxWeight: 19000,
    maxVolume: 85,
    currentWeight: 1250,
    currentVolume: 9,
    fuelLevel: 58,
    mileage: 67890,
    nextMaintenance: '2025-01-28',
    assignedDriver: 'Stefan Weber',
    currentRoute: 'Herzogenaurach → Nürnberg → Regensburg → Wien',
    insuranceExpiry: '2025-05-20',
  },
  {
    id: 'VH-005',
    plate: 'W-IJ 7890',
    make: 'SAP',
    model: 'Express Sprinter',
    year: 2024,
    type: 'box_truck',
    status: 'loading',
    maxWeight: 5000,
    maxVolume: 24,
    currentWeight: 1200,
    currentVolume: 6,
    fuelLevel: 82,
    mileage: 18750,
    nextMaintenance: '2025-04-10',
    assignedDriver: '',
    currentRoute: 'Walldorf → Frankfurt → Amsterdam → Dublin',
    insuranceExpiry: '2026-01-15',
  },
  {
    id: 'VH-006',
    plate: 'W-KL 2345',
    make: 'Volvo',
    model: 'FH16',
    year: 2022,
    type: 'flatbed',
    status: 'parked',
    maxWeight: 22000,
    maxVolume: 65,
    currentWeight: 0,
    currentVolume: 0,
    fuelLevel: 64,
    mileage: 145600,
    nextMaintenance: '2025-01-05',
    assignedDriver: 'Peter Fischer',
    currentRoute: '',
    insuranceExpiry: '2025-04-30',
  },
  {
    id: 'VH-007',
    plate: 'S-MN 6789',
    make: 'DAF',
    model: 'XF 480',
    year: 2023,
    type: 'semi_trailer',
    status: 'maintenance',
    maxWeight: 18500,
    maxVolume: 82,
    currentWeight: 0,
    currentVolume: 0,
    fuelLevel: 40,
    mileage: 98200,
    nextMaintenance: '2024-12-20',
    assignedDriver: '',
    currentRoute: '',
    insuranceExpiry: '2025-09-12',
  },
  {
    id: 'VH-008',
    plate: 'B-OP 0123',
    make: 'Iveco',
    model: 'S-Way',
    year: 2024,
    type: 'box_truck',
    status: 'active',
    maxWeight: 7500,
    maxVolume: 38,
    currentWeight: 430,
    currentVolume: 4.5,
    fuelLevel: 81,
    mileage: 28900,
    nextMaintenance: '2025-05-15',
    assignedDriver: 'Michael Wagner',
    currentRoute: 'Bonn → Köln → Düsseldorf → Dortmund → Berlin',
    insuranceExpiry: '2026-02-28',
  },
  {
    id: 'VH-009',
    plate: 'F-QR 4567',
    make: 'Scania',
    model: 'R500',
    year: 2022,
    type: 'refrigerated',
    status: 'active',
    maxWeight: 16000,
    maxVolume: 72,
    currentWeight: 6800,
    currentVolume: 45,
    fuelLevel: 53,
    mileage: 134500,
    nextMaintenance: '2025-01-20',
    assignedDriver: 'Andreas Becker',
    currentRoute: 'Frankfurt → Leipzig',
    temperature: -18,
    insuranceExpiry: '2025-07-10',
  },
  {
    id: 'VH-010',
    plate: 'D-ST 8901',
    make: 'MAN',
    model: 'TGS 26.480',
    year: 2023,
    type: 'semi_trailer',
    status: 'loading',
    maxWeight: 19000,
    maxVolume: 84,
    currentWeight: 3200,
    currentVolume: 18,
    fuelLevel: 76,
    mileage: 56700,
    nextMaintenance: '2025-02-28',
    assignedDriver: '',
    currentRoute: 'Düsseldorf → Köln → Frankfurt → Stuttgart → Balingen',
    insuranceExpiry: '2025-10-22',
  },
  {
    id: 'VH-011',
    plate: 'M-UV 2345',
    make: 'Mercedes-Benz',
    model: 'Sprinter',
    year: 2024,
    type: 'van',
    status: 'active',
    maxWeight: 3500,
    maxVolume: 17,
    currentWeight: 150,
    currentVolume: 0.2,
    fuelLevel: 69,
    mileage: 22100,
    nextMaintenance: '2025-06-05',
    assignedDriver: 'Rolf Hoffmann',
    currentRoute: 'München → Nürnberg → Würzburg → Frankfurt → Hannover',
    insuranceExpiry: '2026-03-18',
  },
  {
    id: 'VH-012',
    plate: 'E-WX 6789',
    make: 'Volvo',
    model: 'FM 460',
    year: 2023,
    type: 'semi_trailer',
    status: 'parked',
    maxWeight: 19500,
    maxVolume: 88,
    currentWeight: 0,
    currentVolume: 0,
    fuelLevel: 91,
    mileage: 73400,
    nextMaintenance: '2025-03-15',
    assignedDriver: 'Wolfgang Schneider',
    currentRoute: '',
    insuranceExpiry: '2025-11-30',
  },
  {
    id: 'VH-013',
    plate: 'H-YZ 0123',
    make: 'Scania',
    model: 'R450',
    year: 2021,
    type: 'refrigerated',
    status: 'unloading',
    maxWeight: 15000,
    maxVolume: 68,
    currentWeight: 5200,
    currentVolume: 35,
    fuelLevel: 45,
    mileage: 178300,
    nextMaintenance: '2025-01-10',
    assignedDriver: '',
    currentRoute: '',
    temperature: 4,
    insuranceExpiry: '2025-06-15',
  },
  {
    id: 'VH-014',
    plate: 'D-ZA 4567',
    make: 'MAN',
    model: 'TGS 26.480',
    year: 2024,
    type: 'box_truck',
    status: 'active',
    maxWeight: 12000,
    maxVolume: 55,
    currentWeight: 2100,
    currentVolume: 16,
    fuelLevel: 67,
    mileage: 41200,
    nextMaintenance: '2025-04-22',
    assignedDriver: 'Lisa Meier',
    currentRoute: 'Düsseldorf → Köln → Frankfurt → Stuttgart → Balingen',
    insuranceExpiry: '2026-01-10',
  },
];

export const capacityMatches: CapacityMatch[] = [
  {
    id: 'CM-001',
    vehicleId: 'VH-001',
    vehiclePlate: 'M-AB 1234',
    vehicleRoute: 'München → Nürnberg → Leipzig → Berlin',
    availableWeight: 15550,
    availableVolume: 70,
    shipmentId: 'SHP-003',
    shipmentTracking: 'CB-DE-2024-001247',
    shipmentWeight: 890,
    shipmentVolume: 1.0,
    pickupCity: 'Ludwigshafen',
    deliveryCity: 'Monheim',
    matchScore: 94,
    priority: 'standard',
    etaOverlap: true,
  },
  {
    id: 'CM-002',
    vehicleId: 'VH-001',
    vehiclePlate: 'M-AB 1234',
    vehicleRoute: 'München → Nürnberg → Leipzig → Berlin',
    availableWeight: 15550,
    availableVolume: 70,
    shipmentId: 'SHP-011',
    shipmentTracking: 'CB-DE-2024-001255',
    shipmentWeight: 150,
    shipmentVolume: 0.2,
    pickupCity: 'München',
    deliveryCity: 'Hannover',
    matchScore: 87,
    priority: 'express',
    etaOverlap: true,
  },
  {
    id: 'CM-003',
    vehicleId: 'VH-004',
    vehiclePlate: 'N-GH 3456',
    vehicleRoute: 'Herzogenaurach → Nürnberg → Regensburg → Wien',
    availableWeight: 17750,
    availableVolume: 76,
    shipmentId: 'SHP-003',
    shipmentTracking: 'CB-DE-2024-001247',
    shipmentWeight: 890,
    shipmentVolume: 1.0,
    pickupCity: 'Ludwigshafen',
    deliveryCity: 'Monheim',
    matchScore: 62,
    priority: 'standard',
    etaOverlap: false,
  },
  {
    id: 'CM-004',
    vehicleId: 'VH-008',
    vehiclePlate: 'B-OP 0123',
    vehicleRoute: 'Bonn → Köln → Düsseldorf → Dortmund → Berlin',
    availableWeight: 7070,
    availableVolume: 33.5,
    shipmentId: 'SHP-003',
    shipmentTracking: 'CB-DE-2024-001247',
    shipmentWeight: 890,
    shipmentVolume: 1.0,
    pickupCity: 'Ludwigshafen',
    deliveryCity: 'Monheim',
    matchScore: 78,
    priority: 'standard',
    etaOverlap: true,
  },
  {
    id: 'CM-005',
    vehicleId: 'VH-011',
    vehiclePlate: 'M-UV 2345',
    vehicleRoute: 'München → Nürnberg → Würzburg → Frankfurt → Hannover',
    availableWeight: 3350,
    availableVolume: 16.8,
    shipmentId: 'SHP-005',
    shipmentTracking: 'CB-DE-2024-001249',
    shipmentWeight: 320,
    shipmentVolume: 0.06,
    pickupCity: 'Walldorf',
    deliveryCity: 'Dublin',
    matchScore: 45,
    priority: 'express',
    etaOverlap: false,
  },
  {
    id: 'CM-006',
    vehicleId: 'VH-012',
    vehiclePlate: 'E-WX 6789',
    vehicleRoute: '',
    availableWeight: 19500,
    availableVolume: 88,
    shipmentId: 'SHP-003',
    shipmentTracking: 'CB-DE-2024-001247',
    shipmentWeight: 890,
    shipmentVolume: 1.0,
    pickupCity: 'Ludwigshafen',
    deliveryCity: 'Monheim',
    matchScore: 72,
    priority: 'standard',
    etaOverlap: true,
  },
  {
    id: 'CM-007',
    vehicleId: 'VH-014',
    vehiclePlate: 'D-ZA 4567',
    vehicleRoute: 'Düsseldorf → Köln → Frankfurt → Stuttgart → Balingen',
    availableWeight: 9900,
    availableVolume: 39,
    shipmentId: 'SHP-003',
    shipmentTracking: 'CB-DE-2024-001247',
    shipmentWeight: 890,
    shipmentVolume: 1.0,
    pickupCity: 'Ludwigshafen',
    deliveryCity: 'Monheim',
    matchScore: 88,
    priority: 'standard',
    etaOverlap: true,
  },
  {
    id: 'CM-008',
    vehicleId: 'VH-014',
    vehiclePlate: 'D-ZA 4567',
    vehicleRoute: 'Düsseldorf → Köln → Frankfurt → Stuttgart → Balingen',
    availableWeight: 9900,
    availableVolume: 39,
    shipmentId: 'SHP-010',
    shipmentTracking: 'CB-DE-2024-001254',
    shipmentWeight: 2100,
    shipmentVolume: 16,
    pickupCity: 'Düsseldorf',
    deliveryCity: 'Balingen',
    matchScore: 96,
    priority: 'standard',
    etaOverlap: true,
  },
  {
    id: 'CM-009',
    vehicleId: 'VH-002',
    vehiclePlate: 'M-CD 5678',
    vehicleRoute: '',
    availableWeight: 20000,
    availableVolume: 90,
    shipmentId: 'SHP-005',
    shipmentTracking: 'CB-DE-2024-001249',
    shipmentWeight: 320,
    shipmentVolume: 0.06,
    pickupCity: 'Walldorf',
    deliveryCity: 'Dublin',
    matchScore: 81,
    priority: 'express',
    etaOverlap: true,
  },
  {
    id: 'CM-010',
    vehicleId: 'VH-004',
    vehiclePlate: 'N-GH 3456',
    vehicleRoute: 'Herzogenaurach → Nürnberg → Regensburg → Wien',
    availableWeight: 17750,
    availableVolume: 76,
    shipmentId: 'SHP-005',
    shipmentTracking: 'CB-DE-2024-001249',
    shipmentWeight: 320,
    shipmentVolume: 0.06,
    pickupCity: 'Walldorf',
    deliveryCity: 'Dublin',
    matchScore: 38,
    priority: 'express',
    etaOverlap: false,
  },
];

export const routeOptimizations: RouteOptimization[] = [
  {
    vehicleId: 'VH-001',
    vehiclePlate: 'M-AB 1234',
    driverName: 'Hans Müller',
    currentRoute: 'München → Nürnberg → Leipzig → Berlin',
    totalDistance: 585,
    estimatedTime: '6h 45min',
    utilizationPercent: 14,
    suggestedStops: [
      { city: 'Nürnberg', availableCapacityWeight: 15550, availableCapacityVolume: 70, matchingShipments: 3, detourMinutes: 0 },
      { city: 'Leipzig', availableCapacityWeight: 14660, availableCapacityVolume: 69, matchingShipments: 2, detourMinutes: 15 },
    ],
  },
  {
    vehicleId: 'VH-004',
    vehiclePlate: 'N-GH 3456',
    driverName: 'Stefan Weber',
    currentRoute: 'Herzogenaurach → Nürnberg → Regensburg → Wien',
    totalDistance: 420,
    estimatedTime: '4h 30min',
    utilizationPercent: 7,
    suggestedStops: [
      { city: 'Nürnberg', availableCapacityWeight: 17750, availableCapacityVolume: 76, matchingShipments: 1, detourMinutes: 0 },
      { city: 'Regensburg', availableCapacityWeight: 17750, availableCapacityVolume: 76, matchingShipments: 0, detourMinutes: 0 },
    ],
  },
  {
    vehicleId: 'VH-008',
    vehiclePlate: 'B-OP 0123',
    driverName: 'Michael Wagner',
    currentRoute: 'Bonn → Köln → Düsseldorf → Dortmund → Berlin',
    totalDistance: 560,
    estimatedTime: '6h 20min',
    utilizationPercent: 6,
    suggestedStops: [
      { city: 'Köln', availableCapacityWeight: 7070, availableCapacityVolume: 33.5, matchingShipments: 2, detourMinutes: 0 },
      { city: 'Düsseldorf', availableCapacityWeight: 6180, availableCapacityVolume: 32.5, matchingShipments: 1, detourMinutes: 10 },
      { city: 'Dortmund', availableCapacityWeight: 6180, availableCapacityVolume: 32.5, matchingShipments: 3, detourMinutes: 5 },
    ],
  },
  {
    vehicleId: 'VH-011',
    vehiclePlate: 'M-UV 2345',
    driverName: 'Rolf Hoffmann',
    currentRoute: 'München → Nürnberg → Würzburg → Frankfurt → Hannover',
    totalDistance: 490,
    estimatedTime: '5h 15min',
    utilizationPercent: 4,
    suggestedStops: [
      { city: 'Nürnberg', availableCapacityWeight: 3350, availableCapacityVolume: 16.8, matchingShipments: 1, detourMinutes: 0 },
      { city: 'Frankfurt', availableCapacityWeight: 3200, availableCapacityVolume: 16.6, matchingShipments: 2, detourMinutes: 20 },
    ],
  },
  {
    vehicleId: 'VH-014',
    vehiclePlate: 'D-ZA 4567',
    driverName: 'Lisa Meier',
    currentRoute: 'Düsseldorf → Köln → Frankfurt → Stuttgart → Balingen',
    totalDistance: 430,
    estimatedTime: '5h 00min',
    utilizationPercent: 18,
    suggestedStops: [
      { city: 'Köln', availableCapacityWeight: 9900, availableCapacityVolume: 39, matchingShipments: 1, detourMinutes: 0 },
      { city: 'Frankfurt', availableCapacityWeight: 7800, availableCapacityVolume: 23, matchingShipments: 3, detourMinutes: 5 },
      { city: 'Stuttgart', availableCapacityWeight: 5700, availableCapacityVolume: 7, matchingShipments: 1, detourMinutes: 15 },
    ],
  },
];
