apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pricing-service.fullname" . }}
  labels:
    {{- include "pricing-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pricing-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3002"
        prometheus.io/path: "/metrics"
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "pricing-service.selectorLabels" . | nindent 8 }}
        version: v1
    spec:
      serviceAccountName: {{ include "pricing-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3002
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.env.NODE_ENV | quote }}
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            - name: SECURITY_CONFIG_URL
              value: {{ .Values.env.SECURITY_CONFIG_URL | quote }}
            - name: KAFKA_BROKERS
              value: {{ .Values.env.KAFKA_BROKERS | quote }}
            {{- if .Values.database.enabled }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: {{ .Values.database.secretKeys.url }}
            {{- end }}
            {{- if .Values.securityConfigClient.serviceToken.existingSecret }}
            - name: SERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.securityConfigClient.serviceToken.existingSecret }}
                  key: {{ .Values.securityConfigClient.serviceToken.key }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
