{{- if .Values.cron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "payments.name" . }}-scheduler
  labels:
    app: {{ include "payments.name" . }}-scheduler
spec:
  schedule: "{{ .Values.cron.schedule }}"
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ include "payments.name" . }}-scheduler
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          containers:
            - name: scheduler
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["node", "dist/src/cron/payout-scheduler.js"]
              envFrom:
                - secretRef:
                    name: {{ .Values.env.existingSecret }}
              env:
                - name: NODE_ENV
                  value: "production"
              resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "500m"
                  memory: "512Mi"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
          restartPolicy: OnFailure
{{- end }}
