{{- if .Values.cron.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "payments-service.fullname" . }}-scheduler
  labels:
    {{- include "payments-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "payments-service.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: scheduler
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "payments-service.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          restartPolicy: OnFailure
          containers:
            - name: scheduler
              securityContext:
                {{- toYaml .Values.containerSecurityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: {{ .Values.cron.command | toJson }}
              env:
                {{- range $key, $value := .Values.env.regular }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
              envFrom:
                - secretRef:
                    name: {{ .Values.env.existingSecret }}
              resources:
                {{- toYaml .Values.cron.resources | nindent 16 }}
{{- end }}
