{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payments.name" . }}-worker
  labels:
    app: {{ include "payments.name" . }}-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ include "payments.name" . }}-worker
  template:
    metadata:
      labels:
        app: {{ include "payments.name" . }}-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: worker
          image: "{{ .Values.workerImage.repository }}:{{ .Values.workerImage.tag }}"
          imagePullPolicy: {{ .Values.workerImage.pullPolicy }}
          command: {{ toJson .Values.worker.command }}
          envFrom:
            - secretRef:
                name: {{ .Values.env.existingSecret }}
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: {{ .Values.resources.worker.requests.cpu }}
              memory: {{ .Values.resources.worker.requests.memory }}
            limits:
              cpu: {{ .Values.resources.worker.limits.cpu }}
              memory: {{ .Values.resources.worker.limits.memory }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
{{- end }}
