/**
 * Pipeline Assembler
 * Generated by SRE Agent v1.0.0
 * 
 * Assembles all generated files into a release package
 * with versioning and release notes.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Configuration
const config = {
  outputDir: path.join(__dirname, '../multi-agent/output'),
  distDir: path.join(__dirname, '../dist'),
  packageName: 'cargobit-foundation',
  version: require('../multi-agent/config.json').version || '1.0.0'
};

/**
 * Create distribution directory
 */
function createDistDir() {
  if (fs.existsSync(config.distDir)) {
    fs.rmSync(config.distDir, { recursive: true });
  }
  fs.mkdirSync(config.distDir, { recursive: true });
  
  console.log(`Created distribution directory: ${config.distDir}`);
}

/**
 * Copy generated files to distribution
 */
function copyGeneratedFiles() {
  console.log('\n📁 Copying generated files...');
  
  const directories = [
    'prisma',
    'migrations',
    'src',
    'ops',
    'docs',
    'tests'
  ];
  
  for (const dir of directories) {
    const srcPath = path.join(config.outputDir, dir);
    const destPath = path.join(config.distDir, dir);
    
    if (fs.existsSync(srcPath)) {
      fs.cpSync(srcPath, destPath, { recursive: true });
      console.log(`  ✅ Copied ${dir}/`);
    } else {
      console.log(`  ⚠️  Skipped ${dir}/ (not found)`);
    }
  }
  
  // Copy manifest
  const manifestSrc = path.join(config.outputDir, 'manifest.json');
  if (fs.existsSync(manifestSrc)) {
    fs.copyFileSync(manifestSrc, path.join(config.distDir, 'manifest.json'));
    console.log('  ✅ Copied manifest.json');
  }
}

/**
 * Generate package.json
 */
function generatePackageJson() {
  console.log('\n📦 Generating package.json...');
  
  const packageJson = {
    name: config.packageName,
    version: config.version,
    description: 'CargoBit Payment System Foundation Code',
    main: 'src/index.js',
    types: 'src/index.d.ts',
    scripts: {
      'build': 'tsc',
      'test': 'vitest run',
      'test:watch': 'vitest',
      'lint': 'eslint src --ext .ts',
      'db:migrate': 'prisma migrate deploy',
      'db:generate': 'prisma generate',
      'backup': 'bash ops/backup-db.sh',
      'restore': 'bash ops/restore-db.sh',
      'audit:verify': 'ts-node src/jobs/auditVerify.ts',
      'audit:export': 'ts-node ops/export-audit-log.ts'
    },
    dependencies: {
      '@prisma/client': '^5.0.0',
      'ioredis': '^5.3.0',
      'stripe': '^14.0.0',
      'next': '^14.0.0'
    },
    devDependencies: {
      '@types/node': '^20.0.0',
      'prisma': '^5.0.0',
      'typescript': '^5.0.0',
      'vitest': '^1.0.0',
      '@typescript-eslint/parser': '^6.0.0',
      '@typescript-eslint/eslint-plugin': '^6.0.0',
      'eslint': '^8.0.0',
      'ts-node': '^10.9.0'
    },
    engines: {
      node: '>=18.0.0'
    },
    keywords: [
      'payment',
      'stripe',
      'postgresql',
      'redis',
      'audit-log',
      'rate-limiting'
    ],
    license: 'UNLICENSED',
    private: true
  };
  
  fs.writeFileSync(
    path.join(config.distDir, 'package.json'),
    JSON.stringify(packageJson, null, 2)
  );
  
  console.log('  ✅ Generated package.json');
}

/**
 * Generate tsconfig.json
 */
function generateTsConfig() {
  console.log('\n📘 Generating tsconfig.json...');
  
  const tsConfig = {
    compilerOptions: {
      target: 'ES2022',
      module: 'commonjs',
      lib: ['ES2022'],
      outDir: './dist',
      rootDir: './src',
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      declaration: true,
      declarationMap: true,
      sourceMap: true,
      moduleResolution: 'node',
      baseUrl: '.',
      paths: {
        '@/*': ['./src/*']
      }
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist', 'tests']
  };
  
  fs.writeFileSync(
    path.join(config.distDir, 'tsconfig.json'),
    JSON.stringify(tsConfig, null, 2)
  );
  
  console.log('  ✅ Generated tsconfig.json');
}

/**
 * Generate README.md
 */
function generateReadme() {
  console.log('\n📄 Generating README.md...');
  
  const readme = `# CargoBit Payment System Foundation

Version: ${config.version}
Generated: ${new Date().toISOString()}

## Overview

This package contains the foundation code for the CargoBit payment processing system, generated by the Multi-Agent Code Generation System.

## Structure

\`\`\`
├── prisma/           # Database schema
├── migrations/       # SQL migrations
├── src/
│   ├── lib/          # Core libraries
│   ├── middleware/   # Express/Next.js middleware
│   ├── webhooks/     # Stripe webhook handlers
│   ├── services/     # Business logic services
│   └── jobs/         # Scheduled jobs
├── ops/              # Operational scripts
├── tests/            # Test files
└── docs/             # Documentation
\`\`\`

## Quick Start

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Configure environment:
   \`\`\`bash
   cp .env.example .env
   # Edit .env with your configuration
   \`\`\`

3. Run migrations:
   \`\`\`bash
   npx prisma migrate deploy
   \`\`\`

4. Start the server:
   \`\`\`bash
   npm run dev
   \`\`\`

## Features

- **Rate Limiting**: Redis-based distributed rate limiting
- **Stripe Integration**: Webhook handling and payment processing
- **Audit Logging**: Comprehensive audit trail for compliance
- **Backup/Restore**: Automated backup with PITR support
- **Documentation**: Complete operational documentation

## License

UNLICENSED - Internal use only

---

Generated by CargoBit Multi-Agent System v${config.version}
`;
  
  fs.writeFileSync(path.join(config.distDir, 'README.md'), readme);
  console.log('  ✅ Generated README.md');
}

/**
 * Generate release notes
 */
function generateReleaseNotes() {
  console.log('\n📝 Generating release notes...');
  
  // Read manifest for file list
  let fileList = [];
  const manifestPath = path.join(config.outputDir, 'manifest.json');
  if (fs.existsSync(manifestPath)) {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
    fileList = manifest.files || [];
  }
  
  const releaseNotes = `# CargoBit Foundation v${config.version}

Release Date: ${new Date().toISOString()}

## Changes

This release contains the complete foundation code for the CargoBit payment system.

### Generated Components

- **Architecture**: Prisma schema and SQL migrations
- **Backend Services**: Rate limiting, Stripe webhooks, audit logging
- **Operations**: Backup scripts, restore procedures, cron configuration
- **Tests**: Unit and integration tests
- **Documentation**: Security policies, SLAs, runbooks

### Files Included

Total files: ${fileList.length}

<details>
<summary>File List</summary>

\`\`\`
${fileList.join('\n')}
\`\`\`

</details>

### Database Schema

- Users
- Payments
- Audit Logs
- Webhook Events
- Rate Limit Counters
- Backup Metadata

### Services

- Rate Limiting Service (Redis-backed)
- Stripe Webhook Handler
- Audit Log Service
- Audit Verification Job

### Documentation

- Security Policy
- Compliance Readiness Assessment
- Service Level Agreements
- Incident Playbook: Payment Outage
- On-Call Runbook
- Operational Readiness Checklist

## Installation

\`\`\`bash
npm install cargobit-foundation-${config.version}.tar.gz
\`\`\`

## Requirements

- Node.js >= 18
- PostgreSQL 14+
- Redis 6+

---

*Generated by CargoBit Multi-Agent System*
`;
  
  fs.writeFileSync(path.join(config.distDir, 'RELEASE_NOTES.md'), releaseNotes);
  console.log('  ✅ Generated RELEASE_NOTES.md');
}

/**
 * Create tarball
 */
function createTarball() {
  console.log('\n📦 Creating release tarball...');
  
  const tarballName = `${config.packageName}-${config.version}.tar.gz`;
  const tarballPath = path.join(config.distDir, '..', tarballName);
  
  try {
    execSync(`tar -czf ${tarballPath} .`, {
      cwd: config.distDir,
      stdio: 'inherit'
    });
    
    const stats = fs.statSync(tarballPath);
    const sizeMB = (stats.size / (1024 * 1024)).toFixed(2);
    
    console.log(`  ✅ Created ${tarballName} (${sizeMB} MB)`);
    return tarballPath;
  } catch (error) {
    console.log(`  ❌ Failed to create tarball: ${error.message}`);
    return null;
  }
}

/**
 * Generate manifest for release
 */
function generateReleaseManifest() {
  console.log('\n📋 Generating release manifest...');
  
  const manifest = {
    name: config.packageName,
    version: config.version,
    releaseDate: new Date().toISOString(),
    components: {
      architecture: ['prisma/schema.prisma', 'migrations/'],
      backend: ['src/lib/', 'src/middleware/', 'src/webhooks/', 'src/services/', 'src/jobs/'],
      operations: ['ops/'],
      tests: ['tests/'],
      documentation: ['docs/']
    },
    statistics: {
      totalFiles: countFiles(config.distDir),
      totalSize: getDirectorySize(config.distDir)
    }
  };
  
  fs.writeFileSync(
    path.join(config.distDir, 'release-manifest.json'),
    JSON.stringify(manifest, null, 2)
  );
  
  console.log('  ✅ Generated release-manifest.json');
  
  return manifest;
}

/**
 * Count files in directory
 */
function countFiles(dir) {
  let count = 0;
  
  function walk(currentDir) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.isDirectory()) {
        walk(path.join(currentDir, entry.name));
      } else {
        count++;
      }
    }
  }
  
  walk(dir);
  return count;
}

/**
 * Get directory size
 */
function getDirectorySize(dir) {
  let size = 0;
  
  function walk(currentDir) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else {
        size += fs.statSync(fullPath).size;
      }
    }
  }
  
  walk(dir);
  return size;
}

/**
 * Main assembly function
 */
function assemble() {
  console.log('========================================');
  console.log('CargoBit Assembly Pipeline');
  console.log('========================================');
  console.log(`Version: ${config.version}`);
  console.log(`Started at: ${new Date().toISOString()}`);
  
  // Run assembly steps
  createDistDir();
  copyGeneratedFiles();
  generatePackageJson();
  generateTsConfig();
  generateReadme();
  generateReleaseNotes();
  const tarballPath = createTarball();
  const manifest = generateReleaseManifest();
  
  // Print summary
  console.log('\n========================================');
  console.log('ASSEMBLY COMPLETE');
  console.log('========================================');
  console.log(`Distribution: ${config.distDir}`);
  console.log(`Files: ${manifest.statistics.totalFiles}`);
  console.log(`Size: ${(manifest.statistics.totalSize / 1024).toFixed(2)} KB`);
  if (tarballPath) {
    console.log(`Tarball: ${tarballPath}`);
  }
  console.log('========================================');
  
  return manifest;
}

/**
 * CLI entry point
 */
function main() {
  const args = process.argv.slice(2);
  
  if (args.includes('--manifest')) {
    // Output manifest only
    const manifest = generateReleaseManifest();
    console.log(JSON.stringify(manifest, null, 2));
  } else {
    assemble();
  }
}

// CLI execution
if (require.main === module) {
  main();
}

module.exports = { assemble };
