/**
 * Pipeline Publisher
 * Generated by SRE Agent v1.0.0
 * 
 * Publishes the assembled release package to various destinations:
 * - Git repository (commit and tag)
 * - S3 bucket for artifact storage
 * - npm registry (optional)
 * - GitHub Releases
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Configuration
const config = {
  distDir: path.join(__dirname, '../dist'),
  packageName: 'cargobit-foundation',
  version: require('../multi-agent/config.json').version || '1.0.0',
  
  // S3 configuration (optional)
  s3Bucket: process.env.S3_BUCKET || 'cargobit-releases',
  s3Region: process.env.AWS_REGION || 'eu-west-1',
  
  // Git configuration
  gitBranch: process.env.GIT_BRANCH || 'main',
  
  // npm configuration (optional)
  npmRegistry: process.env.NPM_REGISTRY || 'https://registry.npmjs.org'
};

/**
 * Check prerequisites
 */
function checkPrerequisites() {
  console.log('\n🔍 Checking prerequisites...');
  
  const checks = [];
  
  // Check dist directory exists
  if (fs.existsSync(config.distDir)) {
    checks.push({ name: 'Distribution directory', passed: true });
  } else {
    checks.push({ name: 'Distribution directory', passed: false, message: 'Run assemble.js first' });
  }
  
  // Check release manifest
  const manifestPath = path.join(config.distDir, 'release-manifest.json');
  if (fs.existsSync(manifestPath)) {
    checks.push({ name: 'Release manifest', passed: true });
  } else {
    checks.push({ name: 'Release manifest', passed: false, message: 'Missing release-manifest.json' });
  }
  
  // Check tarball
  const tarballPath = path.join(__dirname, '..', `${config.packageName}-${config.version}.tar.gz`);
  if (fs.existsSync(tarballPath)) {
    checks.push({ name: 'Release tarball', passed: true });
  } else {
    checks.push({ name: 'Release tarball', passed: false, message: 'Missing tarball' });
  }
  
  // Print results
  for (const check of checks) {
    if (check.passed) {
      console.log(`  ✅ ${check.name}`);
    } else {
      console.log(`  ❌ ${check.name}: ${check.message}`);
    }
  }
  
  const allPassed = checks.every(c => c.passed);
  
  if (!allPassed) {
    console.log('\n❌ Prerequisites not met. Please fix the issues above.');
    return false;
  }
  
  return true;
}

/**
 * Publish to Git repository
 */
function publishToGit() {
  console.log('\n📦 Publishing to Git repository...');
  
  try {
    // Configure git
    execSync('git config user.name "github-actions[bot]"', { stdio: 'inherit' });
    execSync('git config user.email "github-actions[bot]@users.noreply.github.com"', { stdio: 'inherit' });
    
    // Add files
    execSync('git add .', { stdio: 'inherit' });
    
    // Check if there are changes
    const status = execSync('git status --porcelain').toString().trim();
    
    if (status) {
      // Commit changes
      execSync(`git commit -m "chore: release v${config.version}"`, { stdio: 'inherit' });
      console.log('  ✅ Committed changes');
      
      // Create tag
      execSync(`git tag -a v${config.version} -m "Release v${config.version}"`, { stdio: 'inherit' });
      console.log(`  ✅ Created tag v${config.version}`);
      
      // Push
      execSync(`git push origin ${config.gitBranch}`, { stdio: 'inherit' });
      execSync(`git push origin v${config.version}`, { stdio: 'inherit' });
      console.log('  ✅ Pushed to remote');
    } else {
      console.log('  ℹ️  No changes to commit');
    }
    
    return true;
  } catch (error) {
    console.log(`  ❌ Git publish failed: ${error.message}`);
    return false;
  }
}

/**
 * Publish to S3
 */
function publishToS3() {
  console.log('\n☁️  Publishing to S3...');
  
  if (!process.env.AWS_ACCESS_KEY_ID || !process.env.AWS_SECRET_ACCESS_KEY) {
    console.log('  ⚠️  AWS credentials not configured, skipping S3 publish');
    return true;
  }
  
  try {
    const tarballPath = path.join(__dirname, '..', `${config.packageName}-${config.version}.tar.gz`);
    const s3Key = `releases/${config.packageName}/v${config.version}/${config.packageName}-${config.version}.tar.gz`;
    
    // Upload tarball
    execSync(`aws s3 cp ${tarballPath} s3://${config.s3Bucket}/${s3Key} --region ${config.s3Region}`, {
      stdio: 'inherit'
    });
    
    console.log(`  ✅ Uploaded to s3://${config.s3Bucket}/${s3Key}`);
    
    // Upload release notes
    const releaseNotesPath = path.join(config.distDir, 'RELEASE_NOTES.md');
    if (fs.existsSync(releaseNotesPath)) {
      execSync(`aws s3 cp ${releaseNotesPath} s3://${config.s3Bucket}/releases/${config.packageName}/v${config.version}/RELEASE_NOTES.md --region ${config.s3Region}`, {
        stdio: 'inherit'
      });
      console.log('  ✅ Uploaded release notes');
    }
    
    return true;
  } catch (error) {
    console.log(`  ❌ S3 publish failed: ${error.message}`);
    return false;
  }
}

/**
 * Publish to npm (optional)
 */
function publishToNpm() {
  console.log('\n📦 Publishing to npm...');
  
  if (!process.env.NPM_TOKEN) {
    console.log('  ⚠️  NPM_TOKEN not configured, skipping npm publish');
    return true;
  }
  
  try {
    // Create .npmrc
    fs.writeFileSync(
      path.join(config.distDir, '.npmrc'),
      `//registry.npmjs.org/:_authToken=${process.env.NPM_TOKEN}\n`
    );
    
    // Publish
    execSync(`npm publish --registry ${config.npmRegistry}`, {
      cwd: config.distDir,
      stdio: 'inherit'
    });
    
    console.log(`  ✅ Published to npm as ${config.packageName}@${config.version}`);
    return true;
  } catch (error) {
    console.log(`  ❌ npm publish failed: ${error.message}`);
    return false;
  }
}

/**
 * Create GitHub Release
 */
function createGitHubRelease() {
  console.log('\n🚀 Creating GitHub Release...');
  
  if (!process.env.GITHUB_TOKEN) {
    console.log('  ⚠️  GITHUB_TOKEN not configured, skipping GitHub release');
    return true;
  }
  
  try {
    const releaseNotesPath = path.join(config.distDir, 'RELEASE_NOTES.md');
    const tarballPath = path.join(__dirname, '..', `${config.packageName}-${config.version}.tar.gz`);
    
    // Use gh CLI to create release
    const releaseCommand = [
      'gh release create',
      `v${config.version}`,
      `--title "CargoBit Foundation v${config.version}"`,
      fs.existsSync(releaseNotesPath) ? `--notes-file ${releaseNotesPath}` : '--generate-notes',
      fs.existsSync(tarballPath) ? tarballPath : ''
    ].join(' ');
    
    execSync(releaseCommand, { stdio: 'inherit' });
    
    console.log(`  ✅ Created GitHub release v${config.version}`);
    return true;
  } catch (error) {
    // Check if release already exists
    if (error.message.includes('already exists')) {
      console.log(`  ℹ️  Release v${config.version} already exists`);
      return true;
    }
    console.log(`  ❌ GitHub release failed: ${error.message}`);
    return false;
  }
}

/**
 * Send notification
 */
function sendNotification(success) {
  console.log('\n📧 Sending notification...');
  
  if (!process.env.SLACK_WEBHOOK_URL) {
    console.log('  ℹ️  Slack webhook not configured, skipping notification');
    return;
  }
  
  const status = success ? '✅ Success' : '❌ Failed';
  const color = success ? 'good' : 'danger';
  
  const payload = {
    text: `CargoBit Foundation Release v${config.version}`,
    attachments: [{
      color,
      fields: [
        { title: 'Version', value: config.version, short: true },
        { title: 'Status', value: status, short: true },
        { title: 'Timestamp', value: new Date().toISOString(), short: false }
      ]
    }]
  };
  
  try {
    execSync(`curl -X POST -H 'Content-type: application/json' --data '${JSON.stringify(payload)}' ${process.env.SLACK_WEBHOOK_URL}`, {
      stdio: 'inherit'
    });
    console.log('  ✅ Notification sent');
  } catch (error) {
    console.log(`  ⚠️  Failed to send notification: ${error.message}`);
  }
}

/**
 * Print summary
 */
function printSummary(results) {
  console.log('\n========================================');
  console.log('PUBLISH SUMMARY');
  console.log('========================================');
  console.log(`Package:    ${config.packageName}`);
  console.log(`Version:    ${config.version}`);
  console.log(`Git:        ${results.git ? '✅' : '❌'}`);
  console.log(`S3:         ${results.s3 ? '✅' : '❌'}`);
  console.log(`npm:        ${results.npm ? '✅' : '⏭️'}`);
  console.log(`GitHub:     ${results.github ? '✅' : '❌'}`);
  console.log('========================================');
}

/**
 * Main publish function
 */
function publish() {
  console.log('========================================');
  console.log('CargoBit Publish Pipeline');
  console.log('========================================');
  console.log(`Version: ${config.version}`);
  console.log(`Started at: ${new Date().toISOString()}`);
  
  // Check prerequisites
  if (!checkPrerequisites()) {
    process.exit(1);
  }
  
  // Run publish steps
  const results = {
    git: publishToGit(),
    s3: publishToS3(),
    npm: publishToNpm(),
    github: createGitHubRelease()
  };
  
  // Print summary
  printSummary(results);
  
  // Send notification
  const allSuccess = Object.values(results).every(r => r);
  sendNotification(allSuccess);
  
  // Exit
  if (allSuccess) {
    console.log('\n✅ Publish completed successfully!');
    process.exit(0);
  } else {
    console.log('\n❌ Publish completed with errors');
    process.exit(1);
  }
}

/**
 * CLI entry point
 */
function main() {
  const args = process.argv.slice(2);
  
  if (args.includes('--dry-run')) {
    console.log('Dry run mode - checking prerequisites only');
    checkPrerequisites();
    process.exit(0);
  }
  
  if (args.includes('--git-only')) {
    console.log('Git-only mode');
    if (checkPrerequisites()) {
      publishToGit();
    }
    process.exit(0);
  }
  
  if (args.includes('--s3-only')) {
    console.log('S3-only mode');
    if (checkPrerequisites()) {
      publishToS3();
    }
    process.exit(0);
  }
  
  publish();
}

// CLI execution
if (require.main === module) {
  main();
}

module.exports = { publish };
