/**
 * Pipeline Runner
 * Generated by SRE Agent v1.0.0
 * 
 * Main entry point for running the code generation pipeline.
 * Executes the multi-agent system and captures output.
 */

const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');

// Configuration
const config = {
  orchestratorPath: path.join(__dirname, '../multi-agent/orchestrator.js'),
  outputDir: path.join(__dirname, '../multi-agent/output'),
  logFile: path.join(__dirname, '../generation.log'),
  timeout: 30 * 60 * 1000 // 30 minutes
};

/**
 * Run the multi-agent orchestrator
 */
async function runGeneration() {
  console.log('========================================');
  console.log('CargoBit Code Generation Pipeline');
  console.log('========================================');
  console.log(`Started at: ${new Date().toISOString()}`);
  console.log('');

  // Ensure output directory exists
  if (!fs.existsSync(config.outputDir)) {
    fs.mkdirSync(config.outputDir, { recursive: true });
  }

  return new Promise((resolve, reject) => {
    const startTime = Date.now();
    let stdout = '';
    let stderr = '';

    // Run orchestrator
    const proc = spawn('node', [config.orchestratorPath], {
      cwd: path.join(__dirname, '..'),
      env: { ...process.env, NODE_ENV: 'production' },
      stdio: ['ignore', 'pipe', 'pipe']
    });

    proc.stdout.on('data', (data) => {
      const output = data.toString();
      stdout += output;
      process.stdout.write(output);
    });

    proc.stderr.on('data', (data) => {
      const output = data.toString();
      stderr += output;
      process.stderr.write(output);
    });

    // Set timeout
    const timeout = setTimeout(() => {
      proc.kill('SIGTERM');
      reject(new Error('Generation timed out'));
    }, config.timeout);

    proc.on('close', (code) => {
      clearTimeout(timeout);
      const duration = Date.now() - startTime;

      // Write log file
      const logContent = `
# CargoBit Generation Log
# Started: ${new Date(startTime).toISOString()}
# Completed: ${new Date().toISOString()}
# Duration: ${duration}ms
# Exit Code: ${code}

## STDOUT
${stdout}

## STDERR
${stderr}
`;
      fs.writeFileSync(config.logFile, logContent);

      console.log('');
      console.log('========================================');
      console.log(`Completed in ${duration}ms`);
      console.log(`Exit code: ${code}`);
      console.log('========================================');

      if (code === 0) {
        resolve({
          success: true,
          duration,
          outputDir: config.outputDir,
          logFile: config.logFile
        });
      } else {
        reject(new Error(`Generation failed with exit code ${code}`));
      }
    });

    proc.on('error', (err) => {
      clearTimeout(timeout);
      reject(err);
    });
  });
}

/**
 * Main entry point
 */
async function main() {
  try {
    const result = await runGeneration();
    
    // Print summary
    console.log('\nGeneration completed successfully!');
    console.log(`Output directory: ${result.outputDir}`);
    console.log(`Log file: ${result.logFile}`);
    
    process.exit(0);
  } catch (error) {
    console.error('\nGeneration failed:', error.message);
    process.exit(1);
  }
}

// CLI execution
if (require.main === module) {
  main();
}

module.exports = { runGeneration };
