/**
 * Pipeline Validator
 * Generated by SRE Agent v1.0.0
 * 
 * Validates the generated code for correctness, completeness,
 * and adherence to project standards.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Configuration
const config = {
  outputDir: path.join(__dirname, '../multi-agent/output'),
  requiredFiles: [
    'prisma/schema.prisma',
    'migrations/0001_init.sql',
    'migrations/0002_indexes.sql',
    'src/lib/rateLimit.ts',
    'src/middleware/rateLimit.ts',
    'src/webhooks/stripe.ts',
    'src/services/stripeEvents.ts',
    'src/services/auditLog.ts',
    'src/jobs/auditVerify.ts',
    'ops/backup-db.sh',
    'ops/restore-db.sh',
    'ops/cron-backup.yaml',
    'ops/export-audit-log.ts',
    'tests/rateLimit.test.ts',
    'tests/stripeWebhook.test.ts',
    'docs/security-policy.md',
    'docs/compliance-readiness.md',
    'docs/slas.md',
    'docs/incident-playbook-payment-outage.md',
    'docs/on-call-runbook.md',
    'docs/operational-readiness-checklist.md',
    'manifest.json'
  ]
};

// Results tracking
const results = {
  passed: [],
  failed: [],
  warnings: []
};

/**
 * Log result
 */
function logResult(check, passed, message) {
  const icon = passed ? '✅' : '❌';
  console.log(`  ${icon} ${check}: ${message}`);
  
  if (passed) {
    results.passed.push(check);
  } else {
    results.failed.push(check);
  }
}

/**
 * Log warning
 */
function logWarning(check, message) {
  console.log(`  ⚠️  ${check}: ${message}`);
  results.warnings.push({ check, message });
}

/**
 * Validate file structure
 */
function validateStructure() {
  console.log('\n📁 Validating file structure...');
  
  let allExist = true;
  
  for (const file of config.requiredFiles) {
    const filePath = path.join(config.outputDir, file);
    if (fs.existsSync(filePath)) {
      const stats = fs.statSync(filePath);
      console.log(`  ✅ ${file} (${stats.size} bytes)`);
    } else {
      console.log(`  ❌ ${file} - NOT FOUND`);
      allExist = false;
    }
  }
  
  logResult('File Structure', allExist, 
    `${config.requiredFiles.length} required files ${allExist ? 'present' : 'missing'}`);
  
  return allExist;
}

/**
 * Validate TypeScript files
 */
function validateTypeScript() {
  console.log('\n📘 Validating TypeScript files...');
  
  const tsFiles = findFiles(config.outputDir, '.ts');
  let validCount = 0;
  
  for (const file of tsFiles) {
    const content = fs.readFileSync(file, 'utf-8');
    const relativePath = path.relative(config.outputDir, file);
    
    // Check for basic TypeScript syntax
    const hasImports = content.includes('import ');
    const hasExports = content.includes('export ');
    
    // Check for common issues
    const issues = [];
    
    if (content.includes('any') && !content.includes('// @ts-ignore')) {
      issues.push('uses any type');
    }
    
    if (content.includes('console.log') && !file.includes('test')) {
      issues.push('contains console.log');
    }
    
    if (issues.length > 0) {
      logWarning(relativePath, issues.join(', '));
    } else {
      validCount++;
      console.log(`  ✅ ${relativePath}`);
    }
  }
  
  const allValid = validCount === tsFiles.length;
  logResult('TypeScript', allValid, `${validCount}/${tsFiles.length} files valid`);
  
  return allValid;
}

/**
 * Validate SQL migrations
 */
function validateSQL() {
  console.log('\n🗄️  Validating SQL migrations...');
  
  const sqlFiles = findFiles(config.outputDir, '.sql');
  let validCount = 0;
  
  for (const file of sqlFiles) {
    const content = fs.readFileSync(file, 'utf-8');
    const relativePath = path.relative(config.outputDir, file);
    
    // Check for required SQL elements
    const hasCreate = content.toUpperCase().includes('CREATE');
    const hasValidSyntax = !content.includes('SYNTAX ERROR');
    
    // Check for dangerous operations
    const issues = [];
    if (content.toUpperCase().includes('DROP DATABASE')) {
      issues.push('contains DROP DATABASE');
    }
    if (content.toUpperCase().includes('TRUNCATE')) {
      issues.push('contains TRUNCATE');
    }
    
    if (issues.length > 0) {
      logWarning(relativePath, issues.join(', '));
    }
    
    if (hasCreate && hasValidSyntax) {
      validCount++;
      console.log(`  ✅ ${relativePath}`);
    } else {
      console.log(`  ❌ ${relativePath} - Invalid SQL`);
    }
  }
  
  const allValid = validCount === sqlFiles.length;
  logResult('SQL Migrations', allValid, `${validCount}/${sqlFiles.length} files valid`);
  
  return allValid;
}

/**
 * Validate documentation
 */
function validateDocumentation() {
  console.log('\n📄 Validating documentation...');
  
  const mdFiles = findFiles(config.outputDir, '.md');
  let validCount = 0;
  
  for (const file of mdFiles) {
    const content = fs.readFileSync(file, 'utf-8');
    const relativePath = path.relative(config.outputDir, file);
    
    // Check for required documentation elements
    const hasTitle = content.startsWith('#');
    const hasContent = content.length > 500; // Minimum content length
    
    // Check documentation quality
    const issues = [];
    const lines = content.split('\n');
    const emptyLines = lines.filter(line => line.trim() === '').length;
    const emptyRatio = emptyLines / lines.length;
    
    if (emptyRatio > 0.5) {
      issues.push('too much empty space');
    }
    
    if (!hasTitle) {
      issues.push('missing title');
    }
    
    if (issues.length > 0) {
      logWarning(relativePath, issues.join(', '));
    }
    
    if (hasTitle && hasContent) {
      validCount++;
      console.log(`  ✅ ${relativePath} (${content.length} chars)`);
    } else {
      console.log(`  ❌ ${relativePath} - Invalid documentation`);
    }
  }
  
  const allValid = validCount === mdFiles.length;
  logResult('Documentation', allValid, `${validCount}/${mdFiles.length} files valid`);
  
  return allValid;
}

/**
 * Validate manifest.json
 */
function validateManifest() {
  console.log('\n📋 Validating manifest.json...');
  
  const manifestPath = path.join(config.outputDir, 'manifest.json');
  
  if (!fs.existsSync(manifestPath)) {
    logResult('Manifest', false, 'manifest.json not found');
    return false;
  }
  
  try {
    const content = fs.readFileSync(manifestPath, 'utf-8');
    const manifest = JSON.parse(content);
    
    // Check required fields
    const requiredFields = ['generated_at', 'system', 'version', 'files'];
    const missingFields = requiredFields.filter(field => !manifest[field]);
    
    if (missingFields.length > 0) {
      logResult('Manifest', false, `Missing fields: ${missingFields.join(', ')}`);
      return false;
    }
    
    // Check files array
    if (!Array.isArray(manifest.files) || manifest.files.length === 0) {
      logResult('Manifest', false, 'Files array is empty or invalid');
      return false;
    }
    
    console.log(`  ✅ System: ${manifest.system}`);
    console.log(`  ✅ Version: ${manifest.version}`);
    console.log(`  ✅ Generated: ${manifest.generated_at}`);
    console.log(`  ✅ Files: ${manifest.files.length}`);
    
    logResult('Manifest', true, 'Valid manifest.json');
    return true;
    
  } catch (error) {
    logResult('Manifest', false, `Invalid JSON: ${error.message}`);
    return false;
  }
}

/**
 * Validate shell scripts
 */
function validateShellScripts() {
  console.log('\n🔧 Validating shell scripts...');
  
  const shFiles = findFiles(config.outputDir, '.sh');
  let validCount = 0;
  
  for (const file of shFiles) {
    const content = fs.readFileSync(file, 'utf-8');
    const relativePath = path.relative(config.outputDir, file);
    
    // Check for required shell script elements
    const hasShebang = content.startsWith('#!/bin/bash') || content.startsWith('#!/usr/bin/env bash');
    const hasSetOptions = content.includes('set -');
    
    // Check for issues
    const issues = [];
    if (!hasShebang) {
      issues.push('missing shebang');
    }
    
    if (issues.length > 0) {
      logWarning(relativePath, issues.join(', '));
    }
    
    if (hasShebang) {
      validCount++;
      console.log(`  ✅ ${relativePath}`);
    } else {
      console.log(`  ❌ ${relativePath} - Invalid shell script`);
    }
  }
  
  const allValid = validCount === shFiles.length;
  logResult('Shell Scripts', allValid, `${validCount}/${shFiles.length} files valid`);
  
  return allValid;
}

/**
 * Find all files with given extension
 */
function findFiles(dir, ext) {
  const files = [];
  
  function walk(currentDir) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.name.endsWith(ext)) {
        files.push(fullPath);
      }
    }
  }
  
  walk(dir);
  return files;
}

/**
 * Print summary
 */
function printSummary() {
  console.log('\n========================================');
  console.log('VALIDATION SUMMARY');
  console.log('========================================');
  console.log(`Passed:   ${results.passed.length}`);
  console.log(`Failed:   ${results.failed.length}`);
  console.log(`Warnings: ${results.warnings.length}`);
  console.log('========================================');
  
  if (results.failed.length > 0) {
    console.log('\n❌ Failed checks:');
    results.failed.forEach(check => console.log(`   - ${check}`));
  }
  
  if (results.warnings.length > 0) {
    console.log('\n⚠️  Warnings:');
    results.warnings.forEach(w => console.log(`   - ${w.check}: ${w.message}`));
  }
  
  return results.failed.length === 0;
}

/**
 * Main validation function
 */
function validate(options = {}) {
  console.log('========================================');
  console.log('CargoBit Validation Pipeline');
  console.log('========================================');
  console.log(`Output directory: ${config.outputDir}`);
  console.log(`Started at: ${new Date().toISOString()}`);
  
  // Run all validations
  if (!options.structure || options.all) validateStructure();
  if (!options.typescript || options.all) validateTypeScript();
  if (!options.sql || options.all) validateSQL();
  if (!options.documentation || options.all) validateDocumentation();
  if (!options.manifest || options.all) validateManifest();
  if (!options.scripts || options.all) validateShellScripts();
  
  // Print summary
  const success = printSummary();
  
  return success;
}

/**
 * CLI entry point
 */
function main() {
  const args = process.argv.slice(2);
  
  const options = {
    all: args.length === 0,
    structure: args.includes('--structure'),
    typescript: args.includes('--typescript'),
    sql: args.includes('--sql'),
    documentation: args.includes('--documentation'),
    manifest: args.includes('--manifest'),
    scripts: args.includes('--scripts')
  };
  
  const success = validate(options);
  process.exit(success ? 0 : 1);
}

// CLI execution
if (require.main === module) {
  main();
}

module.exports = { validate, validateStructure, validateTypeScript, validateSQL, validateDocumentation };
