/**
 * Architect Agent
 * Version: 1.0.0
 * 
 * Responsibility: Data modeling, Prisma schema generation, SQL migrations,
 * and architecture documentation for the CargoBit payment system.
 * 
 * Outputs:
 * - prisma/schema.prisma
 * - migrations/0001_init.sql
 * - migrations/0002_indexes.sql
 * - docs/architecture-overview.md
 */

module.exports = {
  name: 'architect-agent',
  version: '1.0.0',
  
  /**
   * Main execution method
   * @param {Object} input - Input from orchestrator (empty for architect)
   * @returns {Object} Generated files
   */
  run(input) {
    console.log('  → Generating Prisma schema...');
    console.log('  → Generating SQL migrations...');
    console.log('  → Creating architecture documentation...');
    
    return {
      files: {
        'prisma/schema.prisma': this.generatePrismaSchema(),
        'migrations/0001_init.sql': this.generateInitMigration(),
        'migrations/0002_indexes.sql': this.generateIndexMigration(),
        'docs/architecture-overview.md': this.generateArchitectureDoc()
      },
      metadata: {
        generated_at: new Date().toISOString(),
        tables: ['User', 'Payment', 'AuditLog', 'WebhookEvent', 'RateLimitCounter'],
        indexes: 12
      }
    };
  },

  /**
   * Generate Prisma Schema
   */
  generatePrismaSchema() {
    return `// Prisma Schema for CargoBit Payment System
// Generated by Architect Agent v1.0.0
// Date: ${new Date().toISOString()}

generator client {
  provider = "prisma-client-js"
  previewFeatures = ["fullTextSearch", "fullTextIndex"]
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// =============================================================================
// USER MANAGEMENT
// =============================================================================

model User {
  id            String    @id @default(cuid())
  email         String    @unique
  name          String?
  stripeCustomerId String? @unique
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  
  // Relations
  payments      Payment[]
  auditLogs     AuditLog[]
  
  @@index([email])
  @@index([stripeCustomerId])
  @@map("users")
}

// =============================================================================
// PAYMENT PROCESSING
// =============================================================================

model Payment {
  id              String        @id @default(cuid())
  userId          String
  amount          Decimal       @db.Decimal(10, 2)
  currency        String        @default("EUR")
  status          PaymentStatus @default(PENDING)
  stripePaymentIntentId String? @unique
  stripeChargeId  String?       @unique
  description     String?
  metadata        Json?
  createdAt       DateTime      @default(now())
  updatedAt       DateTime      @updatedAt
  processedAt     DateTime?
  
  // Relations
  user            User          @relation(fields: [userId], references: [id], onDelete: Cascade)
  auditLogs       AuditLog[]
  
  @@index([userId])
  @@index([status])
  @@index([createdAt])
  @@index([stripePaymentIntentId])
  @@index([stripeChargeId])
  @@map("payments")
}

enum PaymentStatus {
  PENDING
  PROCESSING
  SUCCEEDED
  FAILED
  REFUNDED
  CANCELLED
}

// =============================================================================
// AUDIT LOGGING (COMPLIANCE)
// =============================================================================

model AuditLog {
  id            String      @id @default(cuid())
  userId        String?
  action        String
  entityType    String
  entityId      String?
  oldValues     Json?
  newValues     Json?
  ipAddress     String?
  userAgent     String?
  requestId     String?
  createdAt     DateTime    @default(now())
  
  // Relations
  user          User?       @relation(fields: [userId], references: [id], onDelete: SetNull)
  payment       Payment?    @relation(fields: [paymentId], references: [id])
  paymentId     String?
  
  @@index([userId])
  @@index([action])
  @@index([entityType, entityId])
  @@index([createdAt])
  @@index([requestId])
  @@map("audit_logs")
}

// =============================================================================
// WEBHOOK EVENT TRACKING
// =============================================================================

model WebhookEvent {
  id              String          @id @default(cuid())
  stripeEventId   String          @unique
  eventType       String
  processed       Boolean         @default(false)
  processingError String?
  payload         Json
  signature       String
  receivedAt      DateTime        @default(now())
  processedAt     DateTime?
  retryCount      Int             @default(0)
  
  @@index([stripeEventId])
  @@index([eventType])
  @@index([processed])
  @@index([receivedAt])
  @@map("webhook_events")
}

// =============================================================================
// RATE LIMITING
// =============================================================================

model RateLimitCounter {
  id          String    @id @default(cuid())
  key         String    @unique
  count       Int       @default(0)
  windowStart DateTime  @default(now())
  expiresAt   DateTime
  
  @@index([key])
  @@index([expiresAt])
  @@map("rate_limit_counters")
}

// =============================================================================
// BACKUP METADATA
// =============================================================================

model BackupMetadata {
  id            String    @id @default(cuid())
  backupType    String    // full, incremental, pitr
  status        String    // pending, running, completed, failed
  sizeBytes     BigInt?
  storagePath   String?
  startedAt     DateTime  @default(now())
  completedAt   DateTime?
  checksum      String?
  errorMessage  String?
  
  @@index([backupType])
  @@index([status])
  @@index([startedAt])
  @@map("backup_metadata")
}
`;
  },

  /**
   * Generate Initial Migration SQL
   */
  generateInitMigration() {
    return `-- Migration: 0001_init
-- Description: Initial schema for CargoBit Payment System
-- Generated by Architect Agent v1.0.0
-- Date: ${new Date().toISOString()}

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- ENUMS
-- =============================================================================

CREATE TYPE "PaymentStatus" AS ENUM (
    'PENDING',
    'PROCESSING',
    'SUCCEEDED',
    'FAILED',
    'REFUNDED',
    'CANCELLED'
);

-- =============================================================================
-- USERS TABLE
-- =============================================================================

CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "stripeCustomerId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX "users_stripeCustomerId_key" ON "users"("stripeCustomerId");

-- =============================================================================
-- PAYMENTS TABLE
-- =============================================================================

CREATE TABLE "payments" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "amount" DECIMAL(10,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'EUR',
    "status" "PaymentStatus" NOT NULL DEFAULT 'PENDING',
    "stripePaymentIntentId" TEXT,
    "stripeChargeId" TEXT,
    "description" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "processedAt" TIMESTAMP(3),

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "payments_stripePaymentIntentId_key" ON "payments"("stripePaymentIntentId");
CREATE UNIQUE INDEX "payments_stripeChargeId_key" ON "payments"("stripeChargeId");

-- Add foreign key constraint
ALTER TABLE "payments" ADD CONSTRAINT "payments_userId_fkey" 
    FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- =============================================================================
-- AUDIT LOGS TABLE
-- =============================================================================

CREATE TABLE "audit_logs" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT,
    "oldValues" JSONB,
    "newValues" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "requestId" TEXT,
    "paymentId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

-- Add foreign key constraints
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_userId_fkey" 
    FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_paymentId_fkey" 
    FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- =============================================================================
-- WEBHOOK EVENTS TABLE
-- =============================================================================

CREATE TABLE "webhook_events" (
    "id" TEXT NOT NULL,
    "stripeEventId" TEXT NOT NULL,
    "eventType" TEXT NOT NULL,
    "processed" BOOLEAN NOT NULL DEFAULT false,
    "processingError" TEXT,
    "payload" JSONB NOT NULL,
    "signature" TEXT NOT NULL,
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processedAt" TIMESTAMP(3),
    "retryCount" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "webhook_events_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "webhook_events_stripeEventId_key" ON "webhook_events"("stripeEventId");

-- =============================================================================
-- RATE LIMIT COUNTERS TABLE
-- =============================================================================

CREATE TABLE "rate_limit_counters" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "count" INTEGER NOT NULL DEFAULT 0,
    "windowStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "rate_limit_counters_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "rate_limit_counters_key_key" ON "rate_limit_counters"("key");

-- =============================================================================
-- BACKUP METADATA TABLE
-- =============================================================================

CREATE TABLE "backup_metadata" (
    "id" TEXT NOT NULL,
    "backupType" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "sizeBytes" BIGINT,
    "storagePath" TEXT,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" TIMESTAMP(3),
    "checksum" TEXT,
    "errorMessage" TEXT,

    CONSTRAINT "backup_metadata_pkey" PRIMARY KEY ("id")
);

-- =============================================================================
-- INITIAL DATA
-- =============================================================================

-- Insert default admin user (for development only)
-- INSERT INTO "users" ("id", "email", "name")
-- VALUES (gen_random_uuid(), 'admin@cargobit.local', 'System Admin');
`;
  },

  /**
   * Generate Index Migration SQL
   */
  generateIndexMigration() {
    return `-- Migration: 0002_indexes
-- Description: Performance indexes for CargoBit Payment System
-- Generated by Architect Agent v1.0.0
-- Date: ${new Date().toISOString()}

-- =============================================================================
-- USER INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS "users_email_idx" ON "users"("email");
CREATE INDEX IF NOT EXISTS "users_stripeCustomerId_idx" ON "users"("stripeCustomerId");

-- =============================================================================
-- PAYMENT INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS "payments_userId_idx" ON "payments"("userId");
CREATE INDEX IF NOT EXISTS "payments_status_idx" ON "payments"("status");
CREATE INDEX IF NOT EXISTS "payments_createdAt_idx" ON "payments"("createdAt");
CREATE INDEX IF NOT EXISTS "payments_stripePaymentIntentId_idx" ON "payments"("stripePaymentIntentId");
CREATE INDEX IF NOT EXISTS "payments_stripeChargeId_idx" ON "payments"("stripeChargeId");

-- Composite index for common query pattern
CREATE INDEX IF NOT EXISTS "payments_userId_status_idx" ON "payments"("userId", "status");

-- =============================================================================
-- AUDIT LOG INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS "audit_logs_userId_idx" ON "audit_logs"("userId");
CREATE INDEX IF NOT EXISTS "audit_logs_action_idx" ON "audit_logs"("action");
CREATE INDEX IF NOT EXISTS "audit_logs_entityType_entityId_idx" ON "audit_logs"("entityType", "entityId");
CREATE INDEX IF NOT EXISTS "audit_logs_createdAt_idx" ON "audit_logs"("createdAt");
CREATE INDEX IF NOT EXISTS "audit_logs_requestId_idx" ON "audit_logs"("requestId");

-- Composite index for compliance queries
CREATE INDEX IF NOT EXISTS "audit_logs_action_createdAt_idx" ON "audit_logs"("action", "createdAt");

-- =============================================================================
-- WEBHOOK EVENT INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS "webhook_events_stripeEventId_idx" ON "webhook_events"("stripeEventId");
CREATE INDEX IF NOT EXISTS "webhook_events_eventType_idx" ON "webhook_events"("eventType");
CREATE INDEX IF NOT EXISTS "webhook_events_processed_idx" ON "webhook_events"("processed");
CREATE INDEX IF NOT EXISTS "webhook_events_receivedAt_idx" ON "webhook_events"("receivedAt");

-- Composite index for processing queue
CREATE INDEX IF NOT EXISTS "webhook_events_processed_receivedAt_idx" 
    ON "webhook_events"("processed", "receivedAt");

-- =============================================================================
-- RATE LIMIT INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS "rate_limit_counters_key_idx" ON "rate_limit_counters"("key");
CREATE INDEX IF NOT EXISTS "rate_limit_counters_expiresAt_idx" ON "rate_limit_counters"("expiresAt");

-- =============================================================================
-- BACKUP METADATA INDEXES
-- =============================================================================

CREATE INDEX IF NOT EXISTS "backup_metadata_backupType_idx" ON "backup_metadata"("backupType");
CREATE INDEX IF NOT EXISTS "backup_metadata_status_idx" ON "backup_metadata"("status");
CREATE INDEX IF NOT EXISTS "backup_metadata_startedAt_idx" ON "backup_metadata"("startedAt");

-- =============================================================================
-- PARTIAL INDEXES FOR PERFORMANCE
-- =============================================================================

-- Index only unprocessed webhook events
CREATE INDEX IF NOT EXISTS "webhook_events_unprocessed_idx" 
    ON "webhook_events"("receivedAt") 
    WHERE "processed" = false;

-- Index only active rate limit counters
CREATE INDEX IF NOT EXISTS "rate_limit_counters_active_idx" 
    ON "rate_limit_counters"("key", "count") 
    WHERE "expiresAt" > CURRENT_TIMESTAMP;

-- =============================================================================
-- ANALYZE TABLES
-- =============================================================================

ANALYZE "users";
ANALYZE "payments";
ANALYZE "audit_logs";
ANALYZE "webhook_events";
ANALYZE "rate_limit_counters";
ANALYZE "backup_metadata";
`;
  },

  /**
   * Generate Architecture Documentation
   */
  generateArchitectureDoc() {
    return `# CargoBit Payment System - Architecture Overview

Generated by Architect Agent v1.0.0  
Date: ${new Date().toISOString()}

---

## 1. System Overview

CargoBit is a production-ready payment processing system designed for reliability, compliance, and scalability. The system integrates with Stripe for payment processing and implements comprehensive audit logging, rate limiting, and operational tooling.

### 1.1 Core Principles

- **Security First**: All sensitive operations are logged and verified
- **Compliance Ready**: Built-in audit trails and GDPR-compliant data handling
- **High Availability**: Designed for 99.9% uptime SLA
- **Observable**: Comprehensive logging and monitoring integration points

---

## 2. Architecture Diagram

\`\`\`
┌─────────────────────────────────────────────────────────────────┐
│                        CLIENT LAYER                              │
├─────────────────────────────────────────────────────────────────┤
│  Web App  │  Mobile App  │  API Consumers  │  Admin Dashboard   │
└─────┬─────┴──────┬───────┴────────┬────────┴────────┬───────────┘
      │            │                │                 │
      ▼            ▼                ▼                 ▼
┌─────────────────────────────────────────────────────────────────┐
│                     API GATEWAY / LOAD BALANCER                  │
│                    (Rate Limiting Middleware)                    │
└─────────────────────────────┬───────────────────────────────────┘
                              │
                              ▼
┌─────────────────────────────────────────────────────────────────┐
│                     APPLICATION LAYER                            │
├─────────────────┬─────────────────┬─────────────────────────────┤
│  Payment API    │  Webhook API    │  Admin API                  │
│  /api/payments  │  /webhooks/*    │  /api/admin/*               │
└────────┬────────┴────────┬────────┴─────────────────────────────┘
         │                 │
         ▼                 ▼
┌─────────────────────────────────────────────────────────────────┐
│                     SERVICE LAYER                                │
├─────────────────┬─────────────────┬─────────────────────────────┤
│  PaymentService │  StripeService  │  AuditLogService            │
│  UserService    │  WebhookHandler │  RateLimitService           │
└────────┬────────┴────────┬────────┴─────────────────────────────┘
         │                 │
         ▼                 ▼
┌─────────────────────────────────────────────────────────────────┐
│                     DATA LAYER                                   │
├─────────────────────────┬───────────────────────────────────────┤
│      PostgreSQL         │              Redis                      │
│   (Primary Database)    │     (Cache + Rate Limiting)             │
│   - Users               │     - Rate limit counters               │
│   - Payments            │     - Session cache                     │
│   - Audit Logs          │     - Webhook idempotency               │
│   - Webhook Events      │                                         │
└─────────────────────────┴───────────────────────────────────────┘
                              │
                              ▼
┌─────────────────────────────────────────────────────────────────┐
│                   EXTERNAL SERVICES                              │
├─────────────────────────────────────────────────────────────────┤
│  Stripe API  │  S3/Storage  │  Monitoring (Prometheus/Grafana)  │
└─────────────────────────────────────────────────────────────────┘
\`\`\`

---

## 3. Database Schema

### 3.1 Entity Relationship Diagram

\`\`\`
┌───────────────┐       ┌───────────────┐
│     User      │       │    Payment    │
├───────────────┤       ├───────────────┤
│ id            │───┐   │ id            │
│ email         │   │   │ userId (FK)   │───┐
│ name          │   └──▶│ amount        │   │
│ stripeCustomer│       │ currency      │   │
│ createdAt     │       │ status        │   │
│ updatedAt     │       │ stripePI      │   │
└───────────────┘       │ createdAt     │   │
                        └───────────────┘   │
                                            │
┌───────────────┐                           │
│   AuditLog    │                           │
├───────────────┤                           │
│ id            │                           │
│ userId (FK)   │───────────────────────────┘
│ action        │
│ entityType    │       ┌───────────────┐
│ entityId      │       │ WebhookEvent  │
│ oldValues     │       ├───────────────┤
│ newValues     │       │ id            │
│ ipAddress     │       │ stripeEventId │
│ createdAt     │       │ eventType     │
└───────────────┘       │ processed     │
                        │ payload       │
┌───────────────┐       │ receivedAt    │
│RateLimitCntr  │       └───────────────┘
├───────────────┤
│ id            │       ┌───────────────┐
│ key           │       │BackupMetadata │
│ count         │       ├───────────────┤
│ windowStart   │       │ id            │
│ expiresAt     │       │ backupType    │
└───────────────┘       │ status        │
                        │ sizeBytes     │
                        │ startedAt     │
                        └───────────────┘
\`\`\`

### 3.2 Table Descriptions

| Table | Purpose | Key Constraints |
|-------|---------|-----------------|
| users | User accounts and Stripe customer mapping | Email unique, Stripe customer ID unique |
| payments | Payment transactions | Cascade delete with user |
| audit_logs | Immutable audit trail for compliance | Retention policy: 7 years |
| webhook_events | Stripe webhook event processing | Idempotency key on stripeEventId |
| rate_limit_counters | Request rate limiting counters | TTL-based expiration |
| backup_metadata | Backup operation tracking | For PITR and restore operations |

---

## 4. Security Architecture

### 4.1 Authentication & Authorization

- **Authentication**: JWT-based with refresh tokens
- **Authorization**: Role-based access control (RBAC)
- **API Keys**: Scoped API keys for service-to-service auth

### 4.2 Data Protection

- **Encryption at Rest**: AES-256 for sensitive fields
- **Encryption in Transit**: TLS 1.3 mandatory
- **PII Handling**: Anonymization for audit logs

### 4.3 Stripe Integration Security

- Webhook signature verification using HMAC-SHA256
- Idempotency keys for all mutating operations
- No storage of full card numbers (tokenized)

---

## 5. Rate Limiting Strategy

### 5.1 Limits

| Endpoint Category | Rate Limit | Window |
|-------------------|------------|--------|
| Public API | 100 requests | 1 minute |
| Authenticated API | 1000 requests | 1 minute |
| Webhook Processing | 500 events | 1 minute |
| Admin API | 5000 requests | 1 minute |

### 5.2 Implementation

- Redis-based sliding window counter
- Graceful degradation with retry-after headers
- Per-user and per-IP limiting

---

## 6. Audit Logging

### 6.1 Logged Events

- All payment state transitions
- User authentication events
- Administrative actions
- Webhook processing
- Data export operations

### 6.2 Log Structure

Each audit log entry contains:
- Actor identification (user ID, IP, user agent)
- Action type and target entity
- Before/after state (JSON)
- Request correlation ID
- Timestamp (immutable)

---

## 7. Backup & Recovery

### 7.1 Backup Schedule

| Type | Frequency | Retention |
|------|-----------|-----------|
| Full Backup | Daily | 30 days |
| Incremental | Hourly | 7 days |
| WAL Archive | Continuous | 7 days |

### 7.2 Recovery Objectives

- **RTO (Recovery Time Objective)**: 1 hour
- **RPO (Recovery Point Objective)**: 5 minutes (with PITR)

---

## 8. Monitoring & Alerting

### 8.1 Key Metrics

- Payment success rate
- Webhook processing latency
- API response time (p50, p95, p99)
- Database connection pool usage
- Rate limit rejection rate

### 8.2 Alert Conditions

- Payment failure rate > 1%
- Webhook queue backlog > 100
- API latency p95 > 500ms
- Database connections > 80%

---

## 9. Deployment Architecture

### 9.1 Environments

| Environment | Purpose | Data |
|-------------|---------|------|
| Development | Feature development | Synthetic data |
| Staging | Integration testing | Anonymized production subset |
| Production | Live traffic | Real customer data |

### 9.2 CI/CD Pipeline

1. Code commit triggers build
2. Unit and integration tests run
3. Security scanning (SAST/DAST)
4. Deployment to staging
5. Automated acceptance tests
6. Manual approval for production
7. Blue-green deployment

---

## 10. Compliance Considerations

### 10.1 GDPR Compliance

- Right to access: User data export endpoint
- Right to erasure: Cascading delete with audit trail
- Data portability: Standard export formats
- Consent management: Opt-in tracking

### 10.2 PCI DSS Compliance

- No card data storage (Stripe handles PCI)
- SAQ A compliance path
- Annual security assessments

---

## 11. Scaling Considerations

### 11.1 Horizontal Scaling

- Stateless application servers
- Redis cluster for rate limiting
- Read replicas for database

### 11.2 Performance Targets

- 10,000 requests/second peak capacity
- < 100ms API response time (p95)
- 99.9% uptime SLA

---

*Document generated automatically by Architect Agent*
*Last updated: ${new Date().toISOString()}*
`;
  }
};
