/**
 * Backend Agent
 * Version: 1.0.0
 * 
 * Responsibility: Generate backend services, middleware, webhook handlers,
 * rate limiting, and audit logging for the CargoBit payment system.
 * 
 * Inputs:
 * - prisma/schema.prisma (from Architect Agent)
 * 
 * Outputs:
 * - src/lib/rateLimit.ts
 * - src/middleware/rateLimit.ts
 * - src/webhooks/stripe.ts
 * - src/services/stripeEvents.ts
 * - src/services/auditLog.ts
 * - src/jobs/auditVerify.ts
 */

module.exports = {
  name: 'backend-agent',
  version: '1.0.0',
  
  /**
   * Main execution method
   * @param {Object} input - Input from orchestrator containing schema
   * @returns {Object} Generated files
   */
  run(input) {
    console.log('  → Generating rate limiting library...');
    console.log('  → Generating rate limiting middleware...');
    console.log('  → Generating Stripe webhook handler...');
    console.log('  → Generating Stripe event processor...');
    console.log('  → Generating audit log service...');
    console.log('  → Generating audit verification job...');
    
    return {
      files: {
        'src/lib/rateLimit.ts': this.generateRateLimitLib(),
        'src/middleware/rateLimit.ts': this.generateRateLimitMiddleware(),
        'src/webhooks/stripe.ts': this.generateStripeWebhook(),
        'src/services/stripeEvents.ts': this.generateStripeEvents(),
        'src/services/auditLog.ts': this.generateAuditLogService(),
        'src/jobs/auditVerify.ts': this.generateAuditVerifyJob()
      },
      metadata: {
        generated_at: new Date().toISOString(),
        services: ['RateLimitService', 'StripeWebhookHandler', 'AuditLogService'],
        middleware: ['rateLimitMiddleware']
      }
    };
  },

  /**
   * Generate Rate Limit Library
   */
  generateRateLimitLib() {
    return `/**
 * Rate Limiting Library
 * Generated by Backend Agent v1.0.0
 * 
 * Redis-based sliding window rate limiter with configurable limits
 * and graceful degradation for high-traffic scenarios.
 */

import { Redis } from 'ioredis';

// =============================================================================
// TYPES & INTERFACES
// =============================================================================

export interface RateLimitConfig {
  /** Maximum number of requests allowed in the window */
  limit: number;
  /** Window duration in milliseconds */
  windowMs: number;
  /** Key prefix for Redis storage */
  keyPrefix?: string;
  /** Whether to skip rate limiting for certain conditions */
  skip?: (req: RateLimitRequest) => boolean | Promise<boolean>;
  /** Custom key generator */
  keyGenerator?: (req: RateLimitRequest) => string | Promise<string>;
  /** Handler when limit is exceeded */
  handler?: (req: RateLimitRequest, res: RateLimitResponse) => void | Promise<void>;
}

export interface RateLimitRequest {
  ip?: string;
  headers: Record<string, string | undefined>;
  user?: { id: string; role?: string };
  path?: string;
  method?: string;
}

export interface RateLimitResponse {
  status: (code: number) => RateLimitResponse;
  json: (data: unknown) => void;
  setHeader: (name: string, value: string | number) => void;
}

export interface RateLimitResult {
  allowed: boolean;
  current: number;
  limit: number;
  remaining: number;
  resetTime: number;
  retryAfter?: number;
}

export interface RateLimitStore {
  increment(key: string): Promise<{ current: number; ttl: number }>;
  reset(key: string): Promise<void>;
  decrement(key: string): Promise<void>;
}

// =============================================================================
// REDIS STORE IMPLEMENTATION
// =============================================================================

export class RedisRateLimitStore implements RateLimitStore {
  private redis: Redis;
  private windowMs: number;
  private prefix: string;

  constructor(redis: Redis, windowMs: number, prefix: string = 'ratelimit:') {
    this.redis = redis;
    this.windowMs = windowMs;
    this.prefix = prefix;
  }

  /**
   * Increment counter using sliding window algorithm
   */
  async increment(key: string): Promise<{ current: number; ttl: number }> {
    const fullKey = \`\${this.prefix}\${key}\`;
    const now = Date.now();
    const windowStart = now - this.windowMs;

    // Use Lua script for atomic sliding window operation
    const script = \`
      local key = KEYS[1]
      local now = tonumber(ARGV[1])
      local window_start = tonumber(ARGV[2])
      local window_ms = tonumber(ARGV[3])
      
      -- Remove expired entries
      redis.call('ZREMRANGEBYSCORE', key, 0, window_start)
      
      -- Count current entries
      local current = redis.call('ZCARD', key)
      
      -- Add current request
      redis.call('ZADD', key, now, now .. '-' .. math.random())
      
      -- Set expiry
      redis.call('PEXPIRE', key, window_ms)
      
      return {current + 1, redis.call('PTTL', key)}
    \`;

    const result = await this.redis.eval(
      script,
      1,
      fullKey,
      now.toString(),
      windowStart.toString(),
      this.windowMs.toString()
    ) as [number, number];

    return {
      current: result[0],
      ttl: Math.ceil(result[1] / 1000) // Convert to seconds
    };
  }

  /**
   * Reset counter for a key
   */
  async reset(key: string): Promise<void> {
    await this.redis.del(\`\${this.prefix}\${key}\`);
  }

  /**
   * Decrement counter (used when undoing rate limit)
   */
  async decrement(key: string): Promise<void> {
    const fullKey = \`\${this.prefix}\${key}\`;
    const now = Date.now();
    
    // Remove one entry from the sorted set
    const entries = await this.redis.zrange(fullKey, 0, 0);
    if (entries.length > 0) {
      await this.redis.zrem(fullKey, entries[0]);
    }
  }
}

// =============================================================================
// RATE LIMITER CLASS
// =============================================================================

export class RateLimiter {
  private store: RateLimitStore;
  private config: Required<Omit<RateLimitConfig, 'skip' | 'handler'>> & Pick<RateLimitConfig, 'skip' | 'handler'>;

  constructor(store: RateLimitStore, config: RateLimitConfig) {
    this.store = store;
    this.config = {
      keyPrefix: 'ratelimit:',
      ...config
    };
  }

  /**
   * Check rate limit for a request
   */
  async checkLimit(identifier: string): Promise<RateLimitResult> {
    const { current, ttl } = await this.store.increment(identifier);
    
    const allowed = current <= this.config.limit;
    const remaining = Math.max(0, this.config.limit - current);
    const resetTime = Date.now() + (ttl * 1000);

    return {
      allowed,
      current,
      limit: this.config.limit,
      remaining: allowed ? remaining : 0,
      resetTime,
      retryAfter: allowed ? undefined : ttl
    };
  }

  /**
   * Reset rate limit for an identifier
   */
  async resetLimit(identifier: string): Promise<void> {
    await this.store.reset(identifier);
  }

  /**
   * Process a request through the rate limiter
   */
  async process(req: RateLimitRequest, res: RateLimitResponse): Promise<RateLimitResult> {
    // Check skip condition
    if (this.config.skip && await this.config.skip(req)) {
      return {
        allowed: true,
        current: 0,
        limit: this.config.limit,
        remaining: this.config.limit,
        resetTime: Date.now() + this.config.windowMs
      };
    }

    // Generate key
    const identifier = req.user?.id || req.ip || 'anonymous';
    const key = \`\${identifier}:\${req.path || 'default'}\`;

    const result = await this.checkLimit(key);

    // Set rate limit headers
    res.setHeader('X-RateLimit-Limit', this.config.limit);
    res.setHeader('X-RateLimit-Remaining', result.remaining);
    res.setHeader('X-RateLimit-Reset', Math.ceil(result.resetTime / 1000));

    if (!result.allowed) {
      res.setHeader('Retry-After', result.retryAfter || 60);
      
      if (this.config.handler) {
        await this.config.handler(req, res);
      } else {
        res.status(429).json({
          error: 'Too Many Requests',
          message: 'Rate limit exceeded. Please try again later.',
          retryAfter: result.retryAfter
        });
      }
    }

    return result;
  }
}

// =============================================================================
// PRESET CONFIGURATIONS
// =============================================================================

export const RATE_LIMIT_PRESETS = {
  /** Public API: 100 requests per minute */
  publicApi: {
    limit: 100,
    windowMs: 60 * 1000,
    keyPrefix: 'public:'
  },

  /** Authenticated API: 1000 requests per minute */
  authenticatedApi: {
    limit: 1000,
    windowMs: 60 * 1000,
    keyPrefix: 'auth:'
  },

  /** Webhook processing: 500 events per minute */
  webhooks: {
    limit: 500,
    windowMs: 60 * 1000,
    keyPrefix: 'webhook:'
  },

  /** Admin API: 5000 requests per minute */
  adminApi: {
    limit: 5000,
    windowMs: 60 * 1000,
    keyPrefix: 'admin:'
  },

  /** Payment creation: 10 requests per minute (sensitive) */
  paymentCreate: {
    limit: 10,
    windowMs: 60 * 1000,
    keyPrefix: 'payment:'
  },

  /** Authentication attempts: 5 per minute */
  authAttempts: {
    limit: 5,
    windowMs: 60 * 1000,
    keyPrefix: 'auth_attempt:'
  }
} as const;

// =============================================================================
// FACTORY FUNCTION
// =============================================================================

/**
 * Create a rate limiter instance with Redis store
 */
export function createRateLimiter(
  redis: Redis,
  preset: keyof typeof RATE_LIMIT_PRESETS | RateLimitConfig
): RateLimiter {
  const config = typeof preset === 'string' 
    ? RATE_LIMIT_PRESETS[preset] 
    : preset;
  
  const store = new RedisRateLimitStore(redis, config.windowMs, config.keyPrefix);
  return new RateLimiter(store, config);
}

// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

/**
 * Extract client IP from request (handles proxies)
 */
export function extractClientIp(req: RateLimitRequest): string {
  const forwarded = req.headers['x-forwarded-for'];
  if (forwarded) {
    const ips = forwarded.split(',').map(ip => ip.trim());
    return ips[0] || 'unknown';
  }
  
  return req.headers['x-real-ip'] || req.ip || 'unknown';
}

/**
 * Create composite key for rate limiting
 */
export function createRateLimitKey(
  ...parts: (string | number | undefined)[]
): string {
  return parts
    .filter(Boolean)
    .map(String)
    .join(':')
    .replace(/[^a-zA-Z0-9:_-]/g, '');
}
`;
  },

  /**
   * Generate Rate Limit Middleware
   */
  generateRateLimitMiddleware() {
    return `/**
 * Rate Limiting Middleware
 * Generated by Backend Agent v1.0.0
 * 
 * Express/Next.js middleware for request rate limiting
 * with Redis-backed distributed counters.
 */

import { NextRequest, NextResponse } from 'next/server';
import { 
  createRateLimiter, 
  RATE_LIMIT_PRESETS,
  extractClientIp,
  createRateLimitKey,
  RateLimitConfig
} from '../lib/rateLimit';
import { getRedisClient } from '../lib/redis';

// =============================================================================
// TYPES
// =============================================================================

interface RateLimitMiddlewareOptions extends Partial<RateLimitConfig> {
  /** Preset to use (overrides individual config options) */
  preset?: keyof typeof RATE_LIMIT_PRESETS;
  /** Routes to exclude from rate limiting */
  excludePaths?: string[];
  /** Whether to trust X-Forwarded-For header */
  trustProxy?: boolean;
  /** Callback when rate limit is exceeded */
  onLimitReached?: (req: NextRequest, identifier: string) => void | Promise<void>;
}

// =============================================================================
// MIDDLEWARE FACTORY
// =============================================================================

/**
 * Create rate limiting middleware with configurable options
 */
export function rateLimitMiddleware(options: RateLimitMiddlewareOptions = {}) {
  const {
    preset,
    excludePaths = ['/health', '/metrics', '/favicon.ico'],
    trustProxy = true,
    onLimitReached,
    ...configOverrides
  } = options;

  // Merge preset with overrides
  const config: RateLimitConfig = preset
    ? { ...RATE_LIMIT_PRESETS[preset], ...configOverrides }
    : { limit: 100, windowMs: 60000, ...configOverrides };

  return async function middleware(req: NextRequest): Promise<NextResponse | null> {
    // Skip excluded paths
    const pathname = req.nextUrl.pathname;
    if (excludePaths.some(path => pathname.startsWith(path))) {
      return null; // Continue to next handler
    }

    try {
      const redis = getRedisClient();
      const limiter = createRateLimiter(redis, config);

      // Build request object for rate limiter
      const rateLimitReq = {
        ip: trustProxy ? extractClientIpFromNextRequest(req) : req.ip,
        headers: Object.fromEntries(req.headers.entries()),
        user: getUserFromRequest(req),
        path: pathname,
        method: req.method
      };

      // Build response object
      let responseStatus = 200;
      let responseBody: unknown = null;
      const headers = new Map<string, string | number>();

      const rateLimitRes = {
        status: (code: number) => {
          responseStatus = code;
          return rateLimitRes;
        },
        json: (data: unknown) => {
          responseBody = data;
        },
        setHeader: (name: string, value: string | number) => {
          headers.set(name, value);
        }
      };

      // Check rate limit
      const result = await limiter.process(rateLimitReq, rateLimitRes);

      // Build response with rate limit headers
      if (!result.allowed) {
        // Call onLimitReached callback if provided
        if (onLimitReached) {
          const identifier = rateLimitReq.user?.id || rateLimitReq.ip || 'anonymous';
          await onLimitReached(req, identifier);
        }

        const response = NextResponse.json(
          responseBody || {
            error: 'Too Many Requests',
            message: 'Rate limit exceeded. Please try again later.',
            retryAfter: result.retryAfter
          },
          { status: responseStatus }
        );

        // Set rate limit headers
        headers.forEach((value, key) => {
          response.headers.set(key, String(value));
        });

        return response;
      }

      // Continue to next handler
      const response = NextResponse.next();
      
      // Add rate limit headers to successful responses
      headers.forEach((value, key) => {
        response.headers.set(key, String(value));
      });

      return null; // Continue to next middleware/handler

    } catch (error) {
      console.error('Rate limiting error:', error);
      
      // Fail open - allow request if rate limiting fails
      return null;
    }
  };
}

// =============================================================================
// PRECONFIGURED MIDDLEWARES
// =============================================================================

/**
 * Public API rate limiting (100 req/min)
 */
export const publicApiRateLimit = rateLimitMiddleware({
  preset: 'publicApi',
  onLimitReached: (req, identifier) => {
    console.warn(\`Rate limit exceeded for \${identifier} on \${req.nextUrl.pathname}\`);
  }
});

/**
 * Authenticated API rate limiting (1000 req/min)
 */
export const authenticatedApiRateLimit = rateLimitMiddleware({
  preset: 'authenticatedApi',
  skip: (req) => !req.user, // Only apply to authenticated users
  onLimitReached: (req, identifier) => {
    console.warn(\`Auth API rate limit exceeded for user \${identifier}\`);
  }
});

/**
 * Payment creation rate limiting (10 req/min - sensitive)
 */
export const paymentRateLimit = rateLimitMiddleware({
  preset: 'paymentCreate',
  excludePaths: ['/api/payments/success', '/api/payments/cancel']
});

/**
 * Authentication attempts rate limiting (5 req/min)
 */
export const authRateLimit = rateLimitMiddleware({
  preset: 'authAttempts',
  keyGenerator: (req) => {
    // Rate limit by IP for unauthenticated requests
    return extractClientIpFromNextRequest(req as NextRequest);
  }
});

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

/**
 * Extract client IP from Next.js request
 */
function extractClientIpFromNextRequest(req: NextRequest): string {
  const forwarded = req.headers.get('x-forwarded-for');
  if (forwarded) {
    const ips = forwarded.split(',').map(ip => ip.trim());
    return ips[0] || 'unknown';
  }
  
  return req.headers.get('x-real-ip') || req.ip || 'unknown';
}

/**
 * Get user from request (if authenticated)
 */
function getUserFromRequest(req: NextRequest): { id: string; role?: string } | undefined {
  // This would typically decode a JWT or session token
  const authHeader = req.headers.get('authorization');
  if (!authHeader) return undefined;
  
  // Placeholder - actual implementation would decode JWT
  // and extract user info from the token
  return undefined;
}

// =============================================================================
// ROUTE MATCHER HELPERS
// =============================================================================

/**
 * Check if request matches API routes
 */
export function isApiRoute(req: NextRequest): boolean {
  return req.nextUrl.pathname.startsWith('/api/');
}

/**
 * Check if request matches webhook routes
 */
export function isWebhookRoute(req: NextRequest): boolean {
  return req.nextUrl.pathname.startsWith('/api/webhooks/');
}

/**
 * Check if request matches admin routes
 */
export function isAdminRoute(req: NextRequest): boolean {
  return req.nextUrl.pathname.startsWith('/api/admin/');
}

// =============================================================================
// COMBINED MIDDLEWARE
// =============================================================================

/**
 * Apply appropriate rate limiting based on route type
 */
export async function applyRateLimit(req: NextRequest): Promise<NextResponse | null> {
  const pathname = req.nextUrl.pathname;

  // Webhook rate limiting
  if (pathname.startsWith('/api/webhooks/')) {
    return rateLimitMiddleware({ preset: 'webhooks' })(req);
  }

  // Admin rate limiting
  if (pathname.startsWith('/api/admin/')) {
    return rateLimitMiddleware({ preset: 'adminApi' })(req);
  }

  // Payment rate limiting
  if (pathname.startsWith('/api/payments/')) {
    return paymentRateLimit(req);
  }

  // Default public API rate limiting
  if (pathname.startsWith('/api/')) {
    return publicApiRateLimit(req);
  }

  return null;
}
`;
  },

  /**
   * Generate Stripe Webhook Handler
   */
  generateStripeWebhook() {
    return `/**
 * Stripe Webhook Handler
 * Generated by Backend Agent v1.0.0
 * 
 * Secure webhook endpoint for Stripe events with signature verification,
 * idempotency, and comprehensive error handling.
 */

import { NextRequest, NextResponse } from 'next/server';
import Stripe from 'stripe';
import { buffer } from 'micro';
import { prisma } from '@/lib/prisma';
import { processStripeEvent, isEventProcessed } from '@/services/stripeEvents';
import { logAuditEvent } from '@/services/auditLog';

// =============================================================================
// CONFIGURATION
// =============================================================================

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-11-20.acacia',
  typescript: true,
});

const WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET!;

// Maximum time to process a webhook before returning
const PROCESSING_TIMEOUT_MS = 25000;

// Events we want to handle
const SUPPORTED_EVENTS = [
  'payment_intent.succeeded',
  'payment_intent.payment_failed',
  'payment_intent.canceled',
  'charge.succeeded',
  'charge.failed',
  'charge.refunded',
  'charge.dispute.created',
  'customer.created',
  'customer.updated',
  'customer.deleted',
  'invoice.paid',
  'invoice.payment_failed',
  'checkout.session.completed',
] as const;

type SupportedEventType = typeof SUPPORTED_EVENTS[number];

// =============================================================================
// WEBHOOK VERIFICATION
// =============================================================================

/**
 * Verify Stripe webhook signature
 */
function verifyWebhookSignature(
  payload: string | Buffer,
  signature: string,
  secret: string
): Stripe.Event {
  try {
    return stripe.webhooks.constructEvent(payload, signature, secret);
  } catch (err) {
    const error = err as Error;
    console.error('Webhook signature verification failed:', error.message);
    throw new Error(\`Invalid signature: \${error.message}\`);
  }
}

/**
 * Check if event type is supported
 */
function isSupportedEventType(type: string): type is SupportedEventType {
  return SUPPORTED_EVENTS.includes(type as SupportedEventType);
}

// =============================================================================
// IDEMPOTENCY HANDLING
// =============================================================================

/**
 * Record webhook event for idempotency
 */
async function recordWebhookEvent(
  event: Stripe.Event,
  signature: string
): Promise<{ isNew: boolean; record: any }> {
  const existing = await prisma.webhookEvent.findUnique({
    where: { stripeEventId: event.id }
  });

  if (existing) {
    return { isNew: false, record: existing };
  }

  const record = await prisma.webhookEvent.create({
    data: {
      stripeEventId: event.id,
      eventType: event.type,
      payload: event.data as any,
      signature,
      processed: false,
    }
  });

  return { isNew: true, record };
}

/**
 * Mark webhook as processed
 */
async function markWebhookProcessed(
  eventId: string,
  error?: string
): Promise<void> {
  await prisma.webhookEvent.update({
    where: { id: eventId },
    data: {
      processed: !error,
      processingError: error,
      processedAt: new Date(),
    }
  });
}

// =============================================================================
// MAIN HANDLER
// =============================================================================

export async function POST(req: NextRequest) {
  const startTime = Date.now();
  let eventId: string | undefined;

  try {
    // Get raw body for signature verification
    const rawBody = await req.text();
    const signature = req.headers.get('stripe-signature');

    if (!signature) {
      console.error('Missing Stripe signature header');
      return NextResponse.json(
        { error: 'Missing signature' },
        { status: 400 }
      );
    }

    // Verify webhook signature
    let event: Stripe.Event;
    try {
      event = verifyWebhookSignature(rawBody, signature, WEBHOOK_SECRET);
    } catch (err) {
      return NextResponse.json(
        { error: 'Invalid signature' },
        { status: 400 }
      );
    }

    eventId = event.id;
    console.log(\`Received Stripe webhook: \${event.type} [\${event.id}]\`);

    // Check if event type is supported
    if (!isSupportedEventType(event.type)) {
      console.log(\`Unhandled event type: \${event.type}\`);
      return NextResponse.json(
        { received: true, note: 'Event type not handled' },
        { status: 200 }
      );
    }

    // Check idempotency
    const { isNew, record } = await recordWebhookEvent(event, signature);
    
    if (!isNew) {
      console.log(\`Duplicate event: \${event.id} (already \${record.processed ? 'processed' : 'processing'})\`);
      return NextResponse.json(
        { received: true, note: 'Duplicate event' },
        { status: 200 }
      );
    }

    // Log webhook receipt
    await logAuditEvent({
      action: 'WEBHOOK_RECEIVED',
      entityType: 'WebhookEvent',
      entityId: record.id,
      newValues: { eventType: event.type, stripeEventId: event.id },
      requestId: req.headers.get('x-request-id') || undefined,
      ipAddress: req.headers.get('x-forwarded-for')?.split(',')[0] || undefined,
    });

    // Process event with timeout protection
    const processingPromise = processStripeEvent(event);
    const timeoutPromise = new Promise<never>((_, reject) => {
      setTimeout(() => reject(new Error('Processing timeout')), PROCESSING_TIMEOUT_MS);
    });

    try {
      await Promise.race([processingPromise, timeoutPromise]);
      await markWebhookProcessed(record.id);
    } catch (processingError) {
      const errorMsg = processingError instanceof Error 
        ? processingError.message 
        : 'Unknown processing error';
      
      await markWebhookProcessed(record.id, errorMsg);
      throw processingError;
    }

    // Log successful processing
    const duration = Date.now() - startTime;
    console.log(\`Webhook processed successfully: \${event.id} in \${duration}ms\`);

    return NextResponse.json(
      { received: true, eventId: event.id, duration },
      { status: 200 }
    );

  } catch (error) {
    const duration = Date.now() - startTime;
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    
    console.error(\`Webhook processing failed [\${eventId || 'unknown'}]:\`, errorMessage);

    // Log error for monitoring
    await logAuditEvent({
      action: 'WEBHOOK_ERROR',
      entityType: 'WebhookEvent',
      entityId: eventId || 'unknown',
      newValues: { error: errorMessage, duration },
    });

    // Return 200 to prevent Stripe retries for certain errors
    // Return 500 for retryable errors
    const isRetryable = errorMessage.includes('timeout') || 
                        errorMessage.includes('connection') ||
                        errorMessage.includes('database');

    return NextResponse.json(
      { 
        error: 'Processing failed', 
        eventId,
        retryable: isRetryable 
      },
      { status: isRetryable ? 500 : 200 }
    );
  }
}

// =============================================================================
// CONFIGURATION FOR RAW BODY
// =============================================================================

// Next.js API routes need this configuration to access raw body
export const config = {
  api: {
    bodyParser: false,
    externalResolver: true,
  },
};

// =============================================================================
// HEALTH CHECK
// =============================================================================

export async function GET() {
  // Simple health check for webhook endpoint
  return NextResponse.json({
    status: 'healthy',
    endpoint: '/api/webhooks/stripe',
    supportedEvents: SUPPORTED_EVENTS.length,
  });
}
`;
  },

  /**
   * Generate Stripe Events Service
   */
  generateStripeEvents() {
    return `/**
 * Stripe Event Processing Service
 * Generated by Backend Agent v1.0.0
 * 
 * Handles all Stripe webhook events with proper error handling,
 * idempotency, and audit logging.
 */

import Stripe from 'stripe';
import { prisma } from '@/lib/prisma';
import { logAuditEvent, AuditAction } from '@/services/auditLog';

// =============================================================================
// TYPES
// =============================================================================

interface PaymentUpdateData {
  status?: string;
  stripePaymentIntentId?: string;
  stripeChargeId?: string;
  processedAt?: Date;
  metadata?: Record<string, unknown>;
}

// =============================================================================
// EVENT PROCESSORS
// =============================================================================

/**
 * Process payment_intent.succeeded event
 */
async function handlePaymentIntentSucceeded(
  event: Stripe.PaymentIntentSucceededEvent
): Promise<void> {
  const paymentIntent = event.data.object;
  
  console.log(\`Processing successful payment: \${paymentIntent.id}\`);

  // Find payment by stripe payment intent ID
  const payment = await prisma.payment.findFirst({
    where: { stripePaymentIntentId: paymentIntent.id }
  });

  if (!payment) {
    console.warn(\`Payment not found for PaymentIntent: \${paymentIntent.id}\`);
    // Could be a payment created outside our system
    return;
  }

  // Update payment status
  await prisma.payment.update({
    where: { id: payment.id },
    data: {
      status: 'SUCCEEDED',
      processedAt: new Date(),
      metadata: {
        ...(payment.metadata as object || {}),
        stripeAmount: paymentIntent.amount,
        stripeCurrency: paymentIntent.currency,
        stripeCreated: paymentIntent.created,
      }
    }
  });

  // Log audit event
  await logAuditEvent({
    userId: payment.userId,
    action: 'PAYMENT_SUCCEEDED',
    entityType: 'Payment',
    entityId: payment.id,
    oldValues: { status: payment.status },
    newValues: { status: 'SUCCEEDED', amount: payment.amount.toNumber() },
  });
}

/**
 * Process payment_intent.payment_failed event
 */
async function handlePaymentIntentFailed(
  event: Stripe.PaymentIntentPaymentFailedEvent
): Promise<void> {
  const paymentIntent = event.data.object;
  const lastPaymentError = paymentIntent.last_payment_error;

  console.log(\`Processing failed payment: \${paymentIntent.id}\`);

  const payment = await prisma.payment.findFirst({
    where: { stripePaymentIntentId: paymentIntent.id }
  });

  if (!payment) {
    console.warn(\`Payment not found for PaymentIntent: \${paymentIntent.id}\`);
    return;
  }

  await prisma.payment.update({
    where: { id: payment.id },
    data: {
      status: 'FAILED',
      processedAt: new Date(),
      metadata: {
        ...(payment.metadata as object || {}),
        failureCode: lastPaymentError?.code,
        failureMessage: lastPaymentError?.message,
        failureType: lastPaymentError?.type,
      }
    }
  });

  await logAuditEvent({
    userId: payment.userId,
    action: 'PAYMENT_FAILED',
    entityType: 'Payment',
    entityId: payment.id,
    oldValues: { status: payment.status },
    newValues: { 
      status: 'FAILED', 
      error: lastPaymentError?.message 
    },
  });
}

/**
 * Process charge.succeeded event
 */
async function handleChargeSucceeded(
  event: Stripe.ChargeSucceededEvent
): Promise<void> {
  const charge = event.data.object;
  
  console.log(\`Processing charge: \${charge.id}\`);

  // Find payment by payment intent ID (from charge)
  if (charge.payment_intent) {
    const payment = await prisma.payment.findFirst({
      where: { 
        stripePaymentIntentId: typeof charge.payment_intent === 'string' 
          ? charge.payment_intent 
          : charge.payment_intent.id 
      }
    });

    if (payment && !payment.stripeChargeId) {
      await prisma.payment.update({
        where: { id: payment.id },
        data: { 
          stripeChargeId: charge.id,
          metadata: {
            ...(payment.metadata as object || {}),
            chargeId: charge.id,
            receiptUrl: charge.receipt_url,
          }
        }
      });
    }
  }

  await logAuditEvent({
    action: 'CHARGE_SUCCEEDED',
    entityType: 'Charge',
    entityId: charge.id,
    newValues: {
      amount: charge.amount,
      currency: charge.currency,
      paid: charge.paid,
    }
  });
}

/**
 * Process charge.refunded event
 */
async function handleChargeRefunded(
  event: Stripe.ChargeRefundedEvent
): Promise<void> {
  const charge = event.data.object;
  const refunds = charge.refunds;

  console.log(\`Processing refund for charge: \${charge.id}\`);

  // Find payment by charge ID
  const payment = await prisma.payment.findFirst({
    where: { stripeChargeId: charge.id }
  });

  if (payment) {
    await prisma.payment.update({
      where: { id: payment.id },
      data: {
        status: 'REFUNDED',
        metadata: {
          ...(payment.metadata as object || {}),
          refundAmount: refunds.data.reduce((sum, r) => sum + r.amount, 0),
          refundIds: refunds.data.map(r => r.id),
        }
      }
    });

    await logAuditEvent({
      userId: payment.userId,
      action: 'PAYMENT_REFUNDED',
      entityType: 'Payment',
      entityId: payment.id,
      oldValues: { status: payment.status },
      newValues: { 
        status: 'REFUNDED',
        refundAmount: refunds.data.reduce((sum, r) => sum + r.amount, 0)
      },
    });
  }
}

/**
 * Process charge.dispute.created event
 */
async function handleDisputeCreated(
  event: Stripe.ChargeDisputeCreatedEvent
): Promise<void> {
  const dispute = event.data.object;

  console.warn(\`Dispute created for charge: \${dispute.charge}\`);

  // Find associated payment
  const chargeId = typeof dispute.charge === 'string' 
    ? dispute.charge 
    : dispute.charge.id;
    
  const payment = await prisma.payment.findFirst({
    where: { stripeChargeId: chargeId }
  });

  if (payment) {
    await logAuditEvent({
      userId: payment.userId,
      action: 'PAYMENT_DISPUTED',
      entityType: 'Payment',
      entityId: payment.id,
      newValues: {
        disputeId: dispute.id,
        disputeAmount: dispute.amount,
        disputeReason: dispute.reason,
        disputeStatus: dispute.status,
      }
    });
  }

  // TODO: Send alert to operations team
}

/**
 * Process customer.created event
 */
async function handleCustomerCreated(
  event: Stripe.CustomerCreatedEvent
): Promise<void> {
  const customer = event.data.object;
  
  console.log(\`Processing new customer: \${customer.id}\`);

  // If customer was created with email, find user and link
  if (customer.email) {
    const user = await prisma.user.findUnique({
      where: { email: customer.email }
    });

    if (user && !user.stripeCustomerId) {
      await prisma.user.update({
        where: { id: user.id },
        data: { stripeCustomerId: customer.id }
      });

      await logAuditEvent({
        userId: user.id,
        action: 'CUSTOMER_CREATED',
        entityType: 'User',
        entityId: user.id,
        newValues: { stripeCustomerId: customer.id }
      });
    }
  }
}

/**
 * Process checkout.session.completed event
 */
async function handleCheckoutSessionCompleted(
  event: Stripe.CheckoutSessionCompletedEvent
): Promise<void> {
  const session = event.data.object;
  
  console.log(\`Processing checkout session: \${session.id}\`);

  // Handle checkout completion - this depends on your checkout flow
  // Typically used for subscription signups or one-time payments

  await logAuditEvent({
    action: 'CHECKOUT_COMPLETED',
    entityType: 'CheckoutSession',
    entityId: session.id,
    newValues: {
      paymentStatus: session.payment_status,
      paymentIntent: session.payment_intent,
      customer: session.customer,
    }
  });
}

// =============================================================================
// EVENT ROUTER
// =============================================================================

const EVENT_HANDLERS: Record<string, (event: Stripe.Event) => Promise<void>> = {
  'payment_intent.succeeded': handlePaymentIntentSucceeded,
  'payment_intent.payment_failed': handlePaymentIntentFailed,
  'charge.succeeded': handleChargeSucceeded,
  'charge.refunded': handleChargeRefunded,
  'charge.dispute.created': handleDisputeCreated,
  'customer.created': handleCustomerCreated,
  'checkout.session.completed': handleCheckoutSessionCompleted,
};

/**
 * Process a Stripe event
 */
export async function processStripeEvent(event: Stripe.Event): Promise<void> {
  const handler = EVENT_HANDLERS[event.type];

  if (!handler) {
    console.log(\`No handler for event type: \${event.type}\`);
    return;
  }

  try {
    await handler(event);
    console.log(\`Successfully processed event: \${event.type} [\${event.id}]\`);
  } catch (error) {
    console.error(\`Error processing event \${event.type} [\${event.id}]:\`, error);
    throw error;
  }
}

/**
 * Check if event has already been processed (idempotency check)
 */
export async function isEventProcessed(stripeEventId: string): Promise<boolean> {
  const event = await prisma.webhookEvent.findUnique({
    where: { stripeEventId },
    select: { processed: true }
  });
  
  return event?.processed ?? false;
}

/**
 * Get unprocessed events (for retry processing)
 */
export async function getUnprocessedEvents(limit: number = 100): Promise<any[]> {
  return prisma.webhookEvent.findMany({
    where: {
      processed: false,
      retryCount: { lt: 5 } // Max 5 retries
    },
    orderBy: { receivedAt: 'asc' },
    take: limit
  });
}

/**
 * Retry failed webhook events
 */
export async function retryFailedEvents(): Promise<{ success: number; failed: number }> {
  const events = await getUnprocessedEvents();
  let success = 0;
  let failed = 0;

  for (const eventRecord of events) {
    try {
      const event = eventRecord.payload as Stripe.Event;
      await processStripeEvent(event);
      
      await prisma.webhookEvent.update({
        where: { id: eventRecord.id },
        data: { processed: true, processedAt: new Date() }
      });
      
      success++;
    } catch (error) {
      await prisma.webhookEvent.update({
        where: { id: eventRecord.id },
        data: { 
          retryCount: { increment: 1 },
          processingError: error instanceof Error ? error.message : 'Unknown error'
        }
      });
      
      failed++;
    }
  }

  return { success, failed };
}
`;
  },

  /**
   * Generate Audit Log Service
   */
  generateAuditLogService() {
    return `/**
 * Audit Log Service
 * Generated by Backend Agent v1.0.0
 * 
 * Comprehensive audit logging for compliance, security, and debugging.
 * All operations are immutable and designed for long-term retention.
 */

import { prisma } from '@/lib/prisma';
import { Prisma } from '@prisma/client';

// =============================================================================
// TYPES & INTERFACES
// =============================================================================

export type AuditAction =
  | 'USER_CREATED'
  | 'USER_UPDATED'
  | 'USER_DELETED'
  | 'PAYMENT_CREATED'
  | 'PAYMENT_SUCCEEDED'
  | 'PAYMENT_FAILED'
  | 'PAYMENT_REFUNDED'
  | 'PAYMENT_DISPUTED'
  | 'WEBHOOK_RECEIVED'
  | 'WEBHOOK_ERROR'
  | 'CHARGE_SUCCEEDED'
  | 'CUSTOMER_CREATED'
  | 'CHECKOUT_COMPLETED'
  | 'DATA_EXPORT'
  | 'DATA_DELETE'
  | 'RATE_LIMIT_EXCEEDED'
  | 'AUTH_LOGIN'
  | 'AUTH_LOGOUT'
  | 'AUTH_FAILED'
  | 'ADMIN_ACTION'
  | 'SYSTEM_BACKUP'
  | 'SYSTEM_RESTORE';

export interface AuditLogEntry {
  userId?: string;
  action: AuditAction | string;
  entityType: string;
  entityId?: string;
  oldValues?: Record<string, unknown>;
  newValues?: Record<string, unknown>;
  ipAddress?: string;
  userAgent?: string;
  requestId?: string;
}

export interface AuditLogQuery {
  userId?: string;
  action?: string | string[];
  entityType?: string;
  entityId?: string;
  startDate?: Date;
  endDate?: Date;
  requestId?: string;
  limit?: number;
  offset?: number;
}

export interface AuditLogStats {
  total: number;
  byAction: Record<string, number>;
  byEntityType: Record<string, number>;
}

// =============================================================================
// CORE FUNCTIONS
// =============================================================================

/**
 * Log an audit event
 */
export async function logAuditEvent(entry: AuditLogEntry): Promise<string> {
  const auditLog = await prisma.auditLog.create({
    data: {
      userId: entry.userId,
      action: entry.action,
      entityType: entry.entityType,
      entityId: entry.entityId,
      oldValues: entry.oldValues as Prisma.InputJsonValue || Prisma.JsonNull,
      newValues: entry.newValues as Prisma.InputJsonValue || Prisma.JsonNull,
      ipAddress: entry.ipAddress,
      userAgent: entry.userAgent,
      requestId: entry.requestId,
    }
  });

  return auditLog.id;
}

/**
 * Log multiple audit events in a batch
 */
export async function logAuditBatch(entries: AuditLogEntry[]): Promise<number> {
  const result = await prisma.auditLog.createMany({
    data: entries.map(entry => ({
      userId: entry.userId,
      action: entry.action,
      entityType: entry.entityType,
      entityId: entry.entityId,
      oldValues: entry.oldValues as Prisma.InputJsonValue || Prisma.JsonNull,
      newValues: entry.newValues as Prisma.InputJsonValue || Prisma.JsonNull,
      ipAddress: entry.ipAddress,
      userAgent: entry.userAgent,
      requestId: entry.requestId,
    }))
  });

  return result.count;
}

/**
 * Query audit logs with filters
 */
export async function queryAuditLogs(query: AuditLogQuery) {
  const where: Prisma.AuditLogWhereInput = {};

  if (query.userId) where.userId = query.userId;
  if (query.entityType) where.entityType = query.entityType;
  if (query.entityId) where.entityId = query.entityId;
  if (query.requestId) where.requestId = query.requestId;
  
  if (query.action) {
    where.action = Array.isArray(query.action) 
      ? { in: query.action } 
      : query.action;
  }

  if (query.startDate || query.endDate) {
    where.createdAt = {};
    if (query.startDate) where.createdAt.gte = query.startDate;
    if (query.endDate) where.createdAt.lte = query.endDate;
  }

  const [logs, total] = await Promise.all([
    prisma.auditLog.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      take: query.limit || 100,
      skip: query.offset || 0,
      include: {
        user: {
          select: { id: true, email: true, name: true }
        }
      }
    }),
    prisma.auditLog.count({ where })
  ]);

  return { logs, total };
}

/**
 * Get audit logs for a specific entity
 */
export async function getEntityAuditTrail(
  entityType: string,
  entityId: string,
  limit: number = 50
) {
  return prisma.auditLog.findMany({
    where: { entityType, entityId },
    orderBy: { createdAt: 'desc' },
    take: limit,
    include: {
      user: {
        select: { id: true, email: true, name: true }
      }
    }
  });
}

/**
 * Get audit logs for a specific user
 */
export async function getUserAuditHistory(
  userId: string,
  options: { startDate?: Date; endDate?: Date; limit?: number } = {}
) {
  return prisma.auditLog.findMany({
    where: {
      userId,
      ...(options.startDate || options.endDate ? {
        createdAt: {
          ...(options.startDate && { gte: options.startDate }),
          ...(options.endDate && { lte: options.endDate })
        }
      } : {})
    },
    orderBy: { createdAt: 'desc' },
    take: options.limit || 100
  });
}

// =============================================================================
// STATISTICS & REPORTING
// =============================================================================

/**
 * Get audit log statistics
 */
export async function getAuditStats(
  startDate: Date,
  endDate: Date
): Promise<AuditLogStats> {
  const logs = await prisma.auditLog.findMany({
    where: {
      createdAt: { gte: startDate, lte: endDate }
    },
    select: { action: true, entityType: true }
  });

  const byAction: Record<string, number> = {};
  const byEntityType: Record<string, number> = {};

  for (const log of logs) {
    byAction[log.action] = (byAction[log.action] || 0) + 1;
    byEntityType[log.entityType] = (byEntityType[log.entityType] || 0) + 1;
  }

  return {
    total: logs.length,
    byAction,
    byEntityType
  };
}

/**
 * Get daily audit counts for a date range
 */
export async function getDailyAuditCounts(
  startDate: Date,
  endDate: Date
): Promise<Array<{ date: string; count: number }>> {
  const result = await prisma.$queryRaw<Array<{ date: Date; count: bigint }>>\`
    SELECT 
      DATE("createdAt") as date,
      COUNT(*) as count
    FROM "audit_logs"
    WHERE "createdAt" >= \${startDate} AND "createdAt" <= \${endDate}
    GROUP BY DATE("createdAt")
    ORDER BY date ASC
  \`;

  return result.map(row => ({
    date: row.date.toISOString().split('T')[0],
    count: Number(row.count)
  }));
}

// =============================================================================
// DATA EXPORT (GDPR COMPLIANCE)
// =============================================================================

/**
 * Export all audit logs for a user (GDPR right to access)
 */
export async function exportUserAuditData(userId: string): Promise<{
  userId: string;
  exportDate: string;
  logs: any[];
}> {
  const logs = await prisma.auditLog.findMany({
    where: { userId },
    orderBy: { createdAt: 'asc' }
  });

  return {
    userId,
    exportDate: new Date().toISOString(),
    logs: logs.map(log => ({
      id: log.id,
      action: log.action,
      entityType: log.entityType,
      entityId: log.entityId,
      oldValues: log.oldValues,
      newValues: log.newValues,
      ipAddress: log.ipAddress,
      createdAt: log.createdAt.toISOString()
    }))
  };
}

/**
 * Delete audit logs older than retention period
 * Note: For compliance, consider anonymizing instead of deleting
 */
export async function deleteOldAuditLogs(
  retentionDays: number = 2555 // 7 years default for compliance
): Promise<{ deleted: number }> {
  const cutoffDate = new Date();
  cutoffDate.setDate(cutoffDate.getDate() - retentionDays);

  const result = await prisma.auditLog.deleteMany({
    where: {
      createdAt: { lt: cutoffDate }
    }
  });

  return { deleted: result.count };
}

/**
 * Anonymize old audit logs (preserve for analytics, remove PII)
 */
export async function anonymizeOldAuditLogs(
  anonymizationDays: number = 365
): Promise<{ anonymized: number }> {
  const cutoffDate = new Date();
  cutoffDate.setDate(cutoffDate.getDate() - anonymizationDays);

  const result = await prisma.auditLog.updateMany({
    where: {
      createdAt: { lt: cutoffDate },
      ipAddress: { not: null }
    },
    data: {
      ipAddress: null,
      userAgent: null,
      oldValues: {},
      newValues: {}
    }
  });

  return { anonymized: result.count };
}

// =============================================================================
// INTEGRITY VERIFICATION
// =============================================================================

/**
 * Verify audit log integrity (detect tampering)
 * This is a simple implementation - consider using cryptographic hashes for production
 */
export async function verifyAuditLogIntegrity(
  logId: string
): Promise<{ valid: boolean; reason?: string }> {
  const log = await prisma.auditLog.findUnique({
    where: { id: logId }
  });

  if (!log) {
    return { valid: false, reason: 'Log not found' };
  }

  // Check that createdAt is in the past
  if (log.createdAt > new Date()) {
    return { valid: false, reason: 'Invalid timestamp' };
  }

  // Additional integrity checks can be added here
  // e.g., verify hash chain, check for gaps in sequence, etc.

  return { valid: true };
}

/**
 * Get sequence integrity report
 */
export async function getSequenceIntegrityReport(
  startDate: Date,
  endDate: Date
): Promise<{
  hasGaps: boolean;
  gapCount: number;
  gaps: Array<{ expected: number; found: number | null }>;
}> {
  // Get all logs in date range ordered by creation
  const logs = await prisma.auditLog.findMany({
    where: {
      createdAt: { gte: startDate, lte: endDate }
    },
    orderBy: { createdAt: 'asc' },
    select: { id: true, createdAt: true }
  });

  const gaps: Array<{ expected: number; found: number | null }> = [];
  
  // Simple gap detection based on timestamps
  for (let i = 1; i < logs.length; i++) {
    const prevTime = logs[i - 1].createdAt.getTime();
    const currTime = logs[i].createdAt.getTime();
    const expectedDiff = 60000; // 1 minute threshold
    
    if (currTime - prevTime > expectedDiff * 10) {
      gaps.push({
        expected: i,
        found: i
      });
    }
  }

  return {
    hasGaps: gaps.length > 0,
    gapCount: gaps.length,
    gaps
  };
}
`;
  },

  /**
   * Generate Audit Verification Job
   */
  generateAuditVerifyJob() {
    return `/**
 * Audit Log Verification Job
 * Generated by Backend Agent v1.0.0
 * 
 * Scheduled job to verify audit log integrity, detect anomalies,
 * and ensure compliance with retention policies.
 */

import { prisma } from '@/lib/prisma';
import { 
  getAuditStats, 
  getSequenceIntegrityReport,
  anonymizeOldAuditLogs,
  deleteOldAuditLogs 
} from '@/services/auditLog';

// =============================================================================
// CONFIGURATION
// =============================================================================

const VERIFICATION_CONFIG = {
  /** Check logs from the last N days */
  checkWindowDays: 7,
  
  /** Anonymize logs older than N days */
  anonymizationDays: 365,
  
  /** Delete logs older than N days (for compliance) */
  retentionDays: 2555, // 7 years
  
  /** Maximum gap duration in minutes before flagging */
  maxGapMinutes: 60,
  
  /** Minimum expected daily log count */
  minDailyLogCount: 10,
};

// =============================================================================
// JOB RESULT TYPES
// =============================================================================

interface VerificationResult {
  success: boolean;
  timestamp: string;
  duration: number;
  checks: {
    integrity: { passed: boolean; details: string };
    gaps: { passed: boolean; gapCount: number };
    volume: { passed: boolean; dailyCount: number };
    retention: { passed: boolean; actions: string[] };
  };
  errors: string[];
  warnings: string[];
}

// =============================================================================
// VERIFICATION FUNCTIONS
// =============================================================================

/**
 * Check audit log integrity
 */
async function checkIntegrity(startDate: Date): Promise<{
  passed: boolean;
  details: string;
}> {
  try {
    const logs = await prisma.auditLog.findMany({
      where: { createdAt: { gte: startDate } },
      select: { id: true, createdAt: true, action: true },
      take: 1000 // Sample check
    });

    // Check for valid actions
    const invalidActions = logs.filter(log => !log.action || log.action.trim() === '');
    if (invalidActions.length > 0) {
      return {
        passed: false,
        details: \`Found \${invalidActions.length} logs with invalid actions\`
      };
    }

    // Check for future timestamps
    const futureLogs = logs.filter(log => log.createdAt > new Date());
    if (futureLogs.length > 0) {
      return {
        passed: false,
        details: \`Found \${futureLogs.length} logs with future timestamps\`
      };
    }

    return {
      passed: true,
      details: \`Verified \${logs.length} logs successfully\`
    };
  } catch (error) {
    return {
      passed: false,
      details: \`Integrity check failed: \${error instanceof Error ? error.message : 'Unknown error'}\`
    };
  }
}

/**
 * Check for gaps in audit log sequence
 */
async function checkGaps(startDate: Date, endDate: Date): Promise<{
  passed: boolean;
  gapCount: number;
  gaps: Array<{ time: string; duration: number }>;
}> {
  const report = await getSequenceIntegrityReport(startDate, endDate);
  
  const gaps = report.gaps.map(g => ({
    time: new Date().toISOString(), // Placeholder
    duration: 0 // Placeholder
  }));

  return {
    passed: !report.hasGaps,
    gapCount: report.gapCount,
    gaps
  };
}

/**
 * Check audit log volume
 */
async function checkVolume(startDate: Date, endDate: Date): Promise<{
  passed: boolean;
  dailyCount: number;
  details: string;
}> {
  const stats = await getAuditStats(startDate, endDate);
  const daysDiff = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
  const dailyCount = Math.round(stats.total / Math.max(daysDiff, 1));

  const passed = dailyCount >= VERIFICATION_CONFIG.minDailyLogCount;
  
  return {
    passed,
    dailyCount,
    details: \`Average \${dailyCount} logs/day over \${daysDiff} days\`
  };
}

/**
 * Apply retention policies
 */
async function applyRetentionPolicies(): Promise<{
  passed: boolean;
  actions: string[];
}> {
  const actions: string[] = [];

  try {
    // Anonymize old logs
    const anonymizeResult = await anonymizeOldAuditLogs(
      VERIFICATION_CONFIG.anonymizationDays
    );
    if (anonymizeResult.anonymized > 0) {
      actions.push(\`Anonymized \${anonymizeResult.anonymized} old logs\`);
    }

    // Note: Deletion should be carefully considered for compliance
    // Uncomment if your compliance requirements allow deletion
    // const deleteResult = await deleteOldAuditLogs(VERIFICATION_CONFIG.retentionDays);
    // if (deleteResult.deleted > 0) {
    //   actions.push(\`Deleted \${deleteResult.deleted} expired logs\`);
    // }

    return { passed: true, actions };
  } catch (error) {
    actions.push(\`Retention policy error: \${error instanceof Error ? error.message : 'Unknown'}\`);
    return { passed: false, actions };
  }
}

// =============================================================================
// MAIN JOB
// =============================================================================

/**
 * Run audit log verification job
 */
export async function runAuditVerification(): Promise<VerificationResult> {
  const startTime = Date.now();
  const errors: string[] = [];
  const warnings: string[] = [];

  const endDate = new Date();
  const startDate = new Date();
  startDate.setDate(startDate.getDate() - VERIFICATION_CONFIG.checkWindowDays);

  console.log('Starting audit log verification...');
  console.log(\`Check period: \${startDate.toISOString()} to \${endDate.toISOString()}\`);

  // Run all checks
  const [integrityCheck, gapsCheck, volumeCheck, retentionResult] = await Promise.all([
    checkIntegrity(startDate),
    checkGaps(startDate, endDate),
    checkVolume(startDate, endDate),
    applyRetentionPolicies()
  ]);

  // Collect warnings
  if (!gapsCheck.passed) {
    warnings.push(\`Found \${gapsCheck.gapCount} gaps in audit log sequence\`);
  }
  if (!volumeCheck.passed) {
    warnings.push(\`Low audit log volume: \${volumeCheck.dailyCount} logs/day\`);
  }

  // Determine overall success
  const success = integrityCheck.passed && retentionResult.passed;

  const result: VerificationResult = {
    success,
    timestamp: new Date().toISOString(),
    duration: Date.now() - startTime,
    checks: {
      integrity: integrityCheck,
      gaps: { passed: gapsCheck.passed, gapCount: gapsCheck.gapCount },
      volume: { passed: volumeCheck.passed, dailyCount: volumeCheck.dailyCount },
      retention: retentionResult
    },
    errors,
    warnings
  };

  // Log results
  console.log('Audit verification complete:');
  console.log(\`  - Integrity: \${integrityCheck.passed ? 'PASS' : 'FAIL'}\`);
  console.log(\`  - Gaps: \${gapsCheck.passed ? 'PASS' : 'WARN'} (\${gapsCheck.gapCount} gaps)\`);
  console.log(\`  - Volume: \${volumeCheck.passed ? 'PASS' : 'WARN'} (\${volumeCheck.dailyCount} logs/day)\`);
  console.log(\`  - Retention: \${retentionResult.passed ? 'PASS' : 'FAIL'}\`);
  console.log(\`  - Duration: \${result.duration}ms\`);

  // Store verification result
  await prisma.auditLog.create({
    data: {
      action: 'SYSTEM_BACKUP',
      entityType: 'VerificationJob',
      newValues: result as any
    }
  });

  return result;
}

// =============================================================================
// SCHEDULER INTEGRATION
// =============================================================================

/**
 * Schedule the verification job
 * Call this from your cron scheduler
 */
export function scheduleAuditVerification(): void {
  // This would typically be called by a cron scheduler
  // Example: run every day at 3 AM
  runAuditVerification()
    .then(result => {
      if (!result.success) {
        console.error('Audit verification failed:', result.errors);
        // TODO: Send alert to operations team
      }
    })
    .catch(error => {
      console.error('Audit verification error:', error);
      // TODO: Send alert to operations team
    });
}

// =============================================================================
// CLI ENTRY POINT
// =============================================================================

// Allow running directly via: npx ts-node src/jobs/auditVerify.ts
if (require.main === module) {
  runAuditVerification()
    .then(result => {
      console.log(JSON.stringify(result, null, 2));
      process.exit(result.success ? 0 : 1);
    })
    .catch(error => {
      console.error('Fatal error:', error);
      process.exit(1);
    });
}

export default runAuditVerification;
`;
  }
};
