/**
 * SRE Agent
 * Version: 1.0.0
 * 
 * Responsibility: Generate operational scripts for backups, restores,
 * monitoring, and maintenance for the CargoBit payment system.
 * 
 * Inputs:
 * - migrations/0001_init.sql (from Architect Agent)
 * 
 * Outputs:
 * - ops/backup-db.sh
 * - ops/restore-db.sh
 * - ops/cron-backup.yaml
 * - ops/export-audit-log.ts
 */

module.exports = {
  name: 'sre-agent',
  version: '1.0.0',
  
  /**
   * Main execution method
   * @param {Object} input - Input from orchestrator containing migrations
   * @returns {Object} Generated files
   */
  run(input) {
    console.log('  → Generating backup script...');
    console.log('  → Generating restore script...');
    console.log('  → Generating cron configuration...');
    console.log('  → Generating audit log export tool...');
    
    return {
      files: {
        'ops/backup-db.sh': this.generateBackupScript(),
        'ops/restore-db.sh': this.generateRestoreScript(),
        'ops/cron-backup.yaml': this.generateCronConfig(),
        'ops/export-audit-log.ts': this.generateAuditExport()
      },
      metadata: {
        generated_at: new Date().toISOString(),
        scripts: ['backup-db.sh', 'restore-db.sh', 'export-audit-log.ts'],
        schedules: ['daily-full', 'hourly-incremental', 'continuous-wal']
      }
    };
  },

  /**
   * Generate Database Backup Script
   */
  generateBackupScript() {
    return `#!/bin/bash
#
# CargoBit Database Backup Script
# Generated by SRE Agent v1.0.0
#
# Usage: ./backup-db.sh [OPTIONS]
#
# Options:
#   -t, --type       Backup type: full, incremental, pitr (default: full)
#   -o, --output     Output directory (default: /var/backups/postgres)
#   -c, --compress   Compression level 0-9 (default: 6)
#   -e, --encrypt    Encrypt backup with GPG
#   -r, --retention  Retention days (default: 30)
#   -v, --verbose    Verbose output
#   -h, --help       Show this help message
#
# Environment Variables:
#   DATABASE_URL     PostgreSQL connection string
#   BACKUP_S3_BUCKET S3 bucket for offsite backup (optional)
#   GPG_KEY_ID       GPG key ID for encryption (optional)
#

set -euo pipefail

# =============================================================================
# CONFIGURATION
# =============================================================================

SCRIPT_NAME=$(basename "$0")
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

# Default values
BACKUP_TYPE="full"
OUTPUT_DIR="${BACKUP_DIR:-/var/backups/postgres}"
COMPRESS_LEVEL=6
ENCRYPT=false
RETENTION_DAYS=30
VERBOSE=false

# Database configuration from environment
DB_HOST="${POSTGRES_HOST:-localhost}"
DB_PORT="${POSTGRES_PORT:-5432}"
DB_NAME="${POSTGRES_DB:-cargobit}"
DB_USER="${POSTGRES_USER:-postgres}"

# Timestamp for backup filename
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
DATE_ONLY=$(date +%Y%m%d)

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m' # No Color

# =============================================================================
# FUNCTIONS
# =============================================================================

log_info() {
    echo -e "\${BLUE}[INFO]\${NC} $1"
}

log_success() {
    echo -e "\${GREEN}[SUCCESS]\${NC} $1"
}

log_warning() {
    echo -e "\${YELLOW}[WARNING]\${NC} $1"
}

log_error() {
    echo -e "\${RED}[ERROR]\${NC} $1" >&2
}

show_help() {
    cat << EOF
CargoBit Database Backup Script

Usage: $SCRIPT_NAME [OPTIONS]

Options:
    -t, --type       Backup type: full, incremental, pitr (default: full)
    -o, --output     Output directory (default: /var/backups/postgres)
    -c, --compress   Compression level 0-9 (default: 6)
    -e, --encrypt    Encrypt backup with GPG
    -r, --retention  Retention days (default: 30)
    -v, --verbose    Verbose output
    -h, --help       Show this help message

Examples:
    # Full backup with default settings
    $SCRIPT_NAME

    # Incremental backup with encryption
    $SCRIPT_NAME -t incremental -e

    # PITR backup to custom directory
    $SCRIPT_NAME -t pitr -o /mnt/backup/postgres

Environment Variables:
    DATABASE_URL       PostgreSQL connection string
    POSTGRES_HOST      Database host (default: localhost)
    POSTGRES_PORT      Database port (default: 5432)
    POSTGRES_DB        Database name (default: cargobit)
    POSTGRES_USER      Database user (default: postgres)
    BACKUP_S3_BUCKET   S3 bucket for offsite backup (optional)
    GPG_KEY_ID         GPG key ID for encryption (optional)
EOF
}

parse_arguments() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            -t|--type)
                BACKUP_TYPE="$2"
                shift 2
                ;;
            -o|--output)
                OUTPUT_DIR="$2"
                shift 2
                ;;
            -c|--compress)
                COMPRESS_LEVEL="$2"
                shift 2
                ;;
            -e|--encrypt)
                ENCRYPT=true
                shift
                ;;
            -r|--retention)
                RETENTION_DAYS="$2"
                shift 2
                ;;
            -v|--verbose)
                VERBOSE=true
                shift
                ;;
            -h|--help)
                show_help
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
    done
}

check_dependencies() {
    local missing=()
    
    command -v pg_dump >/dev/null 2>&1 || missing+=("pg_dump (postgresql-client)")
    command -v gzip >/dev/null 2>&1 || missing+=("gzip")
    
    if [[ "$ENCRYPT" == true ]]; then
        command -v gpg >/dev/null 2>&1 || missing+=("gpg")
    fi
    
    if [[ -n "${BACKUP_S3_BUCKET:-}" ]]; then
        command -v aws >/dev/null 2>&1 || missing+=("aws-cli")
    fi
    
    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing dependencies:"
        printf '  - %s\\n' "\${missing[@]}"
        exit 1
    fi
}

create_output_dir() {
    if [[ ! -d "$OUTPUT_DIR" ]]; then
        log_info "Creating output directory: $OUTPUT_DIR"
        mkdir -p "$OUTPUT_DIR"
    fi
    
    if [[ ! -w "$OUTPUT_DIR" ]]; then
        log_error "Output directory is not writable: $OUTPUT_DIR"
        exit 1
    fi
}

# =============================================================================
# BACKUP FUNCTIONS
# =============================================================================

backup_full() {
    local backup_file="${OUTPUT_DIR}/${DB_NAME}_full_${TIMESTAMP}.sql.gz"
    local checksum_file="${backup_file}.sha256"
    
    log_info "Starting full backup of database: $DB_NAME"
    log_info "Output file: $backup_file"
    
    # Record backup start in database
    local backup_id=$(psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -t -c "
        INSERT INTO backup_metadata (id, backup_type, status, \"startedAt\")
        VALUES (gen_random_uuid(), 'full', 'running', NOW())
        RETURNING id;
    " 2>/dev/null | tr -d '[:space:]')
    
    # Perform backup
    local start_time=$(date +%s)
    
    if pg_dump -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \\
        --format=plain \\
        --no-owner \\
        --no-acl \\
        --verbose=$VERBOSE \\
        | gzip -${COMPRESS_LEVEL} > "$backup_file"; then
        
        local end_time=$(date +%s)
        local duration=$((end_time - start_time))
        local size=$(stat -f%z "$backup_file" 2>/dev/null || stat -c%s "$backup_file")
        
        # Generate checksum
        sha256sum "$backup_file" > "$checksum_file"
        
        # Update backup record
        psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "
            UPDATE backup_metadata 
            SET status = 'completed', 
                \"sizeBytes\" = $size,
                \"storagePath\" = '$backup_file',
                \"completedAt\" = NOW(),
                checksum = '$(cut -d' ' -f1 "$checksum_file")'
            WHERE id = '$backup_id';
        " 2>/dev/null || true
        
        log_success "Backup completed successfully"
        log_info "  Duration: ${duration}s"
        log_info "  Size: $(numfmt --to=iec-i --suffix=B $size)"
        log_info "  Checksum: $(cut -d' ' -f1 "$checksum_file")"
        
    else
        # Update backup record as failed
        psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "
            UPDATE backup_metadata 
            SET status = 'failed', 
                \"completedAt\" = NOW(),
                \"errorMessage\" = 'pg_dump failed'
            WHERE id = '$backup_id';
        " 2>/dev/null || true
        
        log_error "Backup failed"
        rm -f "$backup_file"
        exit 1
    fi
    
    # Encrypt if requested
    if [[ "$ENCRYPT" == true ]]; then
        encrypt_file "$backup_file"
    fi
    
    echo "$backup_file"
}

backup_incremental() {
    local base_backup=$(ls -t "${OUTPUT_DIR}/${DB_NAME}_full_"*.sql.gz 2>/dev/null | head -1)
    
    if [[ -z "$base_backup" ]]; then
        log_warning "No full backup found, performing full backup instead"
        backup_full
        return
    fi
    
    local backup_file="${OUTPUT_DIR}/${DB_NAME}_incr_${TIMESTAMP}.sql.gz"
    
    log_info "Starting incremental backup based on: $base_backup"
    
    # For PostgreSQL, we use WAL archiving for true incremental backups
    # This is a simplified version that backs up changes since last backup
    # In production, use pg_basebackup with WAL archiving
    
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "
        INSERT INTO backup_metadata (id, backup_type, status, \"startedAt\")
        VALUES (gen_random_uuid(), 'incremental', 'running', NOW());
    " 2>/dev/null
    
    # Use pg_dump with changes-only (simplified approach)
    # Real PITR requires WAL archiving setup
    pg_dump -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \\
        --format=plain \\
        --data-only \\
        | gzip -${COMPRESS_LEVEL} > "$backup_file"
    
    log_success "Incremental backup completed: $backup_file"
    echo "$backup_file"
}

backup_pitr() {
    local wal_dir="${OUTPUT_DIR}/wal_archive"
    
    log_info "Setting up PITR backup (WAL archiving)"
    
    # Create WAL archive directory
    mkdir -p "$wal_dir"
    
    # Archive current WAL segment
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "
        SELECT pg_switch_wal();
    " 2>/dev/null
    
    # Copy WAL files to archive
    # Note: This requires wal_level = replica or higher in postgresql.conf
    # and archive_mode = on with archive_command set
    
    log_info "WAL archiving configured"
    log_warning "Ensure postgresql.conf has:"
    log_warning "  wal_level = replica"
    log_warning "  archive_mode = on"
    log_warning "  archive_command = 'cp %p ${wal_dir}/%f'"
}

encrypt_file() {
    local file="$1"
    local gpg_key="${GPG_KEY_ID:-}"
    
    if [[ -z "$gpg_key" ]]; then
        log_warning "No GPG_KEY_ID set, skipping encryption"
        return
    fi
    
    log_info "Encrypting backup with GPG key: $gpg_key"
    
    gpg --encrypt \\
        --recipient "$gpg_key" \\
        --trust-model always \\
        --output "\${file}.gpg" \\
        "$file"
    
    if [[ $? -eq 0 ]]; then
        rm -f "$file"
        log_success "Encrypted backup saved as: \${file}.gpg"
    else
        log_error "Encryption failed"
        exit 1
    fi
}

upload_to_s3() {
    local backup_file="$1"
    local s3_path="s3://${BACKUP_S3_BUCKET}/postgres/${DB_NAME}/$(basename "$backup_file")"
    
    if [[ -z "${BACKUP_S3_BUCKET:-}" ]]; then
        log_warning "No BACKUP_S3_BUCKET set, skipping S3 upload"
        return
    fi
    
    log_info "Uploading backup to S3: $s3_path"
    
    aws s3 cp "$backup_file" "$s3_path" \\
        --storage-class STANDARD_IA \\
        --metadata "database=$DB_NAME,type=$BACKUP_TYPE,date=$TIMESTAMP"
    
    if [[ $? -eq 0 ]]; then
        log_success "Backup uploaded to S3"
    else
        log_error "S3 upload failed"
    fi
}

cleanup_old_backups() {
    log_info "Cleaning up backups older than $RETENTION_DAYS days"
    
    local deleted_count=$(find "$OUTPUT_DIR" \\
        -name "${DB_NAME}_*" \\
        -type f \\
        -mtime +$RETENTION_DAYS \\
        -delete -print | wc -l)
    
    if [[ $deleted_count -gt 0 ]]; then
        log_info "Deleted $deleted_count old backup(s)"
    fi
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    parse_arguments "$@"
    
    log_info "=========================================="
    log_info "CargoBit Database Backup"
    log_info "=========================================="
    log_info "Type: $BACKUP_TYPE"
    log_info "Database: $DB_NAME @ $DB_HOST:$DB_PORT"
    log_info "Output: $OUTPUT_DIR"
    log_info "Timestamp: $TIMESTAMP"
    log_info "=========================================="
    
    check_dependencies
    create_output_dir
    
    local backup_file=""
    
    case "$BACKUP_TYPE" in
        full)
            backup_file=$(backup_full)
            ;;
        incremental)
            backup_file=$(backup_incremental)
            ;;
        pitr)
            backup_pitr
            ;;
        *)
            log_error "Unknown backup type: $BACKUP_TYPE"
            exit 1
            ;;
    esac
    
    # Upload to S3 if configured
    if [[ -n "$backup_file" ]]; then
        upload_to_s3 "$backup_file"
    fi
    
    # Cleanup old backups
    cleanup_old_backups
    
    log_success "Backup process completed"
}

# Run main
main "$@"
`;
  },

  /**
   * Generate Database Restore Script
   */
  generateRestoreScript() {
    return `#!/bin/bash
#
# CargoBit Database Restore Script
# Generated by SRE Agent v1.0.0
#
# Usage: ./restore-db.sh [OPTIONS] <backup_file>
#
# Options:
#   -t, --target       Target database name (default: from backup)
#   -h, --host         Database host (default: localhost)
#   -p, --port         Database port (default: 5432)
#   -u, --user         Database user (default: postgres)
#   -d, --decrypt      Decrypt GPG encrypted backup
#   -k, --key          GPG private key file for decryption
#   -P, --point-in-time Point-in-time recovery target (ISO timestamp)
#   -l, --list         List available backups
#   -v, --verbose      Verbose output
#   -n, --dry-run      Show what would be done without executing
#   --help             Show this help message
#
# Examples:
#   # Restore from backup file
#   ./restore-db.sh /backups/cargobit_full_20240101.sql.gz
#
#   # Restore to different database
#   ./restore-db.sh -t cargobit_test /backups/cargobit_full_20240101.sql.gz
#
#   # Point-in-time recovery
#   ./restore-db.sh -P "2024-01-01 12:00:00" /backups/base/
#

set -euo pipefail

# =============================================================================
# CONFIGURATION
# =============================================================================

SCRIPT_NAME=$(basename "$0")
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

# Default values
TARGET_DB=""
DB_HOST="${POSTGRES_HOST:-localhost}"
DB_PORT="${POSTGRES_PORT:-5432}"
DB_USER="${POSTGRES_USER:-postgres}"
DECRYPT=false
GPG_KEY=""
PITR_TARGET=""
VERBOSE=false
DRY_RUN=false
LIST_BACKUPS=false
BACKUP_DIR="${BACKUP_DIR:-/var/backups/postgres}"

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

# =============================================================================
# FUNCTIONS
# =============================================================================

log_info() {
    echo -e "\${BLUE}[INFO]\${NC} $1"
}

log_success() {
    echo -e "\${GREEN}[SUCCESS]\${NC} $1"
}

log_warning() {
    echo -e "\${YELLOW}[WARNING]\${NC} $1"
}

log_error() {
    echo -e "\${RED}[ERROR]\${NC} $1" >&2
}

show_help() {
    cat << EOF
CargoBit Database Restore Script

Usage: $SCRIPT_NAME [OPTIONS] <backup_file>

Options:
    -t, --target        Target database name (default: from backup)
    -h, --host          Database host (default: localhost)
    -p, --port          Database port (default: 5432)
    -u, --user          Database user (default: postgres)
    -d, --decrypt       Decrypt GPG encrypted backup
    -k, --key           GPG private key file for decryption
    -P, --point-in-time Point-in-time recovery target (ISO timestamp)
    -l, --list          List available backups
    -v, --verbose       Verbose output
    -n, --dry-run       Show what would be done without executing
    --help              Show this help message

Examples:
    # Restore from backup file
    $SCRIPT_NAME /backups/cargobit_full_20240101.sql.gz

    # Restore to different database
    $SCRIPT_NAME -t cargobit_test /backups/cargobit_full_20240101.sql.gz

    # Point-in-time recovery
    $SCRIPT_NAME -P "2024-01-01 12:00:00" /backups/base/

    # List available backups
    $SCRIPT_NAME -l
EOF
}

parse_arguments() {
    local positional=()
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            -t|--target)
                TARGET_DB="$2"
                shift 2
                ;;
            -h|--host)
                DB_HOST="$2"
                shift 2
                ;;
            -p|--port)
                DB_PORT="$2"
                shift 2
                ;;
            -u|--user)
                DB_USER="$2"
                shift 2
                ;;
            -d|--decrypt)
                DECRYPT=true
                shift
                ;;
            -k|--key)
                GPG_KEY="$2"
                shift 2
                ;;
            -P|--point-in-time)
                PITR_TARGET="$2"
                shift 2
                ;;
            -l|--list)
                LIST_BACKUPS=true
                shift
                ;;
            -v|--verbose)
                VERBOSE=true
                shift
                ;;
            -n|--dry-run)
                DRY_RUN=true
                shift
                ;;
            --help)
                show_help
                exit 0
                ;;
            -*)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
            *)
                positional+=("$1")
                shift
                ;;
        esac
    done
    
    BACKUP_FILE="${positional[0]:-}"
}

check_dependencies() {
    local missing=()
    
    command -v psql >/dev/null 2>&1 || missing+=("psql (postgresql-client)")
    command -v gunzip >/dev/null 2>&1 || missing+=("gzip")
    
    if [[ "$DECRYPT" == true ]]; then
        command -v gpg >/dev/null 2>&1 || missing+=("gpg")
    fi
    
    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing dependencies:"
        printf '  - %s\\n' "\${missing[@]}"
        exit 1
    fi
}

list_backups() {
    log_info "Available backups in $BACKUP_DIR:"
    echo ""
    
    printf "%-40s %-12s %-15s %s\\n" "FILENAME" "TYPE" "SIZE" "DATE"
    printf "%-40s %-12s %-15s %s\\n" "--------" "----" "----" "----"
    
    find "$BACKUP_DIR" \\
        -name "*.sql.gz" \\
        -o -name "*.sql.gz.gpg" \\
        -type f \\
        -printf "%f %TY-%Tm-%Td %TH:%TM %s\\n" \\
    | sort -k2,3 \\
    | while read -r filename date time size; do
        local type="full"
        if [[ "$filename" == *"_incr_"* ]]; then
            type="incremental"
        elif [[ "$filename" == *"_pitr_"* ]]; then
            type="pitr"
        fi
        
        local human_size=$(numfmt --to=iec-i --suffix=B $size 2>/dev/null || echo "$size")
        printf "%-40s %-12s %-15s %s %s\\n" "$filename" "$type" "$human_size" "$date" "$time"
    done
    
    echo ""
}

verify_backup_file() {
    local file="$1"
    
    if [[ ! -f "$file" ]]; then
        log_error "Backup file not found: $file"
        exit 1
    fi
    
    # Check checksum file if exists
    local checksum_file="${file}.sha256"
    if [[ -f "$checksum_file" ]]; then
        log_info "Verifying backup integrity..."
        
        if sha256sum -c "$checksum_file" --quiet; then
            log_success "Checksum verification passed"
        else
            log_error "Checksum verification failed"
            read -p "Continue anyway? (y/N): " confirm
            if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
                exit 1
            fi
        fi
    fi
}

decrypt_backup() {
    local file="$1"
    local decrypted_file="${file%.gpg}"
    
    if [[ "$DECRYPT" != true ]]; then
        echo "$file"
        return
    fi
    
    log_info "Decrypting backup..."
    
    if [[ -n "$GPG_KEY" ]]; then
        gpg --import "$GPG_KEY" 2>/dev/null || true
    fi
    
    gpg --decrypt --output "$decrypted_file" "$file"
    
    if [[ $? -eq 0 ]]; then
        log_success "Decryption successful"
        echo "$decrypted_file"
    else
        log_error "Decryption failed"
        exit 1
    fi
}

confirm_restore() {
    local db="$1"
    
    log_warning "This will REPLACE all data in database: $db"
    log_warning "All existing data will be lost!"
    echo ""
    read -p "Are you sure you want to continue? (yes/N): " confirm
    
    if [[ "$confirm" != "yes" ]]; then
        log_info "Restore cancelled"
        exit 0
    fi
}

create_target_database() {
    local db="$1"
    
    log_info "Creating target database: $db"
    
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY RUN] Would create database: $db"
        return
    fi
    
    # Disconnect existing connections
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d postgres -c "
        SELECT pg_terminate_backend(pid)
        FROM pg_stat_activity
        WHERE datname = '$db' AND pid <> pg_backend_pid();
    " 2>/dev/null || true
    
    # Drop and recreate database
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d postgres -c "
        DROP DATABASE IF EXISTS $db;
        CREATE DATABASE $db;
    "
}

restore_database() {
    local backup_file="$1"
    local target_db="$2"
    
    log_info "Restoring database from: $backup_file"
    log_info "Target database: $target_db"
    
    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY RUN] Would restore from: $backup_file"
        return
    fi
    
    local start_time=$(date +%s)
    
    # Decompress and restore
    if [[ "$backup_file" == *.gz ]]; then
        gunzip -c "$backup_file" | psql \\
            -h "$DB_HOST" \\
            -p "$DB_PORT" \\
            -U "$DB_USER" \\
            -d "$target_db" \\
            -v ON_ERROR_STOP=1 \\
            -q
    else
        psql \\
            -h "$DB_HOST" \\
            -p "$DB_PORT" \\
            -U "$DB_USER" \\
            -d "$target_db" \\
            -v ON_ERROR_STOP=1 \\
            -f "$backup_file"
    fi
    
    local end_time=$(date +%s)
    local duration=$((end_time - start_time))
    
    if [[ $? -eq 0 ]]; then
        log_success "Restore completed in ${duration}s"
    else
        log_error "Restore failed"
        exit 1
    fi
}

restore_pitr() {
    local base_dir="$1"
    local target="$2"
    
    log_info "Performing point-in-time recovery to: $target"
    log_warning "PITR requires base backup + WAL archives"
    
    # This is a simplified version
    # Full PITR requires:
    # 1. Restore base backup
    # 2. Configure recovery.conf / postgresql.conf
    # 3. Start PostgreSQL in recovery mode
    # 4. Replay WAL until target time
    
    log_info "1. Restoring base backup..."
    # find and restore base backup
    
    log_info "2. Configuring recovery parameters..."
    # configure recovery settings
    
    log_info "3. Starting recovery..."
    # start postgres in recovery mode
    
    log_warning "PITR is a complex operation. Consider using pgBackRest or Barman."
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    parse_arguments "$@"
    check_dependencies
    
    # List mode
    if [[ "$LIST_BACKUPS" == true ]]; then
        list_backups
        exit 0
    fi
    
    # Require backup file
    if [[ -z "$BACKUP_FILE" ]]; then
        log_error "No backup file specified"
        show_help
        exit 1
    fi
    
    log_info "=========================================="
    log_info "CargoBit Database Restore"
    log_info "=========================================="
    log_info "Backup file: $BACKUP_FILE"
    log_info "Target host: $DB_HOST:$DB_PORT"
    log_info "=========================================="
    
    # Verify and prepare backup
    verify_backup_file "$BACKUP_FILE"
    
    local restore_file="$BACKUP_FILE"
    if [[ "$BACKUP_FILE" == *.gpg ]]; then
        restore_file=$(decrypt_backup "$BACKUP_FILE")
    fi
    
    # Determine target database
    local target_db="${TARGET_DB:-cargobit}"
    
    # Confirm destructive operation
    confirm_restore "$target_db"
    
    # Create target database
    create_target_database "$target_db"
    
    # Perform restore
    if [[ -n "$PITR_TARGET" ]]; then
        restore_pitr "$restore_file" "$PITR_TARGET"
    else
        restore_database "$restore_file" "$target_db"
    fi
    
    # Verify restore
    log_info "Verifying restore..."
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$target_db" -c "
        SELECT table_name, 
               pg_size_pretty(pg_total_relation_size(quote_ident(table_name))) as size
        FROM information_schema.tables 
        WHERE table_schema = 'public'
        ORDER BY table_name;
    "
    
    log_success "Restore process completed"
}

# Run main
main "$@"
`;
  },

  /**
   * Generate Cron Configuration
   */
  generateCronConfig() {
    return `# CargoBit Backup Cron Configuration
# Generated by SRE Agent v1.0.0
#
# This file defines the backup schedule for CargoBit payment system.
# Copy to /etc/cron.d/cargobit-backup or import via crontab.
#
# Environment setup
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=ops@cargobit.local

# Environment variables (adjust as needed)
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=cargobit
POSTGRES_USER=postgres
BACKUP_DIR=/var/backups/postgres

# =============================================================================
# BACKUP SCHEDULE
# =============================================================================

# Full backup - Daily at 2 AM
0 2 * * * postgres /opt/cargobit/ops/backup-db.sh -t full -r 30 >> /var/log/cargobit/backup.log 2>&1

# Incremental backup - Every 4 hours
0 */4 * * * postgres /opt/cargobit/ops/backup-db.sh -t incremental -r 7 >> /var/log/cargobit/backup.log 2>&1

# WAL archive sync - Every 15 minutes (for PITR)
*/15 * * * * postgres rsync -av /var/lib/postgresql/wal_archive/ /var/backups/postgres/wal_archive/ >> /var/log/cargobit/wal-sync.log 2>&1

# =============================================================================
# MAINTENANCE SCHEDULE
# =============================================================================

# Database vacuum analyze - Daily at 3 AM (after backup)
0 3 * * * postgres vacuumdb -h localhost -U postgres -d cargobit --analyze >> /var/log/cargobit/maintenance.log 2>&1

# Audit log verification - Daily at 4 AM
0 4 * * * postgres cd /opt/cargobit && npx ts-node src/jobs/auditVerify.ts >> /var/log/cargobit/audit-verify.log 2>&1

# Audit log export - Weekly on Sunday at 5 AM
0 5 * * 0 postgres cd /opt/cargobit && npx ts-node ops/export-audit-log.ts >> /var/log/cargobit/audit-export.log 2>&1

# Backup verification - Weekly on Sunday at 6 AM
0 6 * * 0 postgres /opt/cargobit/ops/verify-backup.sh >> /var/log/cargobit/backup-verify.log 2>&1

# =============================================================================
# CLEANUP SCHEDULE
# =============================================================================

# Cleanup old logs - Monthly on 1st at midnight
0 0 1 * * postgres find /var/log/cargobit -name "*.log" -mtime +90 -delete >> /var/log/cargobit/cleanup.log 2>&1

# Cleanup temp files - Daily at midnight
0 0 * * * postgres find /tmp -name "cargobit_*" -mtime +1 -delete >> /var/log/cargobit/cleanup.log 2>&1

# =============================================================================
# MONITORING & HEALTH CHECKS
# =============================================================================

# Check backup age - Every hour
0 * * * * postgres test $(find /var/backups/postgres -name "cargobit_full_*.sql.gz" -mtime -1 | wc -l) -gt 0 || echo "WARNING: No backup in last 24h" | mail -s "Backup Alert" ops@cargobit.local

# Check disk space - Every 6 hours
0 */6 * * * postgres df -h /var/backups/postgres | awk 'NR==2 {if ($5+0 > 80) print "WARNING: Backup disk usage at " $5}' | mail -s "Disk Space Alert" ops@cargobit.local

# =============================================================================
# KUBERNETES CRONJOB EQUIVALENT
# =============================================================================

# If running in Kubernetes, use this CronJob manifest instead:
#
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: cargobit-backup
#   namespace: cargobit
# spec:
#   schedule: "0 2 * * *"
#   concurrencyPolicy: Forbid
#   successfulJobsHistoryLimit: 3
#   failedJobsHistoryLimit: 3
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: backup
#             image: cargobit/backup:latest
#             command: ["/opt/cargobit/ops/backup-db.sh"]
#             args: ["-t", "full"]
#             env:
#             - name: POSTGRES_HOST
#               valueFrom:
#                 secretKeyRef:
#                   name: cargobit-secrets
#                   key: postgres-host
#             - name: DATABASE_URL
#               valueFrom:
#                 secretKeyRef:
#                   name: cargobit-secrets
#                   key: database-url
#             volumeMounts:
#             - name: backup-storage
#               mountPath: /var/backups/postgres
#           volumes:
#           - name: backup-storage
#             persistentVolumeClaim:
#               claimName: backup-pvc
#           restartPolicy: OnFailure
#
# ---
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: cargobit-audit-verify
#   namespace: cargobit
# spec:
#   schedule: "0 4 * * *"
#   concurrencyPolicy: Forbid
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: audit-verify
#             image: cargobit/api:latest
#             command: ["npx", "ts-node", "src/jobs/auditVerify.ts"]
#           restartPolicy: OnFailure
`;
  },

  /**
   * Generate Audit Log Export Tool
   */
  generateAuditExport() {
    return `/**
 * Audit Log Export Tool
 * Generated by SRE Agent v1.0.0
 * 
 * Exports audit logs for compliance reporting, archival, and analysis.
 * Supports multiple output formats and filtering options.
 */

import { prisma } from '@/lib/prisma';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

// =============================================================================
// TYPES
// =============================================================================

interface ExportOptions {
  startDate: Date;
  endDate: Date;
  format: 'json' | 'csv' | 'sql';
  outputPath?: string;
  includeUser?: boolean;
  anonymize?: boolean;
  compress?: boolean;
}

interface ExportResult {
  success: boolean;
  filePath: string;
  recordCount: number;
  sizeBytes: number;
  duration: number;
  error?: string;
}

// =============================================================================
// CONFIGURATION
// =============================================================================

const DEFAULT_EXPORT_DIR = process.env.AUDIT_EXPORT_DIR || '/var/exports/audit';
const BATCH_SIZE = 10000;

// =============================================================================
// EXPORT FUNCTIONS
// =============================================================================

/**
 * Export audit logs to JSON format
 */
async function exportToJson(options: ExportOptions): Promise<string> {
  const { startDate, endDate, outputPath, anonymize, includeUser } = options;
  
  const filePath = outputPath || join(
    DEFAULT_EXPORT_DIR,
    \`audit_export_\${startDate.toISOString().split('T')[0]}_\${endDate.toISOString().split('T')[0]}.json\`
  );
  
  // Ensure directory exists
  const dir = filePath.substring(0, filePath.lastIndexOf('/'));
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  
  // Stream logs in batches
  let allLogs: any[] = [];
  let skip = 0;
  let hasMore = true;
  
  while (hasMore) {
    const batch = await prisma.auditLog.findMany({
      where: {
        createdAt: { gte: startDate, lte: endDate }
      },
      orderBy: { createdAt: 'asc' },
      skip,
      take: BATCH_SIZE,
      include: includeUser ? {
        user: { select: { id: true, email: true, name: true } }
      } : false
    });
    
    if (batch.length === 0) {
      hasMore = false;
    } else {
      // Anonymize if requested
      const processedBatch = anonymize 
        ? batch.map(log => ({
            ...log,
            ipAddress: null,
            userAgent: null
          }))
        : batch;
      
      allLogs = allLogs.concat(processedBatch);
      skip += BATCH_SIZE;
      
      console.log(\`Exported \${allLogs.length} records...\`);
    }
  }
  
  // Write to file
  const output = {
    exportDate: new Date().toISOString(),
    dateRange: {
      start: startDate.toISOString(),
      end: endDate.toISOString()
    },
    recordCount: allLogs.length,
    logs: allLogs
  };
  
  writeFileSync(filePath, JSON.stringify(output, null, 2));
  
  return filePath;
}

/**
 * Export audit logs to CSV format
 */
async function exportToCsv(options: ExportOptions): Promise<string> {
  const { startDate, endDate, outputPath, anonymize } = options;
  
  const filePath = outputPath || join(
    DEFAULT_EXPORT_DIR,
    \`audit_export_\${startDate.toISOString().split('T')[0]}_\${endDate.toISOString().split('T')[0]}.csv\`
  );
  
  // Ensure directory exists
  const dir = filePath.substring(0, filePath.lastIndexOf('/'));
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  
  // CSV headers
  const headers = [
    'id', 'userId', 'action', 'entityType', 'entityId',
    'ipAddress', 'userAgent', 'requestId', 'createdAt'
  ];
  
  let csvContent = headers.join(',') + '\\n';
  
  // Stream logs
  let skip = 0;
  let hasMore = true;
  
  while (hasMore) {
    const batch = await prisma.auditLog.findMany({
      where: {
        createdAt: { gte: startDate, lte: endDate }
      },
      orderBy: { createdAt: 'asc' },
      skip,
      take: BATCH_SIZE,
      select: {
        id: true,
        userId: true,
        action: true,
        entityType: true,
        entityId: true,
        ipAddress: true,
        userAgent: true,
        requestId: true,
        createdAt: true
      }
    });
    
    if (batch.length === 0) {
      hasMore = false;
    } else {
      for (const log of batch) {
        const row = [
          log.id,
          log.userId || '',
          escapeCsv(log.action),
          escapeCsv(log.entityType),
          log.entityId || '',
          anonymize ? '' : (log.ipAddress || ''),
          anonymize ? '' : escapeCsv(log.userAgent || ''),
          log.requestId || '',
          log.createdAt.toISOString()
        ];
        
        csvContent += row.join(',') + '\\n';
      }
      
      skip += BATCH_SIZE;
      console.log(\`Processed \${skip} records...\`);
    }
  }
  
  writeFileSync(filePath, csvContent);
  
  return filePath;
}

/**
 * Export audit logs as SQL INSERT statements
 */
async function exportToSql(options: ExportOptions): Promise<string> {
  const { startDate, endDate, outputPath } = options;
  
  const filePath = outputPath || join(
    DEFAULT_EXPORT_DIR,
    \`audit_export_\${startDate.toISOString().split('T')[0]}_\${endDate.toISOString().split('T')[0]}.sql\`
  );
  
  // Ensure directory exists
  const dir = filePath.substring(0, filePath.lastIndexOf('/'));
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  
  let sqlContent = \`-- Audit Log Export
-- Generated: \${new Date().toISOString()}
-- Date Range: \${startDate.toISOString()} to \${endDate.toISOString()}

BEGIN;

\`;
  
  let skip = 0;
  let hasMore = true;
  
  while (hasMore) {
    const batch = await prisma.auditLog.findMany({
      where: {
        createdAt: { gte: startDate, lte: endDate }
      },
      orderBy: { createdAt: 'asc' },
      skip,
      take: BATCH_SIZE
    });
    
    if (batch.length === 0) {
      hasMore = false;
    } else {
      for (const log of batch) {
        sqlContent += \`INSERT INTO audit_logs (id, "userId", action, "entityType", "entityId", "oldValues", "newValues", "ipAddress", "userAgent", "requestId", "createdAt")
VALUES (
  '\${log.id}',
  \${log.userId ? \`'\${log.userId}'\` : 'NULL'},
  '\${escapeSql(log.action)}',
  '\${escapeSql(log.entityType)}',
  \${log.entityId ? \`'\${log.entityId}'\` : 'NULL'},
  '\${escapeSql(JSON.stringify(log.oldValues))}',
  '\${escapeSql(JSON.stringify(log.newValues))}',
  \${log.ipAddress ? \`'\${log.ipAddress}'\` : 'NULL'},
  \${log.userAgent ? \`'\${escapeSql(log.userAgent)}'\` : 'NULL'},
  \${log.requestId ? \`'\${log.requestId}'\` : 'NULL'},
  '\${log.createdAt.toISOString()}'
);
\`;
      }
      
      skip += BATCH_SIZE;
      console.log(\`Processed \${skip} records...\`);
    }
  }
  
  sqlContent += '\\nCOMMIT;\\n';
  
  writeFileSync(filePath, sqlContent);
  
  return filePath;
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

function escapeCsv(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\\n')) {
    return \`"\${value.replace(/"/g, '""')}"\`;
  }
  return value;
}

function escapeSql(value: string): string {
  return value.replace(/'/g, "''");
}

function getFileSize(filePath: string): number {
  const { statSync } = require('fs');
  return statSync(filePath).size;
}

// =============================================================================
// MAIN EXPORT FUNCTION
// =============================================================================

/**
 * Main export function
 */
export async function exportAuditLogs(options: ExportOptions): Promise<ExportResult> {
  const startTime = Date.now();
  
  console.log('Starting audit log export...');
  console.log(\`  Date range: \${options.startDate.toISOString()} to \${options.endDate.toISOString()}\`);
  console.log(\`  Format: \${options.format}\`);
  console.log(\`  Anonymize: \${options.anonymize || false}\`);
  
  try {
    let filePath: string;
    
    switch (options.format) {
      case 'json':
        filePath = await exportToJson(options);
        break;
      case 'csv':
        filePath = await exportToCsv(options);
        break;
      case 'sql':
        filePath = await exportToSql(options);
        break;
      default:
        throw new Error(\`Unsupported format: \${options.format}\`);
    }
    
    // Get record count
    const recordCount = await prisma.auditLog.count({
      where: {
        createdAt: { gte: options.startDate, lte: options.endDate }
      }
    });
    
    const result: ExportResult = {
      success: true,
      filePath,
      recordCount,
      sizeBytes: getFileSize(filePath),
      duration: Date.now() - startTime
    };
    
    console.log(\`\\nExport completed successfully:\`);
    console.log(\`  File: \${filePath}\`);
    console.log(\`  Records: \${recordCount}\`);
    console.log(\`  Size: \${(result.sizeBytes / 1024 / 1024).toFixed(2)} MB\`);
    console.log(\`  Duration: \${result.duration}ms\`);
    
    return result;
    
  } catch (error) {
    const result: ExportResult = {
      success: false,
      filePath: '',
      recordCount: 0,
      sizeBytes: 0,
      duration: Date.now() - startTime,
      error: error instanceof Error ? error.message : 'Unknown error'
    };
    
    console.error('Export failed:', result.error);
    return result;
  }
}

// =============================================================================
// CLI ENTRY POINT
// =============================================================================

async function main() {
  const args = process.argv.slice(2);
  
  // Parse CLI arguments
  let startDate = new Date();
  startDate.setDate(startDate.getDate() - 30); // Default: last 30 days
  
  let endDate = new Date();
  let format: 'json' | 'csv' | 'sql' = 'json';
  let anonymize = false;
  
  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--start':
        startDate = new Date(args[++i]);
        break;
      case '--end':
        endDate = new Date(args[++i]);
        break;
      case '--format':
        format = args[++i] as 'json' | 'csv' | 'sql';
        break;
      case '--anonymize':
        anonymize = true;
        break;
      case '--help':
        console.log(\`
Audit Log Export Tool

Usage: npx ts-node ops/export-audit-log.ts [OPTIONS]

Options:
  --start DATE    Start date (ISO format, default: 30 days ago)
  --end DATE      End date (ISO format, default: now)
  --format FORMAT Output format: json, csv, sql (default: json)
  --anonymize     Remove PII (IP addresses, user agents)
  --help          Show this help message

Examples:
  npx ts-node ops/export-audit-log.ts --start 2024-01-01 --end 2024-01-31 --format csv
  npx ts-node ops/export-audit-log.ts --anonymize
\`);
        process.exit(0);
    }
  }
  
  const result = await exportAuditLogs({
    startDate,
    endDate,
    format,
    anonymize
  });
  
  process.exit(result.success ? 0 : 1);
}

if (require.main === module) {
  main();
}

export default exportAuditLogs;
`;
  }
};
