#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
CargoBit Payment System - Comprehensive Analysis Report
Generated by Z.ai
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, ListFlowable, ListItem
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
import os

# Font registration - use available fonts
pdfmetrics.registerFont(TTFont('NotoSerifSC', '/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', '/usr/share/fonts/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('SarasaMonoSC', '/usr/share/fonts/truetype/chinese/SarasaMonoSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('SarasaMonoSC', normal='SarasaMonoSC', bold='SarasaMonoSC')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

# Colors
ACCENT = colors.HexColor('#2563eb')
TEXT_PRIMARY = colors.HexColor('#1f2937')
TEXT_MUTED = colors.HexColor('#6b7280')
BG_SURFACE = colors.HexColor('#f3f4f6')
RED_CRITICAL = colors.HexColor('#dc2626')
GREEN_OK = colors.HexColor('#16a34a')
YELLOW_WARNING = colors.HexColor('#d97706')

def create_styles():
    styles = getSampleStyleSheet()
    
    styles.add(ParagraphStyle(
        name='GermanTitle',
        fontName='NotoSerifSC',
        fontSize=28,
        leading=36,
        textColor=TEXT_PRIMARY,
        alignment=TA_CENTER,
        spaceAfter=20
    ))
    
    styles.add(ParagraphStyle(
        name='GermanSubtitle',
        fontName='SarasaMonoSC',
        fontSize=14,
        leading=20,
        textColor=TEXT_MUTED,
        alignment=TA_CENTER,
        spaceAfter=30
    ))
    
    styles.add(ParagraphStyle(
        name='GermanH1',
        fontName='NotoSerifSC',
        fontSize=18,
        leading=24,
        textColor=ACCENT,
        spaceBefore=20,
        spaceAfter=12
    ))
    
    styles.add(ParagraphStyle(
        name='GermanH2',
        fontName='NotoSerifSC',
        fontSize=14,
        leading=20,
        textColor=TEXT_PRIMARY,
        spaceBefore=16,
        spaceAfter=8
    ))
    
    styles.add(ParagraphStyle(
        name='GermanH3',
        fontName='SarasaMonoSC',
        fontSize=12,
        leading=18,
        textColor=TEXT_PRIMARY,
        spaceBefore=12,
        spaceAfter=6
    ))
    
    styles.add(ParagraphStyle(
        name='GermanBody',
        fontName='SarasaMonoSC',
        fontSize=10.5,
        leading=18,
        textColor=TEXT_PRIMARY,
        alignment=TA_JUSTIFY,
        wordWrap='CJK',
        spaceAfter=8
    ))
    
    styles.add(ParagraphStyle(
        name='GermanBodyLeft',
        fontName='SarasaMonoSC',
        fontSize=10.5,
        leading=18,
        textColor=TEXT_PRIMARY,
        alignment=TA_LEFT,
        wordWrap='CJK',
        spaceAfter=8
    ))
    
    styles.add(ParagraphStyle(
        name='TableCell',
        fontName='SarasaMonoSC',
        fontSize=9,
        leading=14,
        textColor=TEXT_PRIMARY,
        alignment=TA_LEFT,
        wordWrap='CJK'
    ))
    
    styles.add(ParagraphStyle(
        name='TableHeader',
        fontName='NotoSerifSC',
        fontSize=10,
        leading=14,
        textColor=colors.white,
        alignment=TA_CENTER
    ))
    
    return styles

def create_score_table(styles, title, items):
    """Create a score table with status indicators"""
    data = [[Paragraph('<b>Kategorie</b>', styles['TableHeader']),
             Paragraph('<b>Status</b>', styles['TableHeader']),
             Paragraph('<b>Bewertung</b>', styles['TableHeader']),
             Paragraph('<b>Empfehlung</b>', styles['TableHeader'])]]
    
    for item in items:
        category, status, score, recommendation = item
        if status == 'OK':
            status_color = GREEN_OK
            status_text = '✓ OK'
        elif status == 'WARN':
            status_color = YELLOW_WARNING
            status_text = '⚠ Warnung'
        else:
            status_color = RED_CRITICAL
            status_text = '✗ Kritisch'
        
        data.append([
            Paragraph(category, styles['TableCell']),
            Paragraph(f'<font color="{status_color.hexval()}">{status_text}</font>', styles['TableCell']),
            Paragraph(score, styles['TableCell']),
            Paragraph(recommendation, styles['TableCell'])
        ])
    
    table = Table(data, colWidths=[120, 70, 80, 200])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    return table

def build_report():
    output_path = '/home/z/my-project/download/CargoBit_Maturity_Analysis_Report.pdf'
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=1.5*cm,
        rightMargin=1.5*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )
    
    styles = create_styles()
    story = []
    
    # Title
    story.append(Paragraph('CargoBit Payment System', styles['GermanTitle']))
    story.append(Paragraph('Umfassende Reifegrad-Analyse', styles['GermanSubtitle']))
    story.append(Paragraph('Version 1.0 | 2026-05-02', styles['GermanSubtitle']))
    story.append(Spacer(1, 30))
    
    # Executive Summary
    story.append(Paragraph('1. Zusammenfassung', styles['GermanH1']))
    story.append(Paragraph(
        'CargoBit ist ein umfangreiches europäisches Logistik-Marktplatz-System mit integriertem '
        'Zahlungssystem. Die Analyse zeigt eine technisch gut durchdachte Architektur mit über '
        '150 API-Endpunkten, 50+ Service-Modulen und einer umfassenden Microservice-Struktur. '
        'Das Projekt weist jedoch erhebliche Lücken in der operativen Bereitschaft, Sicherheit, '
        'Compliance und Skalierbarkeit auf, die vor einer Produktionsveröffentlichung behoben '
        'werden müssen.',
        styles['GermanBody']
    ))
    
    story.append(Paragraph(
        'Die Codebasis ist architektonisch reif und zeigt professionelle Entwicklungspraktiken. '
        'Die Hauptherausforderungen liegen nicht im Code selbst, sondern in den fehlenden '
        'operationalen Prozessen und Infrastrukturkomponenten für einen produktiven Betrieb.',
        styles['GermanBody']
    ))
    
    # Overall Score Table
    story.append(Spacer(1, 12))
    overall_data = [
        [Paragraph('<b>Bereich</b>', styles['TableHeader']),
         Paragraph('<b>Reifegrad</b>', styles['TableHeader']),
         Paragraph('<b>Status</b>', styles['TableHeader'])],
        [Paragraph('Code-Qualität', styles['TableCell']),
         Paragraph('85%', styles['TableCell']),
         Paragraph('<font color="#16a34a">Gut</font>', styles['TableCell'])],
        [Paragraph('Operational Readiness', styles['TableCell']),
         Paragraph('40%', styles['TableCell']),
         Paragraph('<font color="#dc2626">Kritisch</font>', styles['TableCell'])],
        [Paragraph('Security-Reife', styles['TableCell']),
         Paragraph('55%', styles['TableCell']),
         Paragraph('<font color="#d97706">Warnung</font>', styles['TableCell'])],
        [Paragraph('Compliance-Reife', styles['TableCell']),
         Paragraph('35%', styles['TableCell']),
         Paragraph('<font color="#dc2626">Kritisch</font>', styles['TableCell'])],
        [Paragraph('Business-Reife', styles['TableCell']),
         Paragraph('30%', styles['TableCell']),
         Paragraph('<font color="#dc2626">Kritisch</font>', styles['TableCell'])],
        [Paragraph('Scalability', styles['TableCell']),
         Paragraph('45%', styles['TableCell']),
         Paragraph('<font color="#d97706">Warnung</font>', styles['TableCell'])],
    ]
    overall_table = Table(overall_data, colWidths=[200, 100, 150])
    overall_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (1, 1), (-1, -1), 'CENTER'),
    ]))
    story.append(overall_table)
    
    # Section 2: Code Quality
    story.append(PageBreak())
    story.append(Paragraph('2. Code-Qualität und Architektur', styles['GermanH1']))
    
    story.append(Paragraph('2.1 Stärken', styles['GermanH2']))
    story.append(Paragraph(
        'Die CargoBit-Codebasis zeigt eine beeindruckende architektonische Reife. Das System '
        'verwendet Next.js 16 mit App Router, TypeScript für Typsicherheit und eine klare '
        'Separation of Concerns. Die Microservice-Architektur ist gut strukturiert mit '
        'eigenständigen Services für Pricing, Matching, Risk, Security und ML-Operations.',
        styles['GermanBody']
    ))
    
    strengths = [
        'Umfangreiche Prisma-Schema-Definition mit 40+ Modellen und korrekten Relationen',
        '50+ Service-Module mit klarer Verantwortungstrennung',
        '40+ UI-Komponenten basierend auf shadcn/ui (Radix)',
        'BullMQ für zuverlässige Job-Queue-Verarbeitung implementiert',
        'SLO/SLI-Definitionen für alle Services vorhanden',
        'Prometheus-Metriken und Grafana-Dashboards vorbereitet',
        'Umfangreiche Dokumentation (70+ Dokumente)',
    ]
    for s in strengths:
        story.append(Paragraph(f'• {s}', styles['GermanBodyLeft']))
    
    story.append(Paragraph('2.2 Verbesserungsbereiche', styles['GermanH2']))
    story.append(Paragraph(
        'Trotz der guten Architektur gibt es einige Bereiche, die Aufmerksamkeit erfordern. '
        'Die Testabdeckung ist dokumentiert aber nicht durchgehend implementiert. Einige '
        'Services haben mehr Implementierung als andere.',
        styles['GermanBody']
    ))
    
    # Section 3: Operational Readiness
    story.append(Paragraph('3. Operational Readiness', styles['GermanH1']))
    story.append(Paragraph(
        'Die operative Bereitschaft ist der kritischste Bereich. Ohne diese Komponenten '
        'kann das System nicht sicher in Produktion genommen werden.',
        styles['GermanBody']
    ))
    
    ops_items = [
        ('Monitoring', 'OK', 'Vorhanden', 'Prometheus + Grafana konfiguriert'),
        ('Alerting', 'OK', 'Vorhanden', 'SLO-basierte Alerts definiert'),
        ('Incident Playbooks', 'OK', 'Vorhanden', '5 Playbooks für kritische Services'),
        ('On-Call Runbook', 'OK', 'Vorhanden', 'Umfassendes Runbook dokumentiert'),
        ('Backups', 'CRIT', 'Fehlend', 'Keine Backup-Strategie implementiert'),
        ('Disaster Recovery', 'CRIT', 'Fehlend', 'Kein DR-Plan oder RTO/RPO definiert'),
        ('Observability Traces', 'WARN', 'Teilweise', 'Tempo konfiguriert, aber nicht aktiv'),
        ('Log Aggregation', 'WARN', 'Teilweise', 'Loki-Format definiert, kein Cluster'),
    ]
    story.append(Spacer(1, 8))
    story.append(create_score_table(styles, 'Operational Readiness', ops_items))
    
    story.append(Spacer(1, 12))
    story.append(Paragraph('3.1 Kritische Lücken', styles['GermanH3']))
    story.append(Paragraph(
        '<b>Backup-Strategie:</b> Es gibt keine automatisierten Datenbank-Backups. Für ein '
        'Zahlungssystem ist dies inakzeptabel. Mindestens tägliche Backups mit Point-in-Time '
        'Recovery (PITR) müssen implementiert werden. Backup-Tests und Restore-Verfahren '
        'müssen dokumentiert und regelmäßig durchgeführt werden.',
        styles['GermanBody']
    ))
    story.append(Paragraph(
        '<b>Disaster Recovery:</b> Es fehlt ein vollständiger DR-Plan mit definierten RTO '
        '(Recovery Time Objective) und RPO (Recovery Point Objective). Für ein Payment-System '
        'sollte RTO < 4 Stunden und RPO < 1 Stunde angestrebt werden. Multi-Region-Deployments '
        'sind für echte Ausfallsicherheit erforderlich.',
        styles['GermanBody']
    ))
    
    # Section 4: Security
    story.append(PageBreak())
    story.append(Paragraph('4. Security-Reife', styles['GermanH1']))
    
    story.append(Paragraph(
        'Die Sicherheit hat eine solide Basis mit einigen fortgeschrittenen Features, '
        'aber es bestehen kritische Lücken bei der operativen Sicherheit.',
        styles['GermanBody']
    ))
    
    sec_items = [
        ('Secrets Management', 'OK', 'Gut', 'Verschlüsselte Speicherung + Rotation'),
        ('Key Rotation', 'OK', 'Gut', 'Stripe Key Rotation Flow implementiert'),
        ('Token TTL', 'WARN', 'Teilweise', 'Keine explizite TTL-Konfiguration'),
        ('Webhook Replay Protection', 'OK', 'Gut', 'StripeEvent Deduplication aktiv'),
        ('Audit Log Tamper-proof', 'CRIT', 'Fehlend', 'Keine unveränderbaren Logs'),
        ('Rate Limiting', 'WARN', 'Teilweise', 'In-Memory Fallback riskant'),
        ('Encryption at Rest', 'WARN', 'Teilweise', 'Nur für Secrets, nicht DB'),
    ]
    story.append(Spacer(1, 8))
    story.append(create_score_table(styles, 'Security-Reife', sec_items))
    
    story.append(Spacer(1, 12))
    story.append(Paragraph('4.1 Positive Sicherheitsmerkmale', styles['GermanH3']))
    story.append(Paragraph(
        '<b>Stripe Webhook Idempotency:</b> Das System implementiert eine robuste '
        'Idempotency-Prüfung mittels StripeEvent-Tabelle. Doppelte Webhooks werden zuverlässig '
        'erkannt und ignoriert. Dies ist eine kritische Anforderung für Payment-Systeme.',
        styles['GermanBody']
    ))
    story.append(Paragraph(
        '<b>Key Rotation:</b> Der Secrets-Service unterstützt Key-Rotation mit Active/Next '
        'Slots. Neue Keys können getestet werden bevor sie aktiviert werden. Dies entspricht '
        'Best Practices für Kryptographie-Management.',
        styles['GermanBody']
    ))
    
    story.append(Paragraph('4.2 Kritische Sicherheitslücken', styles['GermanH3']))
    story.append(Paragraph(
        '<b>Audit Log Manipulation:</b> Die Audit-Logs sind in der Standard-Datenbank '
        'gespeichert und können von jedem mit Datenbankzugriff manipuliert werden. Für '
        'Compliance und forensische Zwecke müssen Logs append-only sein (z.B. in einem '
        'separaten, schreibgeschützten System oder Blockchain-basiert).',
        styles['GermanBody']
    ))
    story.append(Paragraph(
        '<b>Rate Limiting Fallback:</b> Der InMemoryRedisStore ist für Entwicklung akzeptabel, '
        'aber gefährlich in Produktion. Bei einem Neustart gehen alle Rate-Limit-Daten verloren, '
        'was Angreifer begünstigt. Redis muss extern und persistent betrieben werden.',
        styles['GermanBody']
    ))
    
    # Section 5: Compliance
    story.append(Paragraph('5. Compliance-Reife', styles['GermanH1']))
    
    story.append(Paragraph(
        'Compliance ist der am wenigsten entwickelte Bereich. Für ein Payment-System '
        'in der EU sind diese Lücken geschäftskritisch.',
        styles['GermanBody']
    ))
    
    comp_items = [
        ('GDPR Data Flows', 'CRIT', 'Fehlend', 'Keine Datenschutz-Folgenabschätzung'),
        ('Data Retention', 'OK', 'Gut', 'Umfassende Policies definiert'),
        ('DPIA', 'CRIT', 'Fehlend', 'Keine Datenschutz-Folgenabschätzung'),
        ('Consent Management', 'CRIT', 'Fehlend', 'Keine Einwilligungsverwaltung'),
        ('Vendor Risk Management', 'WARN', 'Teilweise', 'Dokumentiert, nicht implementiert'),
        ('ISO27001', 'WARN', 'Teilweise', 'Policy-Suite vorhanden, nicht zertifiziert'),
        ('SOC2', 'WARN', 'Teilweise', 'Checklist vorhanden, nicht auditiert'),
    ]
    story.append(Spacer(1, 8))
    story.append(create_score_table(styles, 'Compliance-Reife', comp_items))
    
    story.append(Spacer(1, 12))
    story.append(Paragraph(
        '<b>GDPR:</b> Als Payment-System verarbeitet CargoBit personenbezogene Daten. '
        'Eine Datenschutz-Folgenabschätzung (DPIA) ist nach Art. 35 DSGVO zwingend erforderlich. '
        'Datenschutzfreundliche Voreinstellungen (Privacy by Design) müssen implementiert werden. '
        'Ein Verzeichnis von Verarbeitungstätigkeiten muss geführt werden.',
        styles['GermanBody']
    ))
    
    # Section 6: Business
    story.append(PageBreak())
    story.append(Paragraph('6. Business-Reife', styles['GermanH1']))
    
    story.append(Paragraph(
        'Die geschäftliche Bereitschaft ist für einen MVP-Start unzureichend. Diese '
        'Lücken müssen vor der ersten Kundenakquise geschlossen werden.',
        styles['GermanBody']
    ))
    
    bus_items = [
        ('Pricing Model', 'WARN', 'Teilweise', 'Plans definiert, keine Abrechnung'),
        ('Billing System', 'CRIT', 'Fehlend', 'Keine automatische Abrechnung'),
        ('Support System', 'WARN', 'Teilweise', 'Tickets in DB, kein Prozess'),
        ('SLAs', 'CRIT', 'Fehlend', 'Keine SLAs definiert'),
        ('Onboarding Flow', 'WARN', 'Teilweise', 'UI vorhanden, kein Prozess'),
        ('Legal Terms', 'CRIT', 'Fehlend', 'AGB/Datenschutz fehlen'),
        ('Partner Agreements', 'CRIT', 'Fehlend', 'Keine Vertragsvorlagen'),
    ]
    story.append(Spacer(1, 8))
    story.append(create_score_table(styles, 'Business-Reife', bus_items))
    
    story.append(Spacer(1, 12))
    story.append(Paragraph(
        '<b>Rechtliche Dokumente:</b> Vor dem Start benötigt das System: AGB für Shipper '
        'und Carrier, Datenschutzerklärung, Impressum, Widerrufsbelehrung (für Verbraucher), '
        'und Partnerverträge. Ohne diese Dokumente ist ein operativer Start rechtlich riskant.',
        styles['GermanBody']
    ))
    story.append(Paragraph(
        '<b>Billing:</b> Das System hat Plans (Free/Starter/Professional/Enterprise) definiert, '
        'aber keine automatische Abrechnung. Stripe Subscriptions muss integriert werden für '
        'wiederkehrende Zahlungen. Usage-basierte Abrechnung für Kommissionen muss implementiert werden.',
        styles['GermanBody']
    ))
    
    # Section 7: Scalability
    story.append(Paragraph('7. Scalability-Risiken', styles['GermanH1']))
    
    story.append(Paragraph(
        'Die Skalierbarkeit hat architektonisch gute Ansätze, aber einige fundamentale '
        'Probleme verhindern einen reibungslosen Produktionsbetrieb.',
        styles['GermanBody']
    ))
    
    scale_items = [
        ('SQLite', 'CRIT', 'Kritisch', 'Nicht für Produktion geeignet'),
        ('In-Memory Rate Limiting', 'CRIT', 'Kritisch', 'Gefährlich bei Neustart'),
        ('Queue Backpressure', 'WARN', 'Teilweise', 'BullMQ Limiter vorhanden'),
        ('Dead Letter Queue', 'OK', 'Gut', 'In BullMQ integriert'),
        ('Horizontal Scaling', 'OK', 'Gut', 'Stateless Services + Redis'),
        ('Database Connection Pool', 'WARN', 'Teilweise', 'Prisma Pool, keine Limits'),
    ]
    story.append(Spacer(1, 8))
    story.append(create_score_table(styles, 'Scalability-Risiken', scale_items))
    
    story.append(Spacer(1, 12))
    story.append(Paragraph('7.1 SQLite-Problem', styles['GermanH3']))
    story.append(Paragraph(
        'Das Prisma-Schema ist auf SQLite konfiguriert. SQLite ist ein hervorragendes '
        'Entwicklungstool, aber für ein Payment-System in Produktion absolut ungeeignet. '
        'Gründe: Keine echten Concurrent Writes, keine Replikation möglich, begrenzte '
        'Datenbankgröße, keine Point-in-Time Recovery. PostgreSQL muss zwingend verwendet werden.',
        styles['GermanBody']
    ))
    story.append(Paragraph(
        '<b>Lösung:</b> Ändern Sie prisma/schema.prisma: provider = "postgresql" und '
        'konfigurieren Sie DATABASE_URL für eine verwaltete PostgreSQL-Instanz (Neon, Supabase, '
        'oder AWS RDS). Führen Sie Prisma Migrate durch und testen Sie alle Queries.',
        styles['GermanBody']
    ))
    
    story.append(Paragraph('7.2 Queue-Architektur', styles['GermanH3']))
    story.append(Paragraph(
        'Die Payout-Queue-Service-Implementierung mit BullMQ ist professionell. Wichtige '
        'Features sind vorhanden: Idempotency-Checks, Exponential Backoff, Concurrency-Limits, '
        'und Job-Prioritäten. Dead-Letter-Queue wird durch BullMQ automatisch unterstützt '
        '(failed Jobs bleiben erhalten). Der limiter (max: 100/minute) ist ein gutes Backpressure-Mechanism.',
        styles['GermanBody']
    ))
    
    # Section 8: Recommendations
    story.append(PageBreak())
    story.append(Paragraph('8. Empfehlungen', styles['GermanH1']))
    
    story.append(Paragraph('8.1 Sofortige Maßnahmen (vor MVP-Start)', styles['GermanH2']))
    
    immediate = [
        'PostgreSQL statt SQLite konfigurieren (kritisch)',
        'Redis für Rate Limiting und Sessions einrichten',
        'Backup-Strategie implementieren (täglich + PITR)',
        'AGB, Datenschutz, Impressum von einem Anwalt erstellen lassen',
        'Monitoring-Stack (Prometheus + Grafana) deployen',
        'Stripe Webhooks im Live-Modus testen',
    ]
    for i, item in enumerate(immediate, 1):
        story.append(Paragraph(f'{i}. {item}', styles['GermanBodyLeft']))
    
    story.append(Paragraph('8.2 Kurzfristige Maßnahmen (1-2 Wochen)', styles['GermanH2']))
    
    short_term = [
        'Disaster Recovery Plan dokumentieren',
        'Audit Logs in separates, append-only System auslagern',
        'SLAs für verschiedene Pläne definieren',
        'Billing mit Stripe Subscriptions implementieren',
        'Support-Prozess und Ticket-System einrichten',
        'Load Tests mit k6 durchführen',
    ]
    for i, item in enumerate(short_term, 1):
        story.append(Paragraph(f'{i}. {item}', styles['GermanBodyLeft']))
    
    story.append(Paragraph('8.3 Mittelfristige Maßnahmen (1-3 Monate)', styles['GermanH2']))
    
    mid_term = [
        'DPIA durchführen und dokumentieren',
        'ISO27001-Zertifizierung vorbereiten',
        'Multi-Region-Deployment für DR',
        'Penetrationstest durchführen',
        'Partner-Onboarding-Prozess automatisieren',
        'Compliance-Reporting automatisieren',
    ]
    for i, item in enumerate(mid_term, 1):
        story.append(Paragraph(f'{i}. {item}', styles['GermanBodyLeft']))
    
    # Section 9: Release Readiness
    story.append(Paragraph('9. Release-Readiness', styles['GermanH1']))
    
    story.append(Paragraph(
        'Kann CargoBit erfolgreich veröffentlicht werden? Die Antwort ist ein bedingtes "Ja". '
        'Die technische Basis ist solide, aber die operativen und geschäftlichen Voraussetzungen '
        'müssen erst geschaffen werden.',
        styles['GermanBody']
    ))
    
    story.append(Spacer(1, 12))
    
    release_data = [
        [Paragraph('<b>Aspekt</b>', styles['TableHeader']),
         Paragraph('<b>Bewertung</b>', styles['TableHeader']),
         Paragraph('<b>Zeitaufwand</b>', styles['TableHeader'])],
        [Paragraph('Technisch', styles['TableCell']),
         Paragraph('<font color="#16a34a">Bereit</font>', styles['TableCell']),
         Paragraph('2-3 Tage', styles['TableCell'])],
        [Paragraph('Operational', styles['TableCell']),
         Paragraph('<font color="#dc2626">Nicht bereit</font>', styles['TableCell']),
         Paragraph('1-2 Wochen', styles['TableCell'])],
        [Paragraph('Security', styles['TableCell']),
         Paragraph('<font color="#d97706">Teilweise</font>', styles['TableCell']),
         Paragraph('3-5 Tage', styles['TableCell'])],
        [Paragraph('Compliance', styles['TableCell']),
         Paragraph('<font color="#dc2626">Nicht bereit</font>', styles['TableCell']),
         Paragraph('2-4 Wochen', styles['TableCell'])],
        [Paragraph('Business', styles['TableCell']),
         Paragraph('<font color="#dc2626">Nicht bereit</font>', styles['TableCell']),
         Paragraph('1-2 Wochen', styles['TableCell'])],
    ]
    release_table = Table(release_data, colWidths=[180, 120, 120])
    release_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (1, 1), (-1, -1), 'CENTER'),
    ]))
    story.append(release_table)
    
    story.append(Spacer(1, 16))
    story.append(Paragraph(
        '<b>Geschätzter Zeitrahmen bis MVP-Release:</b> 3-6 Wochen bei Vollzeit-Entwicklung. '
        'Ein Pilot-Start mit ausgewählten Partnern ist nach 2-3 Wochen möglich, wenn die '
        'kritischen Sicherheits- und Backup-Maßnahmen implementiert sind.',
        styles['GermanBody']
    ))
    
    story.append(Paragraph(
        '<b>Empfehlung:</b> Starten Sie mit einem geschlossenen Beta-Programm mit 3-5 vertrauenswürdigen '
        'Partnern. Dies ermöglicht das Sammeln von Feedback und das Testen der operativen Prozesse '
        'unter kontrollierten Bedingungen vor dem öffentlichen Launch.',
        styles['GermanBody']
    ))
    
    # Build
    doc.build(story)
    print(f'PDF generated: {output_path}')
    return output_path

if __name__ == '__main__':
    build_report()
